sav_pok_names = ["", "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", "Squirtle", "Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree", "Weedle", "Kakuna", "Beedrill", "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate", "Spearow", "Fearow", "Ekans", "Arbok", "Pikachu", "Raichu", "Sandshrew", "Sandslash", "Nidoran-F", "Nidorina", "Nidoqueen", "Nidoran-M", "Nidorino", "Nidoking", "Clefairy", "Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff", "Zubat", "Golbat", "Oddish", "Gloom", "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth", "Diglett", "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck", "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath", "Abra", "Kadabra", "Alakazam", "Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool", "Tentacruel", "Geodude", "Graveler", "Golem", "Ponyta", "Rapidash", "Slowpoke", "Slowbro", "Magnemite", "Magneton", "Farfetch’d", "Doduo", "Dodrio", "Seel", "Dewgong", "Grimer", "Muk", "Shellder", "Cloyster", "Gastly", "Haunter", "Gengar", "Onix", "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak", "Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Chansey", "Tangela", "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu", "Starmie", "Mr. Mime", "Scyther", "Jynx", "Electabuzz", "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados", "Lapras", "Ditto", "Eevee", "Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto", "Kabutops", "Aerodactyl", "Snorlax", "Articuno", "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew", "Chikorita", "Bayleef", "Meganium", "Cyndaquil", "Quilava", "Typhlosion", "Totodile", "Croconaw", "Feraligatr", "Sentret", "Furret", "Hoothoot", "Noctowl", "Ledyba", "Ledian", "Spinarak", "Ariados", "Crobat", "Chinchou", "Lanturn", "Pichu", "Cleffa", "Igglybuff", "Togepi", "Togetic", "Natu", "Xatu", "Mareep", "Flaaffy", "Ampharos", "Bellossom", "Marill", "Azumarill", "Sudowoodo", "Politoed", "Hoppip", "Skiploom", "Jumpluff", "Aipom", "Sunkern", "Sunflora", "Yanma", "Wooper", "Quagsire", "Espeon", "Umbreon", "Murkrow", "Slowking", "Misdreavus", "Unown", "Wobbuffet", "Girafarig", "Pineco", "Forretress", "Dunsparce", "Gligar", "Steelix", "Snubbull", "Granbull", "Qwilfish", "Scizor", "Shuckle", "Heracross", "Sneasel", "Teddiursa", "Ursaring", "Slugma", "Magcargo", "Swinub", "Piloswine", "Corsola", "Remoraid", "Octillery", "Delibird", "Mantine", "Skarmory", "Houndour", "Houndoom", "Kingdra", "Phanpy", "Donphan", "Porygon2", "Stantler", "Smeargle", "Tyrogue", "Hitmontop", "Smoochum", "Elekid", "Magby", "Miltank", "Blissey", "Raikou", "Entei", "Suicune", "Larvitar", "Pupitar", "Tyranitar", "Lugia", "Ho-Oh", "Celebi", "Treecko", "Grovyle", "Sceptile", "Torchic", "Combusken", "Blaziken", "Mudkip", "Marshtomp", "Swampert", "Poochyena", "Mightyena", "Zigzagoon", "Linoone", "Wurmple", "Silcoon", "Beautifly", "Cascoon", "Dustox", "Lotad", "Lombre", "Ludicolo", "Seedot", "Nuzleaf", "Shiftry", "Taillow", "Swellow", "Wingull", "Pelipper", "Ralts", "Kirlia", "Gardevoir", "Surskit", "Masquerain", "Shroomish", "Breloom", "Slakoth", "Vigoroth", "Slaking", "Nincada", "Ninjask", "Shedinja", "Whismur", "Loudred", "Exploud", "Makuhita", "Hariyama", "Azurill", "Nosepass", "Skitty", "Delcatty", "Sableye", "Mawile", "Aron", "Lairon", "Aggron", "Meditite", "Medicham", "Electrike", "Manectric", "Plusle", "Minun", "Volbeat", "Illumise", "Roselia", "Gulpin", "Swalot", "Carvanha", "Sharpedo", "Wailmer", "Wailord", "Numel", "Camerupt", "Torkoal", "Spoink", "Grumpig", "Spinda", "Trapinch", "Vibrava", "Flygon", "Cacnea", "Cacturne", "Swablu", "Altaria", "Zangoose", "Seviper", "Lunatone", "Solrock", "Barboach", "Whiscash", "Corphish", "Crawdaunt", "Baltoy", "Claydol", "Lileep", "Cradily", "Anorith", "Armaldo", "Feebas", "Milotic", "Castform", "Kecleon", "Shuppet", "Banette", "Duskull", "Dusclops", "Tropius", "Chimecho", "Absol", "Wynaut", "Snorunt", "Glalie", "Spheal", "Sealeo", "Walrein", "Clamperl", "Huntail", "Gorebyss", "Relicanth", "Luvdisc", "Bagon", "Shelgon", "Salamence", "Beldum", "Metang", "Metagross", "Regirock", "Regice", "Registeel", "Latias", "Latios", "Kyogre", "Groudon", "Rayquaza", "Jirachi", "Deoxys", "Turtwig", "Grotle", "Torterra", "Chimchar", "Monferno", "Infernape", "Piplup", "Prinplup", "Empoleon", "Starly", "Staravia", "Staraptor", "Bidoof", "Bibarel", "Kricketot", "Kricketune", "Shinx", "Luxio", "Luxray", "Budew", "Roserade", "Cranidos", "Rampardos", "Shieldon", "Bastiodon", "Burmy", "Wormadam", "Mothim", "Combee", "Vespiquen", "Pachirisu", "Buizel", "Floatzel", "Cherubi", "Cherrim", "Shellos", "Gastrodon", "Ambipom", "Drifloon", "Drifblim", "Buneary", "Lopunny", "Mismagius", "Honchkrow", "Glameow", "Purugly", "Chingling", "Stunky", "Skuntank", "Bronzor", "Bronzong", "Bonsly", "Mime Jr.", "Happiny", "Chatot", "Spiritomb", "Gible", "Gabite", "Garchomp", "Munchlax", "Riolu", "Lucario", "Hippopotas", "Hippowdon", "Skorupi", "Drapion", "Croagunk", "Toxicroak", "Carnivine", "Finneon", "Lumineon", "Mantyke", "Snover", "Abomasnow", "Weavile", "Magnezone", "Lickilicky", "Rhyperior", "Tangrowth", "Electivire", "Magmortar", "Togekiss", "Yanmega", "Leafeon", "Glaceon", "Gliscor", "Mamoswine", "Porygon-Z", "Gallade", "Probopass", "Dusknoir", "Froslass", "Rotom", "Uxie", "Mesprit", "Azelf", "Dialga", "Palkia", "Heatran", "Regigigas", "Giratina", "Cresselia", "Phione", "Manaphy", "Darkrai", "Shaymin", "Arceus", "Victini", "Snivy", "Servine", "Serperior", "Tepig", "Pignite", "Emboar", "Oshawott", "Dewott", "Samurott", "Patrat", "Watchog", "Lillipup", "Herdier", "Stoutland", "Purrloin", "Liepard", "Pansage", "Simisage", "Pansear", "Simisear", "Panpour", "Simipour", "Munna", "Musharna", "Pidove", "Tranquill", "Unfezant", "Blitzle", "Zebstrika", "Roggenrola", "Boldore", "Gigalith", "Woobat", "Swoobat", "Drilbur", "Excadrill", "Audino", "Timburr", "Gurdurr", "Conkeldurr", "Tympole", "Palpitoad", "Seismitoad", "Throh", "Sawk", "Sewaddle", "Swadloon", "Leavanny", "Venipede", "Whirlipede", "Scolipede", "Cottonee", "Whimsicott", "Petilil", "Lilligant", "Basculin", "Sandile", "Krokorok", "Krookodile", "Darumaka", "Darmanitan", "Maractus", "Dwebble", "Crustle", "Scraggy", "Scrafty", "Sigilyph", "Yamask", "Cofagrigus", "Tirtouga", "Carracosta", "Archen", "Archeops", "Trubbish", "Garbodor", "Zorua", "Zoroark", "Minccino", "Cinccino", "Gothita", "Gothorita", "Gothitelle", "Solosis", "Duosion", "Reuniclus", "Ducklett", "Swanna", "Vanillite", "Vanillish", "Vanilluxe", "Deerling", "Sawsbuck", "Emolga", "Karrablast", "Escavalier", "Foongus", "Amoonguss", "Frillish", "Jellicent", "Alomomola", "Joltik", "Galvantula", "Ferroseed", "Ferrothorn", "Klink", "Klang", "Klinklang", "Tynamo", "Eelektrik", "Eelektross", "Elgyem", "Beheeyem", "Litwick", "Lampent", "Chandelure", "Axew", "Fraxure", "Haxorus", "Cubchoo", "Beartic", "Cryogonal", "Shelmet", "Accelgor", "Stunfisk", "Mienfoo", "Mienshao", "Druddigon", "Golett", "Golurk", "Pawniard", "Bisharp", "Bouffalant", "Rufflet", "Braviary", "Vullaby", "Mandibuzz", "Heatmor", "Durant", "Deino", "Zweilous", "Hydreigon", "Larvesta", "Volcarona", "Cobalion", "Terrakion", "Virizion", "Tornadus", "Thundurus", "Reshiram", "Zekrom", "Landorus", "Kyurem", "Keldeo", "Meloetta", "Genesect", "Egg", "Bad Egg", "    ", "     ", "    ", "    ", "     ", "    ", "    ", "    ", "    ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "     ", "    ", "     ", "     ", "     ", "     ", "    ", "    "]

sav_move_names =  ["-----", "Pound", "Karate Chop", "Double Slap", "Comet Punch", "Mega Punch", "Pay Day", "Fire Punch", "Ice Punch", "Thunder Punch", "Scratch", "Vise Grip", "Guillotine", "Razor Wind", "Swords Dance", "Cut", "Gust", "Wing Attack", "Whirlwind", "Fly", "Bind", "Slam", "Vine Whip", "Stomp", "Double Kick", "Mega Kick", "Jump Kick", "Rolling Kick", "Sand Attack", "Headbutt", "Horn Attack", "Fury Attack", "Horn Drill", "Tackle", "Body Slam", "Wrap", "Take Down", "Thrash", "Double-Edge", "Tail Whip", "Poison Sting", "Twineedle", "Pin Missile", "Leer", "Bite", "Growl", "Roar", "Sing", "Supersonic", "Sonic Boom", "Disable", "Acid", "Ember", "Flamethrower", "Mist", "Water Gun", "Hydro Pump", "Surf", "Ice Beam", "Blizzard", "Psybeam", "Bubble Beam", "Aurora Beam", "Hyper Beam", "Peck", "Drill Peck", "Submission", "Low Kick", "Counter", "Seismic Toss", "Strength", "Absorb", "Mega Drain", "Leech Seed", "Growth", "Razor Leaf", "Solar Beam", "Poison Powder", "Stun Spore", "Sleep Powder", "Petal Dance", "String Shot", "Dragon Rage", "Fire Spin", "Thunder Shock", "Thunderbolt", "Thunder Wave", "Thunder", "Rock Throw", "Earthquake", "Fissure", "Dig", "Toxic", "Confusion", "Psychic", "Hypnosis", "Meditate", "Agility", "Quick Attack", "Rage", "Teleport", "Night Shade", "Mimic", "Screech", "Double Team", "Recover", "Harden", "Minimize", "Smokescreen", "Confuse Ray", "Withdraw", "Defense Curl", "Barrier", "Light Screen", "Haze", "Reflect", "Focus Energy", "Bide", "Metronome", "Mirror Move", "Self-Destruct", "Egg Bomb", "Lick", "Smog", "Sludge", "Bone Club", "Fire Blast", "Waterfall", "Clamp", "Swift", "Skull Bash", "Spike Cannon", "Constrict", "Amnesia", "Kinesis", "Soft-Boiled", "High Jump Kick", "Glare", "Dream Eater", "Poison Gas", "Barrage", "Leech Life", "Lovely Kiss", "Sky Attack", "Transform", "Bubble", "Dizzy Punch", "Spore", "Flash", "Psywave", "Splash", "Acid Armor", "Crabhammer", "Explosion", "Fury Swipes", "Bonemerang", "Rest", "Rock Slide", "Hyper Fang", "Sharpen", "Conversion", "Tri Attack", "Super Fang", "Slash", "Substitute", "Struggle", "Sketch", "Triple Kick", "Thief", "Spider Web", "Mind Reader", "Nightmare", "Flame Wheel", "Snore", "Curse", "Flail", "Conversion 2", "Aeroblast", "Cotton Spore", "Reversal", "Spite", "Powder Snow", "Protect", "Mach Punch", "Scary Face", "Feint Attack", "Sweet Kiss", "Belly Drum", "Sludge Bomb", "Mud-Slap", "Octazooka", "Spikes", "Zap Cannon", "Foresight", "Destiny Bond", "Perish Song", "Icy Wind", "Detect", "Bone Rush", "Lock-On", "Outrage", "Sandstorm", "Giga Drain", "Endure", "Charm", "Rollout", "False Swipe", "Swagger", "Milk Drink", "Spark", "Fury Cutter", "Steel Wing", "Mean Look", "Attract", "Sleep Talk", "Heal Bell", "Return", "Present", "Frustration", "Safeguard", "Pain Split", "Sacred Fire", "Magnitude", "Dynamic Punch", "Megahorn", "Dragon Breath", "Baton Pass", "Encore", "Pursuit", "Rapid Spin", "Sweet Scent", "Iron Tail", "Metal Claw", "Vital Throw", "Morning Sun", "Synthesis", "Moonlight", "Hidden Power", "Cross Chop", "Twister", "Rain Dance", "Sunny Day", "Crunch", "Mirror Coat", "Psych Up", "Extreme Speed", "Ancient Power", "Shadow Ball", "Future Sight", "Rock Smash", "Whirlpool", "Beat Up", "Fake Out", "Uproar", "Stockpile", "Spit Up", "Swallow", "Heat Wave", "Hail", "Torment", "Flatter", "Will-O-Wisp", "Memento", "Facade", "Focus Punch", "Smelling Salts", "Follow Me", "Nature Power", "Charge", "Taunt", "Helping Hand", "Trick", "Role Play", "Wish", "Assist", "Ingrain", "Superpower", "Magic Coat", "Recycle", "Revenge", "Brick Break", "Yawn", "Knock Off", "Endeavor", "Eruption", "Skill Swap", "Imprison", "Refresh", "Grudge", "Snatch", "Secret Power", "Dive", "Arm Thrust", "Camouflage", "Tail Glow", "Luster Purge", "Mist Ball", "Feather Dance", "Teeter Dance", "Blaze Kick", "Mud Sport", "Ice Ball", "Needle Arm", "Slack Off", "Hyper Voice", "Poison Fang", "Crush Claw", "Blast Burn", "Hydro Cannon", "Meteor Mash", "Astonish", "Weather Ball", "Aromatherapy", "Fake Tears", "Air Cutter", "Overheat", "Odor Sleuth", "Rock Tomb", "Silver Wind", "Metal Sound", "Grass Whistle", "Tickle", "Cosmic Power", "Water Spout", "Signal Beam", "Shadow Punch", "Extrasensory", "Sky Uppercut", "Sand Tomb", "Sheer Cold", "Muddy Water", "Bullet Seed", "Aerial Ace", "Icicle Spear", "Iron Defense", "Block", "Howl", "Dragon Claw", "Frenzy Plant", "Bulk Up", "Bounce", "Mud Shot", "Poison Tail", "Covet", "Volt Tackle", "Magical Leaf", "Water Sport", "Calm Mind", "Leaf Blade", "Dragon Dance", "Rock Blast", "Shock Wave", "Water Pulse", "Doom Desire", "Psycho Boost", "Roost", "Gravity", "Miracle Eye", "Wake-Up Slap", "Hammer Arm", "Gyro Ball", "Healing Wish", "Brine", "Natural Gift", "Feint", "Pluck", "Tailwind", "Acupressure", "Metal Burst", "U-turn", "Close Combat", "Payback", "Assurance", "Embargo", "Fling", "Psycho Shift", "Trump Card", "Heal Block", "Wring Out", "Power Trick", "Gastro Acid", "Lucky Chant", "Me First", "Copycat", "Power Swap", "Guard Swap", "Punishment", "Last Resort", "Worry Seed", "Sucker Punch", "Toxic Spikes", "Heart Swap", "Aqua Ring", "Magnet Rise", "Flare Blitz", "Force Palm", "Aura Sphere", "Rock Polish", "Poison Jab", "Dark Pulse", "Night Slash", "Aqua Tail", "Seed Bomb", "Air Slash", "X-Scissor", "Bug Buzz", "Dragon Pulse", "Dragon Rush", "Power Gem", "Drain Punch", "Vacuum Wave", "Focus Blast", "Energy Ball", "Brave Bird", "Earth Power", "Switcheroo", "Giga Impact", "Nasty Plot", "Bullet Punch", "Avalanche", "Ice Shard", "Shadow Claw", "Thunder Fang", "Ice Fang", "Fire Fang", "Shadow Sneak", "Mud Bomb", "Psycho Cut", "Zen Headbutt", "Mirror Shot", "Flash Cannon", "Rock Climb", "Defog", "Trick Room", "Draco Meteor", "Discharge", "Lava Plume", "Leaf Storm", "Power Whip", "Rock Wrecker", "Cross Poison", "Gunk Shot", "Iron Head", "Magnet Bomb", "Stone Edge", "Captivate", "Stealth Rock", "Grass Knot", "Chatter", "Judgment", "Bug Bite", "Charge Beam", "Wood Hammer", "Aqua Jet", "Attack Order", "Defend Order", "Heal Order", "Head Smash", "Double Hit", "Roar of Time", "Spacial Rend", "Lunar Dance", "Crush Grip", "Magma Storm", "Dark Void", "Seed Flare", "Ominous Wind", "Shadow Force", "Hone Claws", "Wide Guard", "Guard Split", "Power Split", "Wonder Room", "Psyshock", "Venoshock", "Autotomize", "Rage Powder", "Telekinesis", "Magic Room", "Smack Down", "Storm Throw", "Flame Burst", "Sludge Wave", "Quiver Dance", "Heavy Slam", "Synchronoise", "Electro Ball", "Soak", "Flame Charge", "Coil", "Low Sweep", "Acid Spray", "Foul Play", "Simple Beam", "Entrainment", "After You", "Round", "Echoed Voice", "Chip Away", "Clear Smog", "Stored Power", "Quick Guard", "Ally Switch", "Scald", "Shell Smash", "Heal Pulse", "Hex", "Sky Drop", "Shift Gear", "Circle Throw", "Incinerate", "Quash", "Acrobatics", "Reflect Type", "Retaliate", "Final Gambit", "Bestow", "Inferno", "Water Pledge", "Fire Pledge", "Grass Pledge", "Volt Switch", "Struggle Bug", "Bulldoze", "Frost Breath", "Dragon Tail", "Work Up", "Electroweb", "Wild Charge", "Drill Run", "Dual Chop", "Heart Stamp", "Horn Leech", "Sacred Sword", "Razor Shell", "Heat Crash", "Leaf Tornado", "Steamroller", "Cotton Guard", "Night Daze", "Psystrike", "Tail Slap", "Hurricane", "Head Charge", "Gear Grind", "Searing Shot", "Techno Blast", "Relic Song", "Secret Sword", "Glaciate", "Bolt Strike", "Blue Flare", "Fiery Dance", "Freeze Shock", "Ice Burn", "Snarl", "Icicle Crash", "V-create", "Fusion Flare", "Fusion Bolt"]
sav_item_names = ["None", "Master Ball", "Ultra Ball", "Great Ball", "Poke Ball", "Safari Ball", "Net Ball", "Dive Ball", "Nest Ball", "Repeat Ball", "Timer Ball", "Luxury Ball", "Premier Ball", "Dusk Ball", "Heal Ball", "Quick Ball", "Cherish Ball", "Potion", "Antidote", "Burn Heal", "Ice Heal", "Awakening", "Parlyz Heal", "Full Restore", "Max Potion", "Hyper Potion", "Super Potion", "Full Heal", "Revive", "Max Revive", "Fresh Water", "Soda Pop", "Lemonade", "Moomoo Milk", "Energy Powder", "Energy Root", "Heal Powder", "Revival Herb", "Ether", "Max Ether", "Elixir", "Max Elixir", "Lava Cookie", "Berry Juice", "Sacred Ash", "HP Up", "Protein", "Iron", "Carbos", "Calcium", "Rare Candy", "PP Up", "Zinc", "PP Max", "Old Gateau", "Guard Spec.", "Dire Hit", "X Attack", "X Defend", "X Speed", "X Accuracy", "X Special", "X Sp. Def", "Poke Doll", "Fluffy Tail", "Blue Flute", "Yellow Flute", "Red Flute", "Black Flute", "White Flute", "Shoal Salt", "Shoal Shell", "Red Shard", "Blue Shard", "Yellow Shard", "Green Shard", "Super Repel", "Max Repel", "Escape Rope", "Repel", "Sun Stone", "Moon Stone", "Fire Stone", "Thunderstone", "Water Stone", "Leaf Stone", "Tiny Mushroom", "Big Mushroom", "Pearl", "Big Pearl", "Stardust", "Star Piece", "Nugget", "Heart Scale", "Honey", "Growth Mulch", "Damp Mulch", "Stable Mulch", "Gooey Mulch", "Root Fossil", "Claw Fossil", "Helix Fossil", "Dome Fossil", "Old Amber", "Armor Fossil", "Skull Fossil", "Rare Bone", "Shiny Stone", "Dusk Stone", "Dawn Stone", "Oval Stone", "Odd Keystone", "Griseous Orb", "???", "???", "???", "Douse Drive", "Shock Drive", "Burn Drive", "Chill Drive", "???", "???", "???", "???", "???", "???", "???", "???", "???", "???", "???", "???", "???", "???", "Sweet Heart", "Adamant Orb", "Lustrous Orb", "Greet Mail", "Favored Mail", "RSVP Mail", "Thanks Mail", "Inquiry Mail", "Like Mail", "Reply Mail", "Bridge Mail S", "Bridge Mail D", "Bridge Mail T", "Bridge Mail V", "Bridge Mail M", "Cheri Berry", "Chesto Berry", "Pecha Berry", "Rawst Berry", "Aspear Berry", "Leppa Berry", "Oran Berry", "Persim Berry", "Lum Berry", "Sitrus Berry", "Figy Berry", "Wiki Berry", "Mago Berry", "Aguav Berry", "Iapapa Berry", "Razz Berry", "Bluk Berry", "Nanab Berry", "Wepear Berry", "Pinap Berry", "Pomeg Berry", "Kelpsy Berry", "Qualot Berry", "Hondew Berry", "Grepa Berry", "Tamato Berry", "Cornn Berry", "Magost Berry", "Rabuta Berry", "Nomel Berry", "Spelon Berry", "Pamtre Berry", "Watmel Berry", "Durin Berry", "Belue Berry", "Occa Berry", "Passho Berry", "Wacan Berry", "Rindo Berry", "Yache Berry", "Chople Berry", "Kebia Berry", "Shuca Berry", "Coba Berry", "Payapa Berry", "Tanga Berry", "Charti Berry", "Kasib Berry", "Haban Berry", "Colbur Berry", "Babiri Berry", "Chilan Berry", "Liechi Berry", "Ganlon Berry", "Salac Berry", "Petaya Berry", "Apicot Berry", "Lansat Berry", "Starf Berry", "Enigma Berry", "Micle Berry", "Custap Berry", "Jaboca Berry", "Rowap Berry", "Bright Powder", "White Herb", "Macho Brace", "Exp. Share", "Quick Claw", "Soothe Bell", "Mental Herb", "Choice Band", "King’s Rock", "Silver Powder", "Amulet Coin", "Cleanse Tag", "Soul Dew", "Deep Sea Tooth", "Deep Sea Scale", "Smoke Ball", "Everstone", "Focus Band", "Lucky Egg", "Scope Lens", "Metal Coat", "Leftovers", "Dragon Scale", "Light Ball", "Soft Sand", "Hard Stone", "Miracle Seed", "Black Glasses", "Black Belt", "Magnet", "Mystic Water", "Sharp Beak", "Poison Barb", "Never Melt Ice", "Spell Tag", "Twisted Spoon", "Charcoal", "Dragon Fang", "Silk Scarf", "Up-Grade", "Shell Bell", "Sea Incense", "Lax Incense", "Lucky Punch", "Metal Powder", "Thick Club", "Stick", "Red Scarf", "Blue Scarf", "Pink Scarf", "Green Scarf", "Yellow Scarf", "Wide Lens", "Muscle Band", "Wise Glasses", "Expert Belt", "Light Clay", "Life Orb", "Power Herb", "Toxic Orb", "Flame Orb", "Quick Powder", "Focus Sash", "Zoom Lens", "Metronome", "Iron Ball", "Lagging Tail", "Destiny Knot", "Black Sludge", "Icy Rock", "Smooth Rock", "Heat Rock", "Damp Rock", "Grip Claw", "Choice Scarf", "Sticky Barb", "Power Bracer", "Power Belt", "Power Lens", "Power Band", "Power Anklet", "Power Weight", "Shed Shell", "Big Root", "Choice Specs", "Flame Plate", "Splash Plate", "Zap Plate", "Meadow Plate", "Icicle Plate", "Fist Plate", "Toxic Plate", "Earth Plate", "Sky Plate", "Mind Plate", "Insect Plate", "Stone Plate", "Spooky Plate", "Draco Plate", "Dread Plate", "Iron Plate", "Odd Incense", "Rock Incense", "Full Incense", "Wave Incense", "Rose Incense", "Luck Incense", "Pure Incense", "Protector", "Electirizer", "Magmarizer", "Dubious Disc", "Reaper Cloth", "Razor Claw", "Razor Fang", "TM01", "TM02", "TM03", "TM04", "TM05", "TM06", "TM07", "TM08", "TM09", "TM10", "TM11", "TM12", "TM13", "TM14", "TM15", "TM16", "TM17", "TM18", "TM19", "TM20", "TM21", "TM22", "TM23", "TM24", "TM25", "TM26", "TM27", "TM28", "TM29", "TM30", "TM31", "TM32", "TM33", "TM34", "TM35", "TM36", "TM37", "TM38", "TM39", "TM40", "TM41", "TM42", "TM43", "TM44", "TM45", "TM46", "TM47", "TM48", "TM49", "TM50", "TM51", "TM52", "TM53", "TM54", "TM55", "TM56", "TM57", "TM58", "TM59", "TM60", "TM61", "TM62", "TM63", "TM64", "TM65", "TM66", "TM67", "TM68", "TM69", "TM70", "TM71", "TM72", "TM73", "TM74", "TM75", "TM76", "TM77", "TM78", "TM79", "TM80", "TM81", "TM82", "TM83", "TM84", "TM85", "TM86", "TM87", "TM88", "TM89", "TM90", "TM91", "TM92", "HM01", "HM02", "HM03", "HM04", "HM05", "HM06", "???", "???", "Explorer Kit", "Loot Sack", "Rule Book", "Poke Radar", "Point Card", "Journal", "Seal Case", "Fashion Case", "Seal Bag", "Pal Pad", "Works Key", "Old Charm", "Galactic Key", "Red Chain", "Town Map", "Vs. Seeker", "Coin Case", "Old Rod", "Good Rod", "Super Rod", "Sprayduck", "Poffin Case", "Bicycle", "Suite Key", "Oak’s Letter", "Lunar Wing", "Member Card", "Azure Flute", "S.S. Ticket", "Contest Pass", "Magma Stone", "Parcel", "Coupon 1", "Coupon 2", "Coupon 3", "Storage Key", "Secret Potion", "Vs. Recorder", "Gracidea", "Secret Key", "Apricorn Box", "Unown Report", "Berry Pots", "Dowsing MCHN", "Blue Card", "Slowpoke Tail", "Clear Bell", "Card Key", "Basement Key", "Squirt Bottle", "Red Scale", "Lost Item", "Pass", "Machine Part", "Silver Wing", "Rainbow Wing", "Mystery Egg", "Red Apricorn", "Blu Apricorn", "Ylw Apricorn", "Grn Apricorn", "Pnk Apricorn", "Wht Apricorn", "Blk Apricorn", "Fast Ball", "Level Ball", "Lure Ball", "Heavy Ball", "Love Ball", "Friend Ball", "Moon Ball", "Sport Ball", "Park Ball", "Photo Album", "GB Sounds", "Tidal Bell", "Rage Candy Bar", "Data Card 1", "Data Card 2", "Data Card 3", "Data Card 4", "Data Card 5", "Data Card 6", "Data Card 7", "Data Card 8", "Data Card 9", "Data Card 10", "Data Card 11", "Data Card 12", "Data Card 13", "Data Card 14", "Data Card 15", "Data Card 16", "Data Card 17", "Data Card 18", "Data Card 19", "Data Card 20", "Data Card 21", "Data Card 22", "Data Card 23", "Data Card 24", "Data Card 25", "Data Card 26", "Data Card 27", "Jade Orb", "Lock Capsule", "Red Orb", "Blue Orb", "Enigma Stone", "Prism Scale", "Eviolite", "Float Stone", "Rocky Helmet", "Air Balloon", "Red Card", "Ring Target", "Binding Band", "Absorb Bulb", "Cell Battery", "Eject Button", "Fire Gem", "Water Gem", "Electric Gem", "Grass Gem", "Ice Gem", "Fighting Gem", "Poison Gem", "Ground Gem", "Flying Gem", "Psychic Gem", "Bug Gem", "Rock Gem", "Ghost Gem", "Dragon Gem", "Dark Gem", "Steel Gem", "Normal Gem", "Health Wing", "Muscle Wing", "Resist Wing", "Genius Wing", "Clever Wing", "Swift Wing", "Pretty Wing", "Cover Fossil", "Plume Fossil", "Liberty Pass", "Pass Orb", "Dream Ball", "Poke Toy", "Prop Case", "Dragon Skull", "Balm Mushroom", "Big Nugget", "Pearl String", "Comet Shard", "Relic Copper", "Relic Silver", "Relic Gold", "Relic Vase", "Relic Band", "Relic Statue", "Relic Crown", "Casteliacone", "Dire Hit 2", "X Speed 2", "X Special 2", "X Sp. Def 2", "X Defend 2", "X Attack 2", "X Accuracy 2", "X Speed 3", "X Special 3", "X Sp. Def 3", "X Defend 3", "X Attack 3", "X Accuracy 3", "X Speed 6", "X Special 6", "X Sp. Def 6", "X Defend 6", "X Attack 6", "X Accuracy 6", "Ability Urge", "Item Drop", "Item Urge", "Reset Urge", "Dire Hit 3", "Light Stone", "Dark Stone", "TM93", "TM94", "TM95", "Xtransceiver", "???", "Gram 1", "Gram 2", "Gram 3", "Xtransceiver", "Medal Box", "DNA Splicers", "DNA Splicers", "Permit", "Oval Charm", "Shiny Charm", "Plasma Card", "Grubby Hanky", "Colress MCHN", "Dropped Item", "Dropped Item", "Reveal Glass"]
sav_pok_growths = [0,3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,3,3,3,0,0,0,0,0,0,0,0,0,0,3,3,3,3,3,3,4,4,0,0,4,4,0,0,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,5,5,3,3,3,3,3,3,3,3,3,3,3,3,5,5,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,3,3,3,0,0,0,0,0,0,0,5,5,0,0,0,0,0,0,0,5,5,4,0,0,0,0,0,0,5,5,0,0,0,0,0,5,5,5,5,5,0,0,0,0,0,0,0,0,0,0,5,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,3,0,0,0,0,4,4,4,4,0,5,5,0,4,4,4,4,0,0,3,3,3,3,4,4,0,3,3,3,3,4,3,3,0,0,0,0,0,3,0,4,0,0,0,0,0,0,3,0,4,4,0,0,3,5,3,0,0,0,0,5,5,4,0,0,4,5,5,5,5,0,0,0,0,5,4,0,0,0,0,0,5,4,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,0,0,0,3,3,3,3,3,3,3,3,0,0,5,5,5,0,0,2,2,5,5,5,1,1,1,3,3,3,2,2,4,0,4,4,3,4,5,5,5,0,0,5,5,0,0,1,2,3,2,2,5,5,2,2,0,0,0,4,4,4,3,3,3,3,3,1,1,1,2,4,4,0,0,2,2,0,0,1,1,1,1,1,1,0,3,4,4,4,4,5,4,3,0,0,0,3,3,3,1,1,1,5,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3,3,3,3,3,1,1,1,1,0,0,0,3,3,0,0,0,0,0,0,0,4,2,2,0,0,4,3,4,4,4,0,0,0,0,0,0,4,3,0,5,5,5,5,3,3,5,5,5,5,0,0,5,1,1,5,5,5,3,0,0,5,0,0,0,4,0,0,0,3,5,0,5,0,4,0,0,5,5,5,5,5,5,5,5,5,5,5,5,3,5,5,3,3,3,3,3,3,3,3,3,0,0,3,3,3,0,0,4,4,4,4,4,4,4,4,3,3,3,0,0,3,3,3,0,0,0,0,4,3,3,3,3,3,3,0,0,3,3,3,3,3,3,0,0,0,0,0,3,3,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,4,4,3,3,3,3,3,3,0,0,5,5,5,0,0,0,0,0,0,0,0,0,4,0,0,0,0,3,3,3,5,5,5,0,0,3,3,3,5,5,5,0,0,0,0,0,0,3,3,0,0,0,0,0,0,5,5,5,5,0,0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,5,5,5,0,0,3,5,0,0,0,0,0,0,0,0,0,3,5,5,5,5,5,5,5]
sav_abilities = ["  ", "Stench", "Drizzle", "Speed Boost", "Battle Armor", "Sturdy", "Damp", "Limber", "Sand Veil", "Static", "Volt Absorb", "Water Absorb", "Oblivious", "Cloud Nine", "Compound Eyes", "Insomnia", "Color Change", "Immunity", "Flash Fire", "Shield Dust", "Own Tempo", "Suction Cups", "Intimidate", "Shadow Tag", "Rough Skin", "Wonder Guard", "Levitate", "Effect Spore", "Synchronize", "Clear Body", "Natural Cure", "Lightning Rod", "Serene Grace", "Swift Swim", "Chlorophyll", "Illuminate", "Trace", "Huge Power", "Poison Point", "Inner Focus", "Magma Armor", "Water Veil", "Magnet Pull", "Soundproof", "Rain Dish", "Sand Stream", "Pressure", "Thick Fat", "Early Bird", "Flame Body", "Run Away", "Keen Eye", "Hyper Cutter", "Pickup", "Truant", "Hustle", "Cute Charm", "Plus", "Minus", "Forecast", "Sticky Hold", "Shed Skin", "Guts", "Marvel Scale", "Liquid Ooze", "Overgrow", "Blaze", "Torrent", "Swarm", "Rock Head", "Drought", "Arena Trap", "Vital Spirit", "White Smoke", "Pure Power", "Shell Armor", "Air Lock", "Tangled Feet", "Motor Drive", "Rivalry", "Steadfast", "Snow Cloak", "Gluttony", "Anger Point", "Unburden", "Heatproof", "Simple", "Dry Skin", "Download", "Iron Fist", "Poison Heal", "Adaptability", "Skill Link", "Hydration", "Solar Power", "Quick Feet", "Normalize", "Sniper", "Magic Guard", "No Guard", "Stall", "Technician", "Leaf Guard", "Klutz", "Mold Breaker", "Super Luck", "Aftermath", "Anticipation", "Forewarn", "Unaware", "Tinted Lens", "Filter", "Slow Start", "Scrappy", "Storm Drain", "Ice Body", "Solid Rock", "Snow Warning", "Honey Gather", "Frisk", "Reckless", "Multitype", "Flower Gift", "Bad Dreams", "Pickpocket", "Sheer Force", "Contrary", "Unnerve", "Defiant", "Defeatist", "Cursed Body", "Healer", "Friend Guard", "Weak Armor", "Heavy Metal", "Light Metal", "Multiscale", "Toxic Boost", "Flare Boost", "Harvest", "Telepathy", "Moody", "Overcoat", "Poison Touch", "Regenerator", "Big Pecks", "Sand Rush", "Wonder Skin", "Analytic", "Illusion", "Imposter", "Infiltrator", "Mummy", "Moxie", "Justified", "Rattled", "Magic Bounce", "Sap Sipper", "Prankster", "Sand Force", "Iron Barbs", "Zen Mode", "Victory Star", "Turboblaze", "Teravolt"]

inc_em_mons = ["-----","Bulbasaur","Ivysaur","Venusaur","Charmander","Charmeleon","Charizard","Squirtle","Wartortle","Blastoise","Caterpie","Metapod","Butterfree","Weedle","Kakuna","Beedrill","Pidgey","Pidgeotto","Pidgeot","Rattata","Raticate","Spearow","Fearow","Ekans","Arbok","Pikachu","Raichu","Sandshrew","Sandslash","Nidoran-F","Nidorina","Nidoqueen","Nidoran-M","Nidorino","Nidoking","Clefairy","Clefable","Vulpix","Ninetales","Jigglypuff","Wigglytuff","Zubat","Golbat","Oddish","Gloom","Vileplume","Paras","Parasect","Venonat","Venomoth","Diglett","Dugtrio","Meowth","Persian","Psyduck","Golduck","Mankey","Primeape","Growlithe","Arcanine","Poliwag","Poliwhirl","Poliwrath","Abra","Kadabra","Alakazam","Machop","Machoke","Machamp","Bellsprout","Weepinbell","Victreebel","Tentacool","Tentacruel","Geodude","Graveler","Golem","Ponyta","Rapidash","Slowpoke","Slowbro","Magnemite","Magneton","Farfetchd","Doduo","Dodrio","Seel","Dewgong","Grimer","Muk","Shellder","Cloyster","Gastly","Haunter","Gengar","Onix","Drowzee","Hypno","Krabby","Kingler","Voltorb","Electrode","Exeggcute","Exeggutor","Cubone","Marowak","Hitmonlee","Hitmonchan","Lickitung","Koffing","Weezing","Rhyhorn","Rhydon","Chansey","Tangela","Kangaskhan","Horsea","Seadra","Goldeen","Seaking","Staryu","Starmie","Mr-Mime","Scyther","Jynx","Electabuzz","Magmar","Pinsir","Tauros","Magikarp","Gyarados","Lapras","Ditto","Eevee","Vaporeon","Jolteon","Flareon","Porygon","Omanyte","Omastar","Kabuto","Kabutops","Aerodactyl","Snorlax","Articuno","Zapdos","Moltres","Dratini","Dragonair","Dragonite","Mewtwo","Mew","Chikorita","Bayleef","Meganium","Cyndaquil","Quilava","Typhlosion","Totodile","Croconaw","Feraligatr","Sentret","Furret","Hoothoot","Noctowl","Ledyba","Ledian","Spinarak","Ariados","Crobat","Chinchou","Lanturn","Pichu","Cleffa","Igglybuff","Togepi","Togetic","Natu","Xatu","Mareep","Flaaffy","Ampharos","Bellossom","Marill","Azumarill","Sudowoodo","Politoed","Hoppip","Skiploom","Jumpluff","Aipom","Sunkern","Sunflora","Yanma","Wooper","Quagsire","Espeon","Umbreon","Murkrow","Slowking","Misdreavus","Unown","Wobbuffet","Girafarig","Pineco","Forretress","Dunsparce","Gligar","Steelix","Snubbull","Granbull","Qwilfish","Scizor","Shuckle","Heracross","Sneasel","Teddiursa","Ursaring","Slugma","Magcargo","Swinub","Piloswine","Corsola","Remoraid","Octillery","Delibird","Mantine","Skarmory","Houndour","Houndoom","Kingdra","Phanpy","Donphan","Porygon2","Stantler","Smeargle","Tyrogue","Hitmontop","Smoochum","Elekid","Magby","Miltank","Blissey","Raikou","Entei","Suicune","Larvitar","Pupitar","Tyranitar","Lugia","Ho-Oh","Celebi","Treecko","Grovyle","Sceptile","Torchic","Combusken","Blaziken","Mudkip","Marshtomp","Swampert","Poochyena","Mightyena","Zigzagoon","Linoone","Wurmple","Silcoon","Beautifly","Cascoon","Dustox","Lotad","Lombre","Ludicolo","Seedot","Nuzleaf","Shiftry","Taillow","Swellow","Wingull","Pelipper","Ralts","Kirlia","Gardevoir","Surskit","Masquerain","Shroomish","Breloom","Slakoth","Vigoroth","Slaking","Nincada","Ninjask","Shedinja","Whismur","Loudred","Exploud","Makuhita","Hariyama","Azurill","Nosepass","Skitty","Delcatty","Sableye","Mawile","Aron","Lairon","Aggron","Meditite","Medicham","Electrike","Manectric","Plusle","Minun","Volbeat","Illumise","Roselia","Gulpin","Swalot","Carvanha","Sharpedo","Wailmer","Wailord","Numel","Camerupt","Torkoal","Spoink","Grumpig","Spinda","Trapinch","Vibrava","Flygon","Cacnea","Cacturne","Swablu","Altaria","Zangoose","Seviper","Lunatone","Solrock","Barboach","Whiscash","Corphish","Crawdaunt","Baltoy","Claydol","Lileep","Cradily","Anorith","Armaldo","Feebas","Milotic","Castform","Kecleon","Shuppet","Banette","Duskull","Dusclops","Tropius","Chimecho","Absol","Wynaut","Snorunt","Glalie","Spheal","Sealeo","Walrein","Clamperl","Huntail","Gorebyss","Relicanth","Luvdisc","Bagon","Shelgon","Salamence","Beldum","Metang","Metagross","Regirock","Regice","Registeel","Latias","Latios","Kyogre","Groudon","Rayquaza","Jirachi","Deoxys","Turtwig","Grotle","Torterra","Chimchar","Monferno","Infernape","Piplup","Prinplup","Empoleon","Starly","Staravia","Staraptor","Bidoof","Bibarel","Kricketot","Kricketune","Shinx","Luxio","Luxray","Budew","Roserade","Cranidos","Rampardos","Shieldon","Bastiodon","Burmy","Wormadam","Mothim","Combee","Vespiquen","Pachirisu","Buizel","Floatzel","Cherubi","Cherrim","Shellos","Gastrodon","Ambipom","Drifloon","Drifblim","Buneary","Lopunny","Mismagius","Honchkrow","Glameow","Purugly","Chingling","Stunky","Skuntank","Bronzor","Bronzong","Bonsly","Mime-Jr","Happiny","Chatot","Spiritomb","Gible","Gabite","Garchomp","Munchlax","Riolu","Lucario","Hippopotas","Hippowdon","Skorupi","Drapion","Croagunk","Toxicroak","Carnivine","Finneon","Lumineon","Mantyke","Snover","Abomasnow","Weavile","Magnezone","Lickilicky","Rhyperior","Tangrowth","Electivire","Magmortar","Togekiss","Yanmega","Leafeon","Glaceon","Gliscor","Mamoswine","Porygon-Z","Gallade","Probopass","Dusknoir","Froslass","Rotom","Uxie","Mesprit","Azelf","Dialga","Palkia","Heatran","Regigigas","Giratina","Cresselia","Phione","Manaphy","Darkrai","Shaymin","Arceus","Victini","Snivy","Servine","Serperior","Tepig","Pignite","Emboar","Oshawott","Dewott","Samurott","Patrat","Watchog","Lillipup","Herdier","Stoutland","Purrloin","Liepard","Pansage","Simisage","Pansear","Simisear","Panpour","Simipour","Munna","Musharna","Pidove","Tranquill","Unfezant","Blitzle","Zebstrika","Roggenrola","Boldore","Gigalith","Woobat","Swoobat","Drilbur","Excadrill","Audino","Timburr","Gurdurr","Conkeldurr","Tympole","Palpitoad","Seismitoad","Throh","Sawk","Sewaddle","Swadloon","Leavanny","Venipede","Whirlipede","Scolipede","Cottonee","Whimsicott","Petilil","Lilligant","Basculin","Sandile","Krokorok","Krookodile","Darumaka","Darmanitan","Maractus","Dwebble","Crustle","Scraggy","Scrafty","Sigilyph","Yamask","Cofagrigus","Tirtouga","Carracosta","Archen","Archeops","Trubbish","Garbodor","Zorua","Zoroark","Minccino","Cinccino","Gothita","Gothorita","Gothitelle","Solosis","Duosion","Reuniclus","Ducklett","Swanna","Vanillite","Vanillish","Vanilluxe","Deerling","Sawsbuck","Emolga","Karrablast","Escavalier","Foongus","Amoonguss","Frillish","Jellicent","Alomomola","Joltik","Galvantula","Ferroseed","Ferrothorn","Klink","Klang","Klinklang","Tynamo","Eelektrik","Eelektross","Elgyem","Beheeyem","Litwick","Lampent","Chandelure","Axew","Fraxure","Haxorus","Cubchoo","Beartic","Cryogonal","Shelmet","Accelgor","Stunfisk","Mienfoo","Mienshao","Druddigon","Golett","Golurk","Pawniard","Bisharp","Bouffalant","Rufflet","Braviary","Vullaby","Mandibuzz","Heatmor","Durant","Deino","Zweilous","Hydreigon","Larvesta","Volcarona","Cobalion","Terrakion","Virizion","Tornadus","Thundurus","Reshiram","Zekrom","Landorus","Kyurem","Keldeo","Meloetta","Genesect","Chespin","Quilladin","Chesnaught","Fennekin","Braixen","Delphox","Froakie","Frogadier","Greninja","Bunnelby","Diggersby","Fletchling","Fletchinder","Talonflame","Scatterbug","Spewpa","Vivillon","Litleo","Pyroar","Flabebe","Floette","Florges","Skiddo","Gogoat","Pancham","Pangoro","Furfrou","Espurr","Meowstic","Honedge","Doublade","Aegislash","Spritzee","Aromatisse","Swirlix","Slurpuff","Inkay","Malamar","Binacle","Barbaracle","Skrelp","Dragalge","Clauncher","Clawitzer","Helioptile","Heliolisk","Tyrunt","Tyrantrum","Amaura","Aurorus","Sylveon","Hawlucha","Dedenne","Carbink","Goomy","Sliggoo","Goodra","Klefki","Phantump","Trevenant","Pumpkaboo","Gourgeist","Bergmite","Avalugg","Noibat","Noivern","Xerneas","Yveltal","Zygarde","Diancie","Hoopa","Volcanion","Rowlet","Dartrix","Decidueye","Litten","Torracat","Incineroar","Popplio","Brionne","Primarina","Pikipek","Trumbeak","Toucannon","Yungoos","Gumshoos","Grubbin","Charjabug","Vikavolt","Crabrawler","Crabominable","Oricorio","Cutiefly","Ribombee","Rockruff","Lycanroc","Wishiwashi","Mareanie","Toxapex","Mudbray","Mudsdale","Dewpider","Araquanid","Fomantis","Lurantis","Morelull","Shiinotic","Salandit","Salazzle","Stufful","Bewear","Bounsweet","Steenee","Tsareena","Comfey","Oranguru","Passimian","Wimpod","Golisopod","Sandygast","Palossand","Pyukumuku","Type-Null","Silvally","Minior","Komala","Turtonator","Togedemaru","Mimikyu","Bruxish","Drampa","Dhelmise","Jangmo-o","Hakamo-o","Kommo-o","Tapu Koko","Tapu Lele","Tapu-Bulu","Tapu-Fini","Cosmog","Cosmoem","Solgaleo","Lunala","Nihilego","Buzzwole","Pheromosa","Xurkitree","Celesteela","Kartana","Guzzlord","Necrozma","Magearna","Marshadow","Poipole","Naganadel","Stakataka","Blacephalon","Zeraora","Meltan","Melmetal","Grookey","Thwackey","Rillaboom","Scorbunny","Raboot","Cinderace","Sobble","Drizzile","Inteleon","Skwovet","Greedent","Rookidee","Corvisquire","Corviknight","Blipbug","Dottler","Orbeetle","Nickit","Thievul","Gossifleur","Eldegoss","Wooloo","Dubwool","Chewtle","Drednaw","Yamper","Boltund","Rolycoly","Carkol","Coalossal","Applin","Flapple","Appletun","Silicobra","Sandaconda","Cramorant","Arrokuda","Barraskewda","Toxel","Toxtricity","Sizzlipede","Centiskorch","Clobbopus","Grapploct","Sinistea","Polteageist","Hatenna","Hattrem","Hatterene","Impidimp","Morgrem","Grimmsnarl","Obstagoon","Perrserker","Cursola","Sirfetchd","Mr-Rime","Runerigus","Milcery","Alcremie","Falinks","Pincurchin","Snom","Frosmoth","Stonjourner","Eiscue","Indeedee","Morpeko","Cufant","Copperajah","Dracozolt","Arctozolt","Dracovish","Arctovish","Duraludon","Dreepy","Drakloak","Dragapult","Zacian","Zamazenta","Eternatus","Kubfu","Urshifu","Zarude","Regieleki","Regidrago","Glastrier","Spectrier","Calyrex","Venusaur-Mega","Charizard-Mega-X","Charizard-Mega-Y","Blastoise-Mega","Beedrill-Mega","Pidgeot-Mega","Alakazam-Mega","Slowbro-Mega","Gengar-Mega","Kangaskhan-Mega","Pinsir-Mega","Gyarados-Mega","Aerodactyl-Mega","Mewtwo-Mega-X","Mewtwo-Mega-Y","Ampharos-Mega","Steelix-Mega","Scizor-Mega","Heracross-Mega","Houndoom-Mega","Tyranitar-Mega","Sceptile-Mega","Blaziken-Mega","Swampert-Mega","Gardevoir-Mega","Sableye-Mega","Mawile-Mega","Aggron-Mega","Medicham-Mega","Manectric-Mega","Sharpedo-Mega","Camerupt-Mega","Altaria-Mega","Banette-Mega","Absol-Mega","Glalie-Mega","Salamence-Mega","Metagross-Mega","Latias-Mega","Latios-Mega","Lopunny-Mega","Garchomp-Mega","Lucario-Mega","Abomasnow-Mega","Gallade-Mega","Audino-Mega","Diancie-Mega","Milotic-Mega","Butterfree-Mega","Machamp-Mega","Kingler-Mega","Lapras-Mega","Flygon-Mega","Kingdra-Mega","Rayquaza-Mega","Kyogre-Primal","Groudon-Primal","Rattata-Alola","Raticate-Alola","Raichu-Alola","Sandshrew-Alola","Sandslash-Alola","Vulpix-Alola","Ninetales-Alola","Diglett-Alola","Dugtrio-Alola","Meowth-Alola","Persian-Alola","Geodude-Alola","Graveler-Alola","Golem-Alola","Grimer-Alola","Muk-Alola","Exeggutor-Alola","Marowak-Alola","Meowth-Galarian","Ponyta-Galarian","Rapidash-Galarian","Slowpoke-Galarian","Slowbro-Galarian","Farfetchd-Galarian","Weezing-Galarian","Mr-Mime-Galarian","Articuno-Galarian","Zapdos-Galarian","Moltres-Galarian","Slowking-Galarian","Corsola-Galarian","Zigzagoon-Galarian","Linoone-Galarian","Darumaka-Galarian","Darmanitan-Galarian","Yamask-Galarian","Stunfisk-Galarian","Pikachu-Cosplay","Pikachu-Rock-Star","Pikachu-Belle","Pikachu-Pop-Star","Pikachu-Ph-D","Pikachu-Libre","Pikachu-Original-Cap","Pikachu-Hoenn-Cap","Pikachu-Sinnoh-Cap","Pikachu-Unova-Cap","Pikachu-Kalos-Cap","Pikachu-Alola-Cap","Pikachu-Partner-Cap","Pikachu-World-Cap","Pichu-Spiky-Eared","Unown-B","Unown-C","Unown-D","Unown-E","Unown-F","Unown-G","Unown-H","Unown-I","Unown-J","Unown-K","Unown-L","Unown-M","Unown-N","Unown-O","Unown-P","Unown-Q","Unown-R","Unown-S","Unown-T","Unown-U","Unown-V","Unown-W","Unown-X","Unown-Y","Unown-Z","Unown-Emark","Unown-Qmark","Castform-Sunny","Castform-Rainy","Castform-Snowy","Deoxys-Attack","Deoxys-Defense","Deoxys-Speed","Burmy-Sandy-Cloak","Burmy-Trash-Cloak","Wormadam-Sandy","Wormadam-Trash","Cherrim-Sunshine","Shellos-East-Sea","Gastrodon","Rotom-Heat","Rotom-Wash","Rotom-Frost","Rotom-Fan","Rotom-Mow","Giratina-Origin","Shaymin-Sky","Arceus-Fighting","Arceus-Flying","Arceus-Poison","Arceus-Ground","Arceus-Rock","Arceus-Bug","Arceus-Ghost","Arceus-Steel","Arceus-Fire","Arceus-Water","Arceus-Grass","Arceus-Electric","Arceus-Psychic","Arceus-Ice","Arceus-Dragon","Arceus-Dark","Arceus-Fairy","Basculin-Blue-Striped","Darmanitan-Zen-Mode","Darmanitan-Zen-Mode-Galarian","Deerling-Summer","Deerling-Autumn","Deerling-Winter","Sawsbuck-Summer","Sawsbuck-Autumn","Sawsbuck-Winter","Tornadus-Therian","Thundurus-Therian","Landorus-Therian","Kyurem-White","Kyurem-Black","Keldeo-Resolute","Meloetta-Pirouette","Genesect-Douse-Drive","Genesect-Shock-Drive","Genesect-Burn-Drive","Genesect-Chill-Drive","Greninja-Battle-Bond","Greninja-Ash","Vivillon-Polar","Vivillon-Tundra","Vivillon-Continental","Vivillon-Garden","Vivillon-Elegant","Vivillon-Meadow","Vivillon-Modern","Vivillon-Marine","Vivillon-Archipelago","Vivillon-High-Plains","Vivillon-Sandstorm","Vivillon-River","Vivillon-Monsoon","Vivillon-Savanna","Vivillon-Sun","Vivillon-Ocean","Vivillon-Jungle","Vivillon-Fancy","Vivillon-Poke-Ball","Flabebe-Yellow-Flower","Flabebe-Orange-Flower","Flabebe-Blue-Flower","Flabebe-White-Flower","Floette-Yellow-Flower","Floette-Orange-Flower","Floette-Blue-Flower","Floette-White-Flower","Floette-Eternal-Flower","Florges-Yellow-Flower","Florges-Orange-Flower","Florges-Blue-Flower","Florges-White-Flower","Furfrou-Heart-Trim","Furfrou-Star-Trim","Furfrou-Diamond-Trim","Furfrou-Debutante-Trim","Furfrou-Matron-Trim","Furfrou-Dandy-Trim","Furfrou-La-Reine-Trim","Furfrou-Kabuki-Trim","Furfrou-Pharaoh-Trim","Meowstic-F","Aegislash-Blade","Pumpkaboo-Small","Pumpkaboo-Large","Pumpkaboo-Super","Gourgeist-Small","Gourgeist-Large","Gourgeist-Super","Xerneas-Active","Zygarde-10","Zygarde-10-Power-Construct","Zygarde-50-Power-Construct","Zygarde-Complete","Hoopa-Unbound","Oricorio-Pom-Pom","Oricorio-Pau","Oricorio-Sensu","Rockruff-Own-Tempo","Lycanroc-Midnight","Lycanroc-Dusk","Wishiwashi-School","Silvally-Fighting","Silvally-Flying","Silvally-Poison","Silvally-Ground","Silvally-Rock","Silvally-Bug","Silvally-Ghost","Silvally-Steel","Silvally-Fire","Silvally-Water","Silvally-Grass","Silvally-Electric","Silvally-Psychic","Silvally-Ice","Silvally-Dragon","Silvally-Dark","Silvally-Fairy","Minior-Meteor-Orange","Minior-Meteor-Yellow","Minior-Meteor-Green","Minior-Meteor-Blue","Minior-Meteor-Indigo","Minior-Meteor-Violet","Minior-Core-Red","Minior-Core-Orange","Minior-Core-Yellow","Minior-Core-Green","Minior-Core-Blue","Minior-Core-Indigo","Minior-Core-Violet","Mimikyu-Busted","Necrozma-Dusk-Mane","Necrozma-Dawn-Wings","Necrozma-Ultra","Magearna-Original-Color","Cramorant-Gulping","Cramorant-Gorging","Toxtricity-Low-Key","Sinistea-Antique","Polteageist-Antique","Alcremie-Ruby-Cream","Alcremie-Matcha-Cream","Alcremie-Mint-Cream","Alcremie-Lemon-Cream","Alcremie-Salted-Cream","Alcremie-Ruby-Swirl","Alcremie-Caramel-Swirl","Alcremie-Rainbow-Swirl","Eiscue-Noice-Face","Indeedee-Female","Morpeko-Hangry","Zacian-Crowned-Sword","Zamazenta-Crowned-Shield","Eternatus-Eternamax","Urshifu-Rapid-Strike-Style","Zarude-Dada","Calyrex-Ice","Calyrex-Shadow"]
inc_em_moves = ["None","Pound","Karate Chop","Double Slap","Comet Punch","Mega Punch","Pay Day","Fire Punch","Ice Punch","Thunder Punch","Scratch","Vise Grip","Guillotine","Razor Wind","Swords Dance","Cut","Gust","Wing Attack","Whirlwind","Fly","Bind","Slam","Vine Whip","Stomp","Double Kick","Mega Kick","Jump Kick","Rolling Kick","Sand-Attack","Headbutt","Horn Attack","Fury Attack","Horn Drill","Tackle","Body Slam","Wrap","Take Down","Thrash","Double-Edge","Tail Whip","Poison Sting","Twineedle","Pin Missile","Leer","Bite","Growl","Roar","Sing","Supersonic","Sonic Boom","Disable","Acid","Ember","Flamethrower","Mist","Water Gun","Hydro Pump","Surf","Ice Beam","Blizzard","Psybeam","Bubble Beam","Aurora Beam","Hyper Beam","Peck","Drill Peck","Submission","Low Kick","Counter","Seismic Toss","Strength","Absorb","Mega Drain","Leech Seed","Growth","Razor Leaf","Solar Beam","Poison Powder","Stun Spore","Sleep Powder","Petal Dance","String Shot","Dragon Rage","Fire Spin","Thunder Shock","Thunderbolt","Thunder Wave","Thunder","Rock Throw","Earthquake","Fissure","Dig","Toxic","Confusion","Psychic","Hypnosis","Meditate","Agility","Quick Attack","Rage","Teleport","Night Shade","Mimic","Screech","Double Team","Recover","Harden","Minimize","Smokescreen","Confuse Ray","Withdraw","Defense Curl","Barrier","Light Screen","Haze","Reflect","Focus Energy","Bide","Metronome","Mirror Move","Self Destruct","Egg Bomb","Lick","Smog","Sludge","Bone Club","Fire Blast","Waterfall","Clamp","Swift","Skull Bash","Spike Cannon","Constrict","Amnesia","Kinesis","Soft Boiled","High Jump Kick","Glare","Dream Eater","Poison Gas","Barrage","Leech Life","Lovely Kiss","Sky Attack","Transform","Bubble","Dizzy Punch","Spore","Flash","Psywave","Splash","Acid Armor","Crabhammer","Explosion","Fury Swipes","Bonemerang","Rest","Rock Slide","Hyper Fang","Sharpen","Conversion","Tri Attack","Super Fang","Slash","Substitute","Struggle","Sketch","Triple Kick","Thief","Spider Web","Mind Reader","Nightmare","Flame Wheel","Snore","Curse","Flail","Conversion 2","Aeroblast","Cotton Spore","Reversal","Spite","Powder Snow","Protect","Mach Punch","Scary Face","Feint Attack","Sweet Kiss","Belly Drum","Sludge Bomb","Mud-Slap","Octazooka","Spikes","Zap Cannon","Foresight","Destiny Bond","Perish Song","Icy Wind","Detect","Bone Rush","Lock On","Outrage","Sandstorm","Giga Drain","Endure","Charm","Rollout","False Swipe","Swagger","Milk Drink","Spark","Fury Cutter","Steel Wing","Mean Look","Attract","Sleep Talk","Heal Bell","Return","Present","Frustration","Safeguard","Pain Split","Sacred Fire","Magnitude","Dynamic Punch","Megahorn","Dragon Breath","Baton Pass","Encore","Pursuit","Rapid Spin","Sweet Scent","Iron Tail","Metal Claw","Vital Throw","Morning Sun","Synthesis","Moonlight","Hidden Power","Cross Chop","Twister","Rain Dance","Sunny Day","Crunch","Mirror Coat","Psych Up","Extreme Speed","Ancient Power","Shadow Ball","Future Sight","Rock Smash","Whirlpool","Beat Up","Fake Out","Uproar","Stockpile","Spit Up","Swallow","Heat Wave","Hail","Torment","Flatter","Will-O-Wisp","Memento","Facade","Focus Punch","Smelling Salts","Follow Me","Nature Power","Charge","Taunt","Helping Hand","Trick","Role Play","Wish","Assist","Ingrain","Superpower","Magic Coat","Recycle","Revenge","Brick Break","Yawn","Knock Off","Endeavor","Eruption","Skill Swap","Imprison","Refresh","Grudge","Snatch","Secret Power","Dive","Arm Thrust","Camouflage","Tail Glow","Luster Purge","Mist Ball","Feather Dance","Teeter Dance","Blaze Kick","Mud Sport","Ice Ball","Needle Arm","Slack Off","Hyper Voice","Poison Fang","Crush Claw","Blast Burn","Hydro Cannon","Meteor Mash","Astonish","Weather Ball","Aromatherapy","Fake Tears","Air Cutter","Overheat","Odor Sleuth","Rock Tomb","Silver Wind","Metal Sound","Grass Whistle","Tickle","Cosmic Power","Water Spout","Signal Beam","Shadow Punch","Extrasensory","Sky Uppercut","Sand Tomb","Sheer Cold","Muddy Water","Bullet Seed","Aerial Ace","Icicle Spear","Iron Defense","Block","Howl","Dragon Claw","Frenzy Plant","Bulk Up","Bounce","Mud Shot","Poison Tail","Covet","Volt Tackle","Magical Leaf","Water Sport","Calm Mind","Leaf Blade","Dragon Dance","Rock Blast","Shock Wave","Water Pulse","Doom Desire","Psycho Boost","Roost","Gravity","Miracle Eye","Wake-Up Slap","Hammer Arm","Gyro Ball","Healing Wish","Brine","Natural Gift","Feint","Pluck","Tailwind","Acupressure","Metal Burst","U-turn","Close Combat","Payback","Assurance","Embargo","Fling","Psycho Shift","Trump Card","Heal Block","Wring Out","Power Trick","Gastro Acid","Lucky Chant","Me First","Copycat","Power Swap","Guard Swap","Punishment","Last Resort","Worry Seed","Sucker Punch","Toxic Spikes","Heart Swap","Aqua Ring","Magnet Rise","Flare Blitz","Force Palm","Aura Sphere","Rock Polish","Poison Jab","Dark Pulse","Night Slash","Aqua Tail","Seed Bomb","Air Slash","X-Scissor","Bug Buzz","Dragon Pulse","Dragon Rush","Power Gem","Drain Punch","Vacuum Wave","Focus Blast","Energy Ball","Brave Bird","Earth Power","Switcheroo","Giga Impact","Nasty Plot","Bullet Punch","Avalanche","Ice Shard","Shadow Claw","Thunder Fang","Ice Fang","Fire Fang","Shadow Sneak","Mud Bomb","Psycho Cut","Zen Headbutt","Mirror Shot","Flash Cannon","Rock Climb","Defog","Trick Room","Draco Meteor","Discharge","Lava Plume","Leaf Storm","Power Whip","Rock Wrecker","Cross Poison","Gunk Shot","Iron Head","Magnet Bomb","Stone Edge","Captivate","Stealth Rock","Grass Knot","Chatter","Judgment","Bug Bite","Charge Beam","Wood Hammer","Aqua Jet","Attack Order","Defend Order","Heal Order","Head Smash","Double Hit","Roar Of Time","Spacial Rend","Lunar Dance","Crush Grip","Magma Storm","Dark Void","Seed Flare","Ominous Wind","Shadow Force","Hone Claws","Wide Guard","Guard Split","Power Split","Wonder Room","Psyshock","Venoshock","Autotomize","Rage Powder","Telekinesis","Magic Room","Smack Down","Storm Throw","Flame Burst","Sludge Wave","Quiver Dance","Heavy Slam","Synchronoise","Electro Ball","Soak","Flame Charge","Coil","Low Sweep","Acid Spray","Foul Play","Simple Beam","Entrainment","After You","Round","Echoed Voice","Chip Away","Clear Smog","Stored Power","Quick Guard","Ally Switch","Scald","Shell Smash","Heal Pulse","Hex","Sky Drop","Shift Gear","Circle Throw","Incinerate","Quash","Acrobatics","Reflect Type","Retaliate","Final Gambit","Bestow","Inferno","Water Pledge","Fire Pledge","Grass Pledge","Volt Switch","Struggle Bug","Bulldoze","Frost Breath","Dragon Tail","Work Up","Electroweb","Wild Charge","Drill Run","Dual Chop","Heart Stamp","Horn Leech","Sacred Sword","Razor Shell","Heat Crash","Leaf Tornado","Steamroller","Cotton Guard","Night Daze","Psystrike","Tail Slap","Hurricane","Head Charge","Gear Grind","Searing Shot","Techno Blast","Relic Song","Secret Sword","Glaciate","Bolt Strike","Blue Flare","Fiery Dance","Freeze Shock","Ice Burn","Snarl","Icicle Crash","V-create","Fusion Flare","Fusion Bolt","Flying Press","Mat Block","Belch","Rototiller","Sticky Web","Fell Stinger","Phantom Force","Trick-or-Treat","Noble Roar","Ion Deluge","Parabolic Charge","Forests Curse","Petal Blizzard","Freeze-Dry","Disarming Voice","Parting Shot","Topsy-Turvy","Draining Kiss","Crafty Shield","Flower Shield","Grassy Terrain","Misty Terrain","Electrify","Play Rough","Fairy Wind","Moonblast","Boomburst","Fairy Lock","Kings Shield","Play Nice","Confide","Diamond Storm","Steam Eruption","Hyperspace Hole","Water Shuriken","Mystical Fire","Spiky Shield","Aromatic Mist","Eerie Impulse","Venom Drench","Powder","Geomancy","Magnetic Flux","Happy Hour","Electric Terrain","Dazzling Gleam","Celebrate","Hold Hands","Baby-Doll Eyes","Nuzzle","Hold Back","Infestation","Power-Up Punch","Oblivion Wing","Thousand Arrows","Thousand Waves","Lands Wrath","Light Of Ruin","Origin Pulse","Precipice Blades","Dragon Ascent","Hyperspace Fury","Shore Up","First Impression","Baneful Bunker","Spirit Shackle","Darkest Lariat","Sparkling Aria","Ice Hammer","Floral Healing","High Horsepower","Strength Sap","Solar Blade","Leafage","Spotlight","Toxic Thread","Laser Focus","Gear Up","Throat Chop","Pollen Puff","Anchor Shot","Psychic Terrain","Lunge","Fire Lash","Power Trip","Burn Up","Speed Swap","Smart Strike","Purify","Revelation Dance","Core Enforcer","Trop Kick","Instruct","Beak Blast","Clanging Scales","Dragon Hammer","Brutal Swing","Aurora Veil","Shell Trap","Fleur Cannon","Psychic Fangs","Stomping Tantrum","Shadow Bone","Accelerock","Liquidation","Prismatic Laser","Spectral Thief","Sunsteel Strike","Moongeist Beam","Tearful Look","Zing Zap","Natures Madness","Multi-Attack","Mind Blown","Plasma Fists","Photon Geyser","Zippy Zap","Splishy Splash","Floaty Fall","Pika Papow","Bouncy Bubble","Buzzy Buzz","Sizzly Slide","Glitzy Glow","Baddy Bad","Sappy Seed","Freezy Frost","Sparkly Swirl","Veevee Volley","Double Iron Bash","Dynamax Cannon","Snipe Shot","Jaw Lock","Stuff Cheeks","No Retreat","Tar Shot","Magic Powder","Dragon Darts","Teatime","Octolock","Bolt Beak","Fishious Rend","Court Change","Clangorous Soul","Body Press","Decorate","Drum Beating","Snap Trap","Pyro Ball","Behemoth Blade","Behemoth Bash","Aura Wheel","Breaking Swipe","Branch Poke","Overdrive","Apple Acid","Grav Apple","Spirit Break","Strange Steam","Life Dew","Obstruct","False Surrender","Meteor Assault","Eternabeam","Steel Beam","Expanding Force","Steel Roller","Scale Shot","Meteor Beam","Shell Side Arm","Misty Explosion","Grassy Glide","Rising Voltage","Terrain Pulse","Skitter Smack","Burning Jealousy","Lash Out","Poltergeist","Corrosive Gas","Coaching","Flip Turn","Triple Axel","Dual Wingbeat","Scorching Sands","Jungle Healing","Wicked Blow","Surging Strikes","Thunder Cage","Dragon Energy","Freezing Glare","Fiery Wrath","Thunderous Kick","Glacial Lance","Astral Barrage","Eerie Spell"]

locations = {}

locations["Pt"] = ["Mystery Zone","Twinleaf Town","Sandgem Town","Floaroma Town","Solaceon Town","Celestic Town","Jubilife City","Canalave City","Oreburgh City","Eterna City","Hearthome City","Pastoria City","Veilstone City","Sunyshore City","Snowpoint City","Pokémon League","Route 201","Route 202","Route 203","Route 204","Route 205","Route 206","Route 207","Route 208","Route 209","Route 210","Route 211","Route 212","Route 213","Route 214","Route 215","Route 216","Route 217","Route 218","Route 219","Route 220","Route 221","Route 222","Route 223","Route 224","Route 225","Route 226","Route 227","Route 228","Route 229","Route 230","Oreburgh Mine","Valley Windworks","Eterna Forest","Fuego Ironworks","Mt. Coronet","Spear Pillar","Great Marsh","Solaceon Ruins","Victory Road","Pal Park","Amity Square","Ravaged Path","Floaroma Meadow","Oreburgh Gate","Fullmoon Island","Sendoff Spring","Turnback Cave","Flower Paradise","Snowpoint Temple","Wayward Cave","Ruin Maniac Cave","Maniac Tunnel","Trophy Garden","Iron Island","Old Chateau","Galactic HQ","Verity Lakefront","Valor Lakefront","Acuity Lakefront","Spring Path","Lake Verity","Lake Valor","Lake Acuity","Newmoon Island","Battle Tower","Fight Area","Survival Area","Resort Area","Stark Mountain","Seabreak Path","Hall of Origin","Verity Cavern","Valor Cavern","Acuity Cavern","Jubilife TV","Pokétch Co.","GTS","Trainers’ School","Mining Museum","Flower Shop","Cycle Shop","Contest Hall","Poffin House","Foreign Building","Pokémon Day Care","Veilstone Store","Game Corner","Canalave Library","Vista Lighthouse","Sunyshore Market","Pokémon Mansion","Footstep House","Café","Grand Lake","Restaurant","Battle Park","Battle Frontier","Battle Factory","Battle Castle","Battle Arcade","Battle Hall","Distortion World","Global Terminal","Villa","Battleground","ROTOM’s Room","T.G. Eterna Bldg","Iron Ruins","Iceberg Ruins","Rock Peak Ruins","New Bark Town","Cherrygrove City","Violet City","Azalea Town","Cianwood City","Goldenrod City","Olivine City","Ecruteak City","Mahogany Town","Lake of Rage","Blackthorn City","Mt. Silver","Pallet Town","Viridian City","Pewter City","Cerulean City","Lavender Town","Vermilion City","Celadon City","Fuchsia City","Cinnabar Island","Indigo Plateau","Saffron City","Route 1","Route 2","Route 3","Route 4","Route 5","Route 6","Route 7","Route 8","Route 9","Route 10","Route 11","Route 12","Route 13","Route 14","Route 15","Route 16","Route 17","Route 18","Route 19","Route 20","Route 21","Route 22","Route 23","Route 24","Route 25","Route 26","Route 27","Route 28","Route 29","Route 30","Route 31","Route 32","Route 33","Route 34","Route 35","Route 36","Route 37","Route 38","Route 39","Route 40","Route 41","Route 42","Route 43","Route 44","Route 45","Route 46","Route 47","Route 48","DIGLETT’s Cave","Mt. Moon","Cerulean Cave","Rock Tunnel","Power Plant","Safari Zone","Seafoam Islands","Sprout Tower","Bell Tower","Burned Tower","National Park","Radio Tower","Ruins of Alph","Union Cave","SLOWPOKE Well","Lighthouse","Team Rocket HQ","Ilex Forest","Goldenrod Tunnel","Mt. Mortar","Ice Path","Whirl Islands","Mt. Silver Cave","Dark Cave","Victory Road","Dragon’s Den","Tohjo Falls","Viridian Forest","Pokéathlon Dome","S.S. Aqua","Safari Zone Gate","Cliff Cave","Frontier Access","Bellchime Trail","Sinjoh Ruins","Embedded Tower","Pokéwalker","Cliff Edge Gate"]
locations["HGSS"] = locations["Pt"]
locations["BW2"] = ["Unknown","Mystery Zone","Faraway place","VAR(256, 0)s VAR(261, 1)","Nuvema Town","Accumula Town","Striaton City","Nacrene City","Castelia City","Nimbasa City","Driftveil City","Mistralton City","Icirrus City","Opelucid City","Route 1","Route 2","Route 3","Route 4","Route 5","Route 6","Route 7","Route 8","Route 9","Route 10","Route 11","Route 12","Route 13","Route 14","Route 15","Route 16","Route 17","Route 18","Dreamyard","Pinwheel Forest","Desert Resort","Relic Castle","PWT","Chargestone Cave","Twist Mountain","Dragonspiral Tower","Victory Road","Lacunosa Town","Undella Town","Anville Town","Pokemon League","N's Castle","Royal Unova","Gear Station","Battle Subway","Musical Theater","Black City","White Forest","Unity Tower","Wellspring Cave","Mistralton Cave","Rumination Field","Celestial Tower","Moor of Icirrus","Castelia Gardens","Challenger's Cave","Poke Transfer Lab","Giant Chasm","Liberty Garden","P2 Laboratory","Skyarrow Bridge","Driftveil Drawbridge","Tubeline Bridge","Village Bridge","Marvelous Bridge","Entralink","Abundant Shrine","Undella Bay","Lostlorn Forest","Trial Chamber","Mistralton Cave","Entree Forest","Nimbasa City","Driftveil City","Mistralton City","Icirrus City","Opelucid City","Nuvema Town","White Forest","Black City","Cold Storage","Chargestone Cave","Twist Mountain","Dragonspiral Tower","Giant Chasm","Driftveil Drawbridge","Tubeline Bridge","Village Bridge","Marvelous Bridge","Route 5","Route 6","Route 7","Route 8","Route 9","Route 11","Route 12","Route 13","Route 14","Route 15","Route 16","Lacunosa Town","Undella Town","Accumula Gate","Undella Gate","Nacrene Gate","Castelia Gate","Nimbasa Gate","Opelucid Gate","Black Gate","White Gate","Bridge Gate","Route Gate","Abyssal Ruins","Aspertia City","Virbank City","Humilau City","Pokestar Studios","Join Avenue","Floccesy Town","Lentimas Town","Route 19","Route 20","Route 21","Route 22","Route 23","Castelia Sewers","Floccesy Ranch","Virbank Complex","Reversal Mountain","Strange House","Victory Road","Plasma Frigate","Relic Passage","Clay Tunnel","Unknown","White Treehollow","Black Tower","Seaside Cave","Cave of Being","Hidden Grotto","Marine Tube","Virbank Gate","Aspertia Gate","Nature Preserve","Medal Office","Underground Ruins","Rock Peak Chamber","Iceberg Chamber","Iron Chamber","Pledge Grove","Inner Complex","Faraway Island"]
locations["BW"] = locations["BW2"]
locations["EM"] = ["LITTLEROOT TOWN","OLDALE TOWN","DEWFORD TOWN","LAVARIDGE TOWN","FALLARBOR TOWN","VERDANTURF TOWN","PACIFIDLOG TOWN","PETALBURG CITY","SLATEPORT CITY","MAUVILLE CITY","RUSTBORO CITY","FORTREE CITY","LILYCOVE CITY","MOSSDEEP CITY","SOOTOPOLIS CITY","EVER GRANDE CITY","ROUTE 101","ROUTE 102","ROUTE 103","ROUTE 104","ROUTE 105","ROUTE 106","ROUTE 107","ROUTE 108","ROUTE 109","ROUTE 110","ROUTE 111","ROUTE 112","ROUTE 113","ROUTE 114","ROUTE 115","ROUTE 116","ROUTE 117","ROUTE 118","ROUTE 119","ROUTE 120","ROUTE 121","ROUTE 122","ROUTE 123","ROUTE 124","ROUTE 125","ROUTE 126","ROUTE 127","ROUTE 128","ROUTE 129","ROUTE 130","ROUTE 131","ROUTE 132","ROUTE 133","ROUTE 134","UNDERWATER","UNDERWATER","UNDERWATER","UNDERWATER","UNDERWATER","GRANITE CAVE","MT. CHIMNEY","SAFARI ZONE","BATTLE FRONTIER","PETALBURG WOODS","RUSTURF TUNNEL","ABANDONED SHIP","NEW MAUVILLE","METEOR FALLS","METEOR FALLS","MT. PYRE","{AQUA} HIDEOUT","SHOAL CAVE","SEAFLOOR CAVERN","UNDERWATER","VICTORY ROAD","MIRAGE ISLAND","CAVE OF ORIGIN","SOUTHERN ISLAND","FIERY PATH","FIERY PATH","JAGGED PASS","JAGGED PASS","SEALED CHAMBER","UNDERWATER","SCORCHED SLAB","ISLAND CAVE","DESERT RUINS","ANCIENT TOMB","INSIDE OF TRUCK","SKY PILLAR","SECRET BASE","","PALLET TOWN","VIRIDIAN CITY","PEWTER CITY","CERULEAN CITY","LAVENDER TOWN","VERMILION CITY","CELADON CITY","FUCHSIA CITY","CINNABAR ISLAND","INDIGO PLATEAU","SAFFRON CITY","ROUTE 4","ROUTE 10","ROUTE 1","ROUTE 2","ROUTE 3","ROUTE 4","ROUTE 5","ROUTE 6","ROUTE 7","ROUTE 8","ROUTE 9","ROUTE 10","ROUTE 11","ROUTE 12","ROUTE 13","ROUTE 14","ROUTE 15","ROUTE 16","ROUTE 17","ROUTE 18","ROUTE 19","ROUTE 20","ROUTE 21","ROUTE 22","ROUTE 23","ROUTE 24","ROUTE 25","VIRIDIAN FOREST","MT. MOON","S.S. ANNE","UNDERGROUND PATH","UNDERGROUND PATH","DIGLETT'S CAVE","VICTORY ROAD","ROCKET HIDEOUT","SILPH CO.","POKéMON MANSION","SAFARI ZONE","POKéMON LEAGUE","ROCK TUNNEL","SEAFOAM ISLANDS","POKéMON TOWER","CERULEAN CAVE","POWER PLANT","ONE ISLAND","TWO ISLAND","THREE ISLAND","FOUR ISLAND","FIVE ISLAND","SEVEN ISLAND","SIX ISLAND","KINDLE ROAD","TREASURE BEACH","CAPE BRINK","BOND BRIDGE","THREE ISLE PORT","SEVII ISLE 6","SEVII ISLE 7","SEVII ISLE 8","SEVII ISLE 9","RESORT GORGEOUS","WATER LABYRINTH","FIVE ISLE MEADOW","MEMORIAL PILLAR","OUTCAST ISLAND","GREEN PATH","WATER PATH","RUIN VALLEY","TRAINER TOWER","CANYON ENTRANCE","SEVAULT CANYON","TANOBY RUINS","SEVII ISLE 22","SEVII ISLE 23","SEVII ISLE 24","NAVEL ROCK","MT. EMBER","BERRY FOREST","ICEFALL CAVE","ROCKET WAREHOUSE","TRAINER TOWER","DOTTED HOLE","LOST CAVE","PATTERN BUSH","ALTERING CAVE","TANOBY CHAMBERS","THREE ISLE PATH","TANOBY KEY","BIRTH ISLAND","MONEAN CHAMBER","LIPTOO CHAMBER","WEEPTH CHAMBER","DILFORD CHAMBER","SCUFIB CHAMBER","RIXY CHAMBER","VIAPOIS CHAMBER","EMBER SPA","SPECIAL AREA","AQUA HIDEOUT","MAGMA HIDEOUT","MIRAGE TOWER","BIRTH ISLAND","FARAWAY ISLAND","ARTISAN CAVE","MARINE CAVE","UNDERWATER","TERRA CAVE","UNDERWATER","UNDERWATER","UNDERWATER","DESERT UNDERPASS","ALTERING CAVE","NAVEL ROCK","TRAINER HILL","FLOATING SLAB","ROCKY SLAB","GRASSY SLAB"]

allTypes = ["None", "Normal", "Fighting", "Flying", "Poison", "Ground", "Rock", "Bug", "Ghost", "Steel", "Mystery", "Fire", "Water","Grass","Electric","Psychic","Ice","Dragon","Dark", "Fairy", "Stellar"]




natMods = {
  Hardy: { plus: 'atk', minus: 'atk' },
  Lonely: { plus: 'atk', minus: 'def' },
  Brave: { plus: 'atk', minus: 'spe' },
  Adamant: { plus: 'atk', minus: 'spa' },
  Naughty: { plus: 'atk', minus: 'spd' },
  Bold: { plus: 'def', minus: 'atk' },
  Docile: { plus: 'atk', minus: 'atk' },
  Relaxed: { plus: 'def', minus: 'spe' },
  Impish: { plus: 'def', minus: 'spa' },
  Lax: { plus: 'def', minus: 'spd' },
  Timid: { plus: 'spe', minus: 'atk' },
  Hasty: { plus: 'spe', minus: 'def' },
  Serious: { plus: 'atk', minus: 'atk' },
  Jolly: { plus: 'spe', minus: 'spa' },
  Naive: { plus: 'spe', minus: 'spd' },
  Modest: { plus: 'spa', minus: 'atk' },
  Mild: { plus: 'spa', minus: 'def' },
  Quiet: { plus: 'spa', minus: 'spe' },
  Bashful: { plus: 'atk', minus: 'atk' },
  Rash: { plus: 'spa', minus: 'spd' },
  Calm: { plus: 'spd', minus: 'atk' },
  Gentle: { plus: 'spd', minus: 'def' },
  Sassy: { plus: 'spd', minus: 'spe' },
  Careful: { plus: 'spd', minus: 'spa' },
  Quirky: { plus: 'atk', minus: 'atk' }
};

natures = ["Hardy",
        "Lonely",
        "Brave",
        "Adamant",
        "Naughty",
        "Bold",
        "Docile",
        "Relaxed",
        "Impish",
        "Lax",
        "Timid",
        "Hasty",
        "Serious",
        "Jolly",
        "Naive",
        "Modest",
        "Mild",
        "Quiet",
        "Bashful",
        "Rash",
        "Calm",
        "Gentle",
        "Sassy",
        "Careful",
        "Quirky"]

blockOrders = [
    [0, 1, 2, 3],
    [0, 1, 3, 2],
    [0, 2, 1, 3],
    [0, 2, 3, 1],
    [0, 3, 1, 2],
    [0, 3, 2, 1],
    [1, 0, 2, 3],
    [1, 0, 3, 2],
    [1, 2, 0, 3],
    [1, 2, 3, 0],
    [1, 3, 0, 2],
    [1, 3, 2, 0],
    [2, 0, 1, 3],
    [2, 0, 3, 1],
    [2, 1, 0, 3],
    [2, 1, 3, 0],
    [2, 3, 0, 1],
    [2, 3, 1, 0],
    [3, 0, 1, 2],
    [3, 0, 2, 1],
    [3, 1, 0, 2],
    [3, 1, 2, 0],
    [3, 2, 0, 1],
    [3, 2, 1, 0],

    // duplicates of 0-7 to eliminate modulus
    [0, 1, 2, 3],
    [0, 1, 3, 2],
    [0, 2, 1, 3],
    [0, 3, 1, 2],
    [0, 2, 3, 1],
    [0, 3, 2, 1],
    [1, 0, 2, 3],
    [1, 0, 3, 2]
];

expTables = [[
        0, 8, 27, 64, 125, 216, 343, 512, 729, 1000,
        1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859, 8000,
        9261, 10648, 12167, 13824, 15625, 17576, 19683, 21952, 24389, 27000,
        29791, 32768, 35937, 39304, 42875, 46656, 50653, 54872, 59319, 64000,
        68921, 74088, 79507, 85184, 91125, 97336, 103823, 110592, 117649, 125000,
        132651, 140608, 148877, 157464, 166375, 175616, 185193, 195112, 205379, 216000,
        226981, 238328, 250047, 262144, 274625, 287496, 300763, 314432, 328509, 343000,
        357911, 373248, 389017, 405224, 421875, 438976, 456533, 474552, 493039, 512000,
        531441, 551368, 571787, 592704, 614125, 636056, 658503, 681472, 704969, 729000,
        753571, 778688, 804357, 830584, 857375, 884736, 912673, 941192, 970299, 1000000
    ],
    [
        0, 15, 52, 122, 237, 406, 637, 942, 1326, 1800,
        2369, 3041, 3822, 4719, 5737, 6881, 8155, 9564, 11111, 12800,
        14632, 16610, 18737, 21012, 23437, 26012, 28737, 31610, 34632, 37800,
        41111, 44564, 48155, 51881, 55737, 59719, 63822, 68041, 72369, 76800,
        81326, 85942, 90637, 95406, 100237, 105122, 110052, 115015, 120001, 125000,
        131324, 137795, 144410, 151165, 158056, 165079, 172229, 179503, 186894, 194400,
        202013, 209728, 217540, 225443, 233431, 241496, 249633, 257834, 267406, 276458,
        286328, 296358, 305767, 316074, 326531, 336255, 346965, 357812, 367807, 378880,
        390077, 400293, 411686, 423190, 433572, 445239, 457001, 467489, 479378, 491346,
        501878, 513934, 526049, 536557, 548720, 560922, 571333, 583539, 591882, 600000,
    ]

    ,
    [
        0, 4, 13, 32, 65, 112, 178, 276, 393, 540,
        745, 967, 1230, 1591, 1957, 2457, 3046, 3732, 4526, 5440,
        6482, 7666, 9003, 10506, 12187, 14060, 16140, 18439, 20974, 23760,
        26811, 30146, 33780, 37731, 42017, 46656, 50653, 55969, 60505, 66560,
        71677, 78533, 84277, 91998, 98415, 107069, 114205, 123863, 131766, 142500,
        151222, 163105, 172697, 185807, 196322, 210739, 222231, 238036, 250562, 267840,
        281456, 300293, 315059, 335544, 351520, 373744, 390991, 415050, 433631, 459620,
        479600, 507617, 529063, 559209, 582187, 614566, 639146, 673863, 700115, 737280,
        765275, 804997, 834809, 877201, 908905, 954084, 987754, 1035837, 1071552, 1122660,
        1160499, 1214753, 1254796, 1312322, 1354652, 1415577, 1460276, 1524731, 1571884, 1640000,
    ]

    ,
    [
        0, 9, 57, 96, 135, 179, 236, 314, 419, 560,
        742, 973, 1261, 1612, 2035, 2535, 3120, 3798, 4575, 5460,
        6458, 7577, 8825, 10208, 11735, 13411, 15244, 17242, 19411, 21760,
        24294, 27021, 29949, 33084, 36435, 40007, 43808, 47846, 52127, 56660,
        61450, 66505, 71833, 77440, 83335, 89523, 96012, 102810, 109923, 117360,
        125126, 133229, 141677, 150476, 159635, 169159, 179056, 189334, 199999, 211060,
        222522, 234393, 246681, 259392, 272535, 286115, 300140, 314618, 329555, 344960,
        360838, 377197, 394045, 411388, 429235, 447591, 466464, 485862, 505791, 526260,
        547274, 568841, 590969, 613664, 636935, 660787, 685228, 710266, 735907, 762160,
        789030, 816525, 844653, 873420, 902835, 932903, 963632, 995030, 1027103, 1059860,
    ]

    ,
    [
        0, 6, 21, 51, 100, 172, 274, 409, 583, 800,
        1064, 1382, 1757, 2195, 2700, 3276, 3930, 4665, 5487, 6400,
        7408, 8518, 9733, 11059, 12500, 14060, 15746, 17561, 19511, 21600,
        23832, 26214, 28749, 31443, 34300, 37324, 40522, 43897, 47455, 51200,
        55136, 59270, 63605, 68147, 72900, 77868, 83058, 88473, 94119, 100000,
        106120, 112486, 119101, 125971, 133100, 140492, 148154, 156089, 164303, 172800,
        181584, 190662, 200037, 209715, 219700, 229996, 240610, 251545, 262807, 274400,
        286328, 298598, 311213, 324179, 337500, 351180, 365226, 379641, 394431, 409600,
        425152, 441094, 457429, 474163, 491300, 508844, 526802, 545177, 563975, 583200,
        602856, 622950, 643485, 664467, 685900, 707788, 730138, 752953, 776239, 800000,
    ]

    ,
    [
        0, 10, 33, 80, 156, 270, 428, 640, 911, 1250,
        1663, 2160, 2746, 3430, 4218, 5120, 6141, 7290, 8573, 10000,
        11576, 13310, 15208, 17280, 19531, 21970, 24603, 27440, 30486, 33750,
        37238, 40960, 44921, 49130, 53593, 58320, 63316, 68590, 74148, 80000,
        86151, 92610, 99383, 106480, 113906, 121670, 129778, 138240, 147061, 156250,
        165813, 175760, 186096, 196830, 207968, 219520, 231491, 243890, 256723, 270000,
        283726, 297910, 312558, 327680, 343281, 359370, 375953, 393040, 410636, 428750,
        447388, 466560, 486271, 506530, 527343, 548720, 570666, 593190, 616298, 640000,
        664301, 689210, 714733, 740880, 767656, 795070, 823128, 851840, 881211, 911250,
        941963, 973360, 1005446, 1038230, 1071718, 1105920, 1140841, 1176490, 1212873, 1250000,
]];


function get_level(table, exp) {
    if (exp == table[99]) {
    	return 100
    }

    let left = 0;
    let right = table.length - 1;
    
    while (left <= right) {
        const mid = Math.floor((left + right) / 2);
        
        if (table[mid] <= exp) {
            left = mid + 1;
        } else {
            right = mid - 1;
        }
    }
    
    // After the loop, 'left' is the index of the first element >= x, or arr.length if no such element exists
    return left < table.length ? left : -1;
}



mon_forms = {}
mon_forms["Deoxys"] = ['Attack', 'Defense', 'Speed']
mon_forms["Shaymin"] = ["Sky"]
mon_forms["Giratina"] = ["Origin"]
mon_forms["Rotom"] = ["Heat", "Wash", "Frost", "Fan", "Mow"]
mon_forms["Castorm"] = ["Sunny", "Rainy", "Snowy"]
mon_forms["Basculin"] = ["Blue-Striped"]
mon_forms["Darmanitan"] = ["Zen"]
mon_forms["Meloetta"] = ["Pirouette"]
mon_forms["Kyurem"] = ["White", "Black"]
mon_forms["Keldeo"] = ["Resolute"]
mon_forms["Tornadus"] = ["Therian"]
mon_forms["Thundurus"] = ["Therian"]
mon_forms["Landorus"] = ["Therian"]
mon_forms["Wormadam"] = ["Sandy", "Trash"]
mon_forms["Genesect"] = ["Douse", "Chill", "Burn", "Shock"]
alola_mons = ["Rattata", "Raticate", "Raichu", "Sandshrew", "Sandslash", "Vulpix", "Ninetales", "Diglett", "Dugtrio", "Meowth", "Persian", "Geodude", "Graveler", "Golem", "Grimer", "Muk", "Exeggutor", "Marowak"]
alola_mons.forEach(species => {
  mon_forms[species] = mon_forms[species] || [];
  mon_forms[species].push("Alola");
});


galar_mons = ["Ponyta", "Rapidash", "Slowpoke", "Slowbro", "Farfetch’d", "Weezing", "Mr. Mime", "Articuno", "Zapdos", "Moltres", "Slowking", "Corsola", "Zigzagoon", "Linoone", "Darumaka", "Darmanitan", "Yamask", "Stunfisk"]
galar_mons.forEach(species => {
  mon_forms[species] = mon_forms[species] || [];
  mon_forms[species].push("Galar");
});


textTable = {
      0x0000: "",
      0x0001: "\\x0001",
      0x0002: "ぁ",
      0x0003: "あ",
      0x0004: "ぃ",
      0x0005: "い",
      0x0006: "ぅ",
      0x0007: "う",
      0x0008: "ぇ",
      0x0009: "え",
      0x000A: "ぉ",
      0x000B: "お",
      0x000C: "か",
      0x000D: "が",
      0x000E: "き",
      0x000F: "ぎ",
      0x0010: "く",
      0x0011: "ぐ",
      0x0012: "け",
      0x0013: "げ",
      0x0014: "こ",
      0x0015: "ご",
      0x0016: "さ",
      0x0017: "ざ",
      0x0018: "し",
      0x0019: "じ",
      0x001A: "す",
      0x001B: "ず",
      0x001C: "せ",
      0x001D: "ぜ",
      0x001E: "そ",
      0x001F: "ぞ",
      0x0020: "た",
      0x0021: "だ",
      0x0022: "ち",
      0x0023: "ぢ",
      0x0024: "っ",
      0x0025: "つ",
      0x0026: "づ",
      0x0027: "て",
      0x0028: "で",
      0x0029: "と",
      0x002A: "ど",
      0x002B: "な",
      0x002C: "に",
      0x002D: "ぬ",
      0x002E: "ね",
      0x002F: "の",
      0x0030: "は",
      0x0031: "ば",
      0x0032: "ぱ",
      0x0033: "ひ",
      0x0034: "び",
      0x0035: "ぴ",
      0x0036: "ふ",
      0x0037: "ぶ",
      0x0038: "ぷ",
      0x0039: "へ",
      0x003A: "べ",
      0x003B: "ぺ",
      0x003C: "ほ",
      0x003D: "ぼ",
      0x003E: "ぽ",
      0x003F: "ま",
      0x0040: "み",
      0x0041: "む",
      0x0042: "め",
      0x0043: "も",
      0x0044: "ゃ",
      0x0045: "や",
      0x0046: "ゅ",
      0x0047: "ゆ",
      0x0048: "ょ",
      0x0049: "よ",
      0x004A: "ら",
      0x004B: "り",
      0x004C: "る",
      0x004D: "れ",
      0x004E: "ろ",
      0x004F: "わ",
      0x0050: "を",
      0x0051: "ん",
      0x0052: "ァ",
      0x0053: "ア",
      0x0054: "ィ",
      0x0055: "イ",
      0x0056: "ゥ",
      0x0057: "ウ",
      0x0058: "ェ",
      0x0059: "エ",
      0x005A: "ォ",
      0x005B: "オ",
      0x005C: "カ",
      0x005D: "ガ",
      0x005E: "キ",
      0x005F: "ギ",
      0x0060: "ク",
      0x0061: "グ",
      0x0062: "ケ",
      0x0063: "ゲ",
      0x0064: "コ",
      0x0065: "ゴ",
      0x0066: "サ",
      0x0067: "ザ",
      0x0068: "シ",
      0x0069: "ジ",
      0x006A: "ス",
      0x006B: "ズ",
      0x006C: "セ",
      0x006D: "ゼ",
      0x006E: "ソ",
      0x006F: "ゾ",
      0x0070: "タ",
      0x0071: "ダ",
      0x0072: "チ",
      0x0073: "ヂ",
      0x0074: "ッ",
      0x0075: "ツ",
      0x0076: "ヅ",
      0x0077: "テ",
      0x0078: "デ",
      0x0079: "ト",
      0x007A: "ド",
      0x007B: "ナ",
      0x007C: "ニ",
      0x007D: "ヌ",
      0x007E: "ネ",
      0x007F: "ノ",
      0x0080: "ハ",
      0x0081: "バ",
      0x0082: "パ",
      0x0083: "ヒ",
      0x0084: "ビ",
      0x0085: "ピ",
      0x0086: "フ",
      0x0087: "ブ",
      0x0088: "プ",
      0x0089: "ヘ",
      0x008A: "ベ",
      0x008B: "ペ",
      0x008C: "ホ",
      0x008D: "ボ",
      0x008E: "ポ",
      0x008F: "マ",
      0x0090: "ミ",
      0x0091: "ム",
      0x0092: "メ",
      0x0093: "モ",
      0x0094: "ャ",
      0x0095: "ヤ",
      0x0096: "ュ",
      0x0097: "ユ",
      0x0098: "ョ",
      0x0099: "ヨ",
      0x009A: "ラ",
      0x009B: "リ",
      0x009C: "ル",
      0x009D: "レ",
      0x009E: "ロ",
      0x009F: "ワ",
      0x00A0: "ヲ",
      0x00A1: "ン",
      0x00A2: "０",
      0x00A3: "１",
      0x00A4: "２",
      0x00A5: "３",
      0x00A6: "４",
      0x00A7: "５",
      0x00A8: "６",
      0x00A9: "７",
      0x00AA: "８",
      0x00AB: "９",
      0x00AC: "Ａ",
      0x00AD: "Ｂ",
      0x00AE: "Ｃ",
      0x00AF: "Ｄ",
      0x00B0: "Ｅ",
      0x00B1: "Ｆ",
      0x00B2: "Ｇ",
      0x00B3: "Ｈ",
      0x00B4: "Ｉ",
      0x00B5: "Ｊ",
      0x00B6: "Ｋ",
      0x00B7: "Ｌ",
      0x00B8: "Ｍ",
      0x00B9: "Ｎ",
      0x00BA: "Ｏ",
      0x00BB: "Ｐ",
      0x00BC: "Ｑ",
      0x00BD: "Ｒ",
      0x00BE: "Ｓ",
      0x00BF: "Ｔ",
      0x00C0: "Ｕ",
      0x00C1: "Ｖ",
      0x00C2: "Ｗ",
      0x00C3: "Ｘ",
      0x00C4: "Ｙ",
      0x00C5: "Ｚ",
      0x00C6: "ａ",
      0x00C7: "ｂ",
      0x00C8: "ｃ",
      0x00C9: "ｄ",
      0x00CA: "ｅ",
      0x00CB: "ｆ",
      0x00CC: "ｇ",
      0x00CD: "ｈ",
      0x00CE: "ｉ",
      0x00CF: "ｊ",
      0x00D0: "ｋ",
      0x00D1: "ｌ",
      0x00D2: "ｍ",
      0x00D3: "ｎ",
      0x00D4: "ｏ",
      0x00D5: "ｐ",
      0x00D6: "ｑ",
      0x00D7: "ｒ",
      0x00D8: "ｓ",
      0x00D9: "ｔ",
      0x00DA: "ｕ",
      0x00DB: "ｖ",
      0x00DC: "ｗ",
      0x00DD: "ｘ",
      0x00DE: "ｙ",
      0x00DF: "ｚ",
      0x00E1: "！",
      0x00E2: "？",
      0x00E3: "、",
      0x00E4: "。",
      0x00E5: "⋯",
      0x00E6: "・",
      0x00E7: "／",
      0x00E8: "「",
      0x00E9: "」",
      0x00EA: "『",
      0x00EB: "』",
      0x00EC: "（",
      0x00ED: "）",
      0x00EE: "㊚",
      0x00EF: "㊛",
      0x00F0: "＋",
      0x00F1: "－",
      0x00F2: "⊗",
      0x00F3: "⊘",
      0x00F4: "＝",
      0x00F5: "ｚ",
      0x00F6: "：",
      0x00F7: "；",
      0x00F8: "．",
      0x00F9: "，",
      0x00FA: "♤",
      0x00FB: "♧",
      0x00FC: "♡",
      0x00FD: "♢",
      0x00FE: "☆",
      0x00FF: "◎",
      0x0100: "○",
      0x0101: "□",
      0x0102: "△",
      0x0103: "◇",
      0x0104: "＠",
      0x0105: "♫",
      0x0106: "％",
      0x0107: "☼",
      0x0108: "☔",
      0x0109: "☰",
      0x010A: "❄",
      0x010B: "☋",
      0x010C: "♔",
      0x010D: "♕",
      0x010E: "☊",
      0x010F: "⇗",
      0x0110: "⇘",
      0x0111: "☾",
      0x0112: "¥",
      0x0113: "♈",
      0x0114: "♉",
      0x0115: "♊",
      0x0116: "♋",
      0x0117: "♌",
      0x0118: "♍",
      0x0119: "♎",
      0x011A: "♏",
      0x011B: "←",
      0x011C: "↑",
      0x011D: "↓",
      0x011E: "→",
      0x011F: "‣",
      0x0120: "＆",
      0x0121: "0",
      0x0122: "1",
      0x0123: "2",
      0x0124: "3",
      0x0125: "4",
      0x0126: "5",
      0x0127: "6",
      0x0128: "7",
      0x0129: "8",
      0x012A: "9",
      0x012B: "A",
      0x012C: "B",
      0x012D: "C",
      0x012E: "D",
      0x012F: "E",
      0x0130: "F",
      0x0131: "G",
      0x0132: "H",
      0x0133: "I",
      0x0134: "J",
      0x0135: "K",
      0x0136: "L",
      0x0137: "M",
      0x0138: "N",
      0x0139: "O",
      0x013A: "P",
      0x013B: "Q",
      0x013C: "R",
      0x013D: "S",
      0x013E: "T",
      0x013F: "U",
      0x0140: "V",
      0x0141: "W",
      0x0142: "X",
      0x0143: "Y",
      0x0144: "Z",
      0x0145: "a",
      0x0146: "b",
      0x0147: "c",
      0x0148: "d",
      0x0149: "e",
      0x014A: "f",
      0x014B: "g",
      0x014C: "h",
      0x014D: "i",
      0x014E: "j",
      0x014F: "k",
      0x0150: "l",
      0x0151: "m",
      0x0152: "n",
      0x0153: "o",
      0x0154: "p",
      0x0155: "q",
      0x0156: "r",
      0x0157: "s",
      0x0158: "t",
      0x0159: "u",
      0x015A: "v",
      0x015B: "w",
      0x015C: "x",
      0x015D: "y",
      0x015E: "z",
      0x015F: "À",
      0x0160: "Á",
      0x0161: "Â",
      0x0162: "Ã",
      0x0163: "Ä",
      0x0164: "Å",
      0x0165: "Æ",
      0x0166: "Ç",
      0x0167: "È",
      0x0168: "É",
      0x0169: "Ê",
      0x016A: "Ë",
      0x016B: "Ì",
      0x016C: "Í",
      0x016D: "Î",
      0x016E: "Ï",
      0x016F: "Ð",
      0x0170: "Ñ",
      0x0171: "Ò",
      0x0172: "Ó",
      0x0173: "Ô",
      0x0174: "Õ",
      0x0175: "Ö",
      0x0176: "×",
      0x0177: "Ø",
      0x0178: "Ù",
      0x0179: "Ú",
      0x017A: "Û",
      0x017B: "Ü",
      0x017C: "Ý",
      0x017D: "Þ",
      0x017E: "ß",
      0x017F: "à",
      0x0180: "á",
      0x0181: "â",
      0x0182: "ã",
      0x0183: "ä",
      0x0184: "å",
      0x0185: "æ",
      0x0186: "ç",
      0x0187: "è",
      0x0188: "é",
      0x0189: "ê",
      0x018A: "ë",
      0x018B: "ì",
      0x018C: "í",
      0x018D: "î",
      0x018E: "ï",
      0x018F: "ð",
      0x0190: "ñ",
      0x0191: "ò",
      0x0192: "ó",
      0x0193: "ô",
      0x0194: "õ",
      0x0195: "ö",
      0x0196: "÷",
      0x0197: "ø",
      0x0198: "ù",
      0x0199: "ú",
      0x019A: "û",
      0x019B: "ü",
      0x019C: "ý",
      0x019D: "þ",
      0x019E: "ÿ",
      0x019F: "Œ",
      0x01A0: "œ",
      0x01A1: "Ş",
      0x01A2: "ş",
      0x01A3: "ª",
      0x01A4: "º",
      0x01A5: "¹",
      0x01A6: "²",
      0x01A7: "³",
      0x01A8: "$",
      0x01A9: "¡",
      0x01AA: "¿",
      0x01AB: "!",
      0x01AC: "?",
      0x01AD: ",",
      0x01AE: ".",
      0x01AF: "…",
      0x01B0: "·",
      0x01B1: "/",
      0x01B2: "‘",
      0x01B3: "’",
      0x01B4: "“",
      0x01B5: "”",
      0x01B6: "„",
      0x01B7: "《",
      0x01B8: "》",
      0x01B9: "(",
      0x01BA: ")",
      0x01BB: "♂",
      0x01BC: "♀",
      0x01BD: "+",
      0x01BE: "-",
      0x01BF: "*",
      0x01C0: "#",
      0x01C1: "=",
      0x01C2: "&",
      0x01C3: "~",
      0x01C4: ":",
      0x01C5: ";"
}

gen3TextTable = {
    "0": " ",
    "163": "2",
    "174": "-",
    "187": "A",
    "188": "B",
    "189": "C",
    "190": "D",
    "191": "E",
    "192": "F",
    "193": "G",
    "194": "H",
    "195": "I",
    "196": "J",
    "197": "K",
    "198": "L",
    "199": "M",
    "200": "N",
    "201": "O",
    "202": "P",
    "203": "Q",
    "204": "R",
    "205": "S",
    "206": "T",
    "207": "U",
    "208": "V",
    "209": "W",
    "210": "X",
    "211": "Y",
    "212": "Z",
    "213": "a",
    "214": "b",
    "215": "c",
    "216": "d",
    "217": "e",
    "218": "f",
    "219": "g",
    "220": "h",
    "221": "i",
    "222": "j",
    "223": "k",
    "224": "l",
    "225": "m",
    "226": "n",
    "227": "o",
    "228": "p",
    "229": "q",
    "230": "r",
    "231": "s",
    "232": "t",
    "233": "u",
    "234": "v",
    "235": "w",
    "236": "x",
    "237": "y",
    "238": "z"
}


