growths = {"None":{"bs":{}},"Bulbasaur":{"bs":{},"gr":3},"Ivysaur":{"bs":{},"gr":3},"Venusaur":{"bs":{},"gr":3},"Charmander":{"bs":{},"gr":3},"Charmeleon":{"bs":{},"gr":3},"Charizard":{"bs":{},"gr":3},"Squirtle":{"bs":{},"gr":3},"Wartortle":{"bs":{},"gr":3},"Blastoise":{"bs":{},"gr":3},"Caterpie":{"bs":{},"gr":4},"Metapod":{"bs":{},"gr":4},"Butterfree":{"bs":{},"gr":4},"Weedle":{"bs":{},"gr":0},"Kakuna":{"bs":{},"gr":0},"Beedrill":{"bs":{},"gr":0},"Pidgey":{"bs":{},"gr":3},"Pidgeotto":{"bs":{},"gr":3},"Pidgeot":{"bs":{},"gr":3},"Rattata":{"bs":{},"gr":4},"Raticate":{"bs":{},"gr":4},"Spearow":{"bs":{},"gr":0},"Fearow":{"bs":{},"gr":0},"Ekans":{"bs":{},"gr":0},"Arbok":{"bs":{},"gr":0},"Pikachu":{"bs":{},"gr":0},"Raichu":{"bs":{},"gr":0},"Sandshrew":{"bs":{},"gr":0},"Sandslash":{"bs":{},"gr":0},"Nidoran-F":{"bs":{},"gr":3},"Nidorina":{"bs":{},"gr":3},"Nidoqueen":{"bs":{},"gr":3},"Nidoran-M":{"bs":{},"gr":3},"Nidorino":{"bs":{},"gr":3},"Nidoking":{"bs":{},"gr":3},"Clefairy":{"bs":{},"gr":0},"Clefable":{"bs":{},"gr":0},"Vulpix":{"bs":{},"gr":0},"Ninetales":{"bs":{},"gr":0},"Jigglypuff":{"bs":{},"gr":4},"Wigglytuff":{"bs":{},"gr":4},"Zubat":{"bs":{},"gr":0},"Golbat":{"bs":{},"gr":0},"Oddish":{"bs":{},"gr":3},"Gloom":{"bs":{},"gr":3},"Vileplume":{"bs":{},"gr":3},"Paras":{"bs":{},"gr":4},"Parasect":{"bs":{},"gr":4},"Venonat":{"bs":{},"gr":0},"Venomoth":{"bs":{},"gr":0},"Diglett":{"bs":{},"gr":0},"Dugtrio":{"bs":{},"gr":0},"Meowth":{"bs":{},"gr":0},"Persian":{"bs":{},"gr":0},"Psyduck":{"bs":{},"gr":0},"Golduck":{"bs":{},"gr":0},"Mankey":{"bs":{},"gr":0},"Primeape":{"bs":{},"gr":0},"Growlithe":{"bs":{},"gr":5},"Arcanine":{"bs":{},"gr":5},"Poliwag":{"bs":{},"gr":3},"Poliwhirl":{"bs":{},"gr":3},"Poliwrath":{"bs":{},"gr":3},"Abra":{"bs":{},"gr":3},"Kadabra":{"bs":{},"gr":3},"Alakazam":{"bs":{},"gr":3},"Machop":{"bs":{},"gr":3},"Machoke":{"bs":{},"gr":3},"Machamp":{"bs":{},"gr":3},"Bellsprout":{"bs":{},"gr":3},"Weepinbell":{"bs":{},"gr":3},"Victreebel":{"bs":{},"gr":3},"Tentacool":{"bs":{},"gr":5},"Tentacruel":{"bs":{},"gr":5},"Geodude":{"bs":{},"gr":3},"Graveler":{"bs":{},"gr":3},"Golem":{"bs":{},"gr":3},"Ponyta":{"bs":{},"gr":0},"Rapidash":{"bs":{},"gr":0},"Slowpoke":{"bs":{},"gr":0},"Slowbro":{"bs":{},"gr":0},"Magnemite":{"bs":{},"gr":0},"Magneton":{"bs":{},"gr":0},"Farfetch’d":{"bs":{},"gr":4},"Doduo":{"bs":{},"gr":0},"Dodrio":{"bs":{},"gr":0},"Seel":{"bs":{},"gr":0},"Dewgong":{"bs":{},"gr":0},"Grimer":{"bs":{},"gr":0},"Muk":{"bs":{},"gr":0},"Shellder":{"bs":{},"gr":5},"Cloyster":{"bs":{},"gr":5},"Gastly":{"bs":{},"gr":3},"Haunter":{"bs":{},"gr":3},"Gengar":{"bs":{},"gr":3},"Onix":{"bs":{},"gr":0},"Drowzee":{"bs":{},"gr":4},"Hypno":{"bs":{},"gr":4},"Krabby":{"bs":{},"gr":0},"Kingler":{"bs":{},"gr":0},"Voltorb":{"bs":{},"gr":0},"Electrode":{"bs":{},"gr":0},"Exeggcute":{"bs":{},"gr":0},"Exeggutor":{"bs":{},"gr":0},"Cubone":{"bs":{},"gr":0},"Marowak":{"bs":{},"gr":0},"Hitmonlee":{"bs":{},"gr":0},"Hitmonchan":{"bs":{},"gr":0},"Lickitung":{"bs":{},"gr":0},"Koffing":{"bs":{},"gr":0},"Weezing":{"bs":{},"gr":0},"Rhyhorn":{"bs":{},"gr":5},"Rhydon":{"bs":{},"gr":5},"Chansey":{"bs":{},"gr":4},"Tangela":{"bs":{},"gr":0},"Kangaskhan":{"bs":{},"gr":0},"Horsea":{"bs":{},"gr":0},"Seadra":{"bs":{},"gr":0},"Goldeen":{"bs":{},"gr":4},"Seaking":{"bs":{},"gr":4},"Staryu":{"bs":{},"gr":5},"Starmie":{"bs":{},"gr":5},"Mr. Mime":{"bs":{},"gr":0},"Scyther":{"bs":{},"gr":0},"Jynx":{"bs":{},"gr":0},"Electabuzz":{"bs":{},"gr":0},"Magmar":{"bs":{},"gr":0},"Pinsir":{"bs":{},"gr":5},"Tauros":{"bs":{},"gr":0},"Magikarp":{"bs":{},"gr":5},"Gyarados":{"bs":{},"gr":5},"Lapras":{"bs":{},"gr":5},"Ditto":{"bs":{},"gr":0},"Eevee":{"bs":{},"gr":0},"Vaporeon":{"bs":{},"gr":0},"Jolteon":{"bs":{},"gr":0},"Flareon":{"bs":{},"gr":0},"Porygon":{"bs":{},"gr":0},"Omanyte":{"bs":{},"gr":0},"Omastar":{"bs":{},"gr":0},"Kabuto":{"bs":{},"gr":0},"Kabutops":{"bs":{},"gr":0},"Aerodactyl":{"bs":{},"gr":5},"Snorlax":{"bs":{},"gr":5},"Articuno":{"bs":{},"gr":5},"Zapdos":{"bs":{},"gr":5},"Moltres":{"bs":{},"gr":5},"Dratini":{"bs":{},"gr":5},"Dragonair":{"bs":{},"gr":5},"Dragonite":{"bs":{},"gr":5},"Mewtwo":{"bs":{},"gr":5},"Mew":{"bs":{},"gr":3},"Chikorita":{"bs":{},"gr":3},"Bayleef":{"bs":{},"gr":3},"Meganium":{"bs":{},"gr":3},"Cyndaquil":{"bs":{},"gr":3},"Quilava":{"bs":{},"gr":3},"Typhlosion":{"bs":{},"gr":3},"Totodile":{"bs":{},"gr":3},"Croconaw":{"bs":{},"gr":3},"Feraligatr":{"bs":{},"gr":3},"Sentret":{"bs":{},"gr":4},"Furret":{"bs":{},"gr":4},"Hoothoot":{"bs":{},"gr":0},"Noctowl":{"bs":{},"gr":0},"Ledyba":{"bs":{},"gr":4},"Ledian":{"bs":{},"gr":4},"Spinarak":{"bs":{},"gr":4},"Ariados":{"bs":{},"gr":4},"Crobat":{"bs":{},"gr":0},"Chinchou":{"bs":{},"gr":4},"Lanturn":{"bs":{},"gr":4},"Pichu":{"bs":{},"gr":0},"Cleffa":{"bs":{},"gr":0},"Igglybuff":{"bs":{},"gr":4},"Togepi":{"bs":{},"gr":0},"Togetic":{"bs":{},"gr":0},"Natu":{"bs":{},"gr":0},"Xatu":{"bs":{},"gr":0},"Mareep":{"bs":{},"gr":3},"Flaaffy":{"bs":{},"gr":3},"Ampharos":{"bs":{},"gr":3},"Bellossom":{"bs":{},"gr":3},"Marill":{"bs":{},"gr":0},"Azumarill":{"bs":{},"gr":0},"Sudowoodo":{"bs":{},"gr":4},"Politoed":{"bs":{},"gr":3},"Hoppip":{"bs":{},"gr":3},"Skiploom":{"bs":{},"gr":3},"Jumpluff":{"bs":{},"gr":3},"Aipom":{"bs":{},"gr":4},"Sunkern":{"bs":{},"gr":3},"Sunflora":{"bs":{},"gr":3},"Yanma":{"bs":{},"gr":0},"Wooper":{"bs":{},"gr":0},"Quagsire":{"bs":{},"gr":0},"Espeon":{"bs":{},"gr":0},"Umbreon":{"bs":{},"gr":0},"Murkrow":{"bs":{},"gr":3},"Slowking":{"bs":{},"gr":0},"Misdreavus":{"bs":{},"gr":0},"Unown":{"bs":{},"gr":0},"Wobbuffet":{"bs":{},"gr":0},"Girafarig":{"bs":{},"gr":4},"Pineco":{"bs":{},"gr":0},"Forretress":{"bs":{},"gr":0},"Dunsparce":{"bs":{},"gr":4},"Gligar":{"bs":{},"gr":3},"Steelix":{"bs":{},"gr":0},"Snubbull":{"bs":{},"gr":4},"Granbull":{"bs":{},"gr":4},"Qwilfish":{"bs":{},"gr":4},"Scizor":{"bs":{},"gr":0},"Shuckle":{"bs":{},"gr":3},"Heracross":{"bs":{},"gr":5},"Sneasel":{"bs":{},"gr":3},"Teddiursa":{"bs":{},"gr":0},"Ursaring":{"bs":{},"gr":0},"Slugma":{"bs":{},"gr":4},"Magcargo":{"bs":{},"gr":4},"Swinub":{"bs":{},"gr":5},"Piloswine":{"bs":{},"gr":5},"Corsola":{"bs":{},"gr":4},"Remoraid":{"bs":{},"gr":0},"Octillery":{"bs":{},"gr":0},"Delibird":{"bs":{},"gr":4},"Mantine":{"bs":{},"gr":0},"Skarmory":{"bs":{},"gr":5},"Houndour":{"bs":{},"gr":5},"Houndoom":{"bs":{},"gr":5},"Kingdra":{"bs":{},"gr":0},"Phanpy":{"bs":{},"gr":0},"Donphan":{"bs":{},"gr":0},"Porygon2":{"bs":{},"gr":0},"Stantler":{"bs":{},"gr":4},"Smeargle":{"bs":{},"gr":4},"Tyrogue":{"bs":{},"gr":0},"Hitmontop":{"bs":{},"gr":0},"Smoochum":{"bs":{},"gr":0},"Elekid":{"bs":{},"gr":0},"Magby":{"bs":{},"gr":0},"Miltank":{"bs":{},"gr":0},"Blissey":{"bs":{},"gr":4},"Raikou":{"bs":{},"gr":5},"Entei":{"bs":{},"gr":5},"Suicune":{"bs":{},"gr":5},"Larvitar":{"bs":{},"gr":5},"Pupitar":{"bs":{},"gr":5},"Tyranitar":{"bs":{},"gr":5},"Lugia":{"bs":{},"gr":5},"Ho-Oh":{"bs":{},"gr":5},"Celebi":{"bs":{},"gr":3},"Treecko":{"bs":{},"gr":3},"Grovyle":{"bs":{},"gr":3},"Sceptile":{"bs":{},"gr":3},"Torchic":{"bs":{},"gr":3},"Combusken":{"bs":{},"gr":3},"Blaziken":{"bs":{},"gr":3},"Mudkip":{"bs":{},"gr":3},"Marshtomp":{"bs":{},"gr":3},"Swampert":{"bs":{},"gr":3},"Poochyena":{"bs":{},"gr":4},"Mightyena":{"bs":{},"gr":4},"Zigzagoon":{"bs":{},"gr":0},"Linoone":{"bs":{},"gr":0},"Wurmple":{"bs":{},"gr":4},"Silcoon":{"bs":{},"gr":4},"Beautifly":{"bs":{},"gr":4},"Cascoon":{"bs":{},"gr":4},"Dustox":{"bs":{},"gr":4},"Lotad":{"bs":{},"gr":3},"Lombre":{"bs":{},"gr":3},"Ludicolo":{"bs":{},"gr":3},"Seedot":{"bs":{},"gr":3},"Nuzleaf":{"bs":{},"gr":3},"Shiftry":{"bs":{},"gr":3},"Taillow":{"bs":{},"gr":3},"Swellow":{"bs":{},"gr":3},"Wingull":{"bs":{},"gr":0},"Pelipper":{"bs":{},"gr":0},"Ralts":{"bs":{},"gr":5},"Kirlia":{"bs":{},"gr":5},"Gardevoir":{"bs":{},"gr":5},"Surskit":{"bs":{},"gr":0},"Masquerain":{"bs":{},"gr":0},"Shroomish":{"bs":{},"gr":0},"Breloom":{"bs":{},"gr":0},"Slakoth":{"bs":{},"gr":5},"Vigoroth":{"bs":{},"gr":5},"Slaking":{"bs":{},"gr":5},"Nincada":{"bs":{},"gr":0},"Ninjask":{"bs":{},"gr":0},"Shedinja":{"bs":{},"gr":0},"Whismur":{"bs":{},"gr":3},"Loudred":{"bs":{},"gr":3},"Exploud":{"bs":{},"gr":3},"Makuhita":{"bs":{},"gr":4},"Hariyama":{"bs":{},"gr":4},"Azurill":{"bs":{},"gr":0},"Nosepass":{"bs":{},"gr":0},"Skitty":{"bs":{},"gr":4},"Delcatty":{"bs":{},"gr":4},"Sableye":{"bs":{},"gr":3},"Mawile":{"bs":{},"gr":4},"Aron":{"bs":{},"gr":5},"Lairon":{"bs":{},"gr":5},"Aggron":{"bs":{},"gr":5},"Meditite":{"bs":{},"gr":0},"Medicham":{"bs":{},"gr":0},"Electrike":{"bs":{},"gr":5},"Manectric":{"bs":{},"gr":5},"Plusle":{"bs":{},"gr":4},"Minun":{"bs":{},"gr":4},"Volbeat":{"bs":{},"gr":4},"Illumise":{"bs":{},"gr":4},"Roselia":{"bs":{},"gr":3},"Gulpin":{"bs":{},"gr":4},"Swalot":{"bs":{},"gr":4},"Carvanha":{"bs":{},"gr":5},"Sharpedo":{"bs":{},"gr":5},"Wailmer":{"bs":{},"gr":4},"Wailord":{"bs":{},"gr":4},"Numel":{"bs":{},"gr":4},"Camerupt":{"bs":{},"gr":4},"Torkoal":{"bs":{},"gr":0},"Spoink":{"bs":{},"gr":4},"Grumpig":{"bs":{},"gr":4},"Spinda":{"bs":{},"gr":4},"Trapinch":{"bs":{},"gr":3},"Vibrava":{"bs":{},"gr":3},"Flygon":{"bs":{},"gr":3},"Cacnea":{"bs":{},"gr":3},"Cacturne":{"bs":{},"gr":3},"Swablu":{"bs":{},"gr":0},"Altaria":{"bs":{},"gr":0},"Zangoose":{"bs":{},"gr":4},"Seviper":{"bs":{},"gr":4},"Lunatone":{"bs":{},"gr":4},"Solrock":{"bs":{},"gr":4},"Barboach":{"bs":{},"gr":0},"Whiscash":{"bs":{},"gr":0},"Corphish":{"bs":{},"gr":0},"Crawdaunt":{"bs":{},"gr":0},"Baltoy":{"bs":{},"gr":0},"Claydol":{"bs":{},"gr":0},"Lileep":{"bs":{},"gr":4},"Cradily":{"bs":{},"gr":4},"Anorith":{"bs":{},"gr":4},"Armaldo":{"bs":{},"gr":4},"Feebas":{"bs":{},"gr":0},"Milotic":{"bs":{},"gr":0},"Castform":{"bs":{},"gr":4},"Kecleon":{"bs":{},"gr":3},"Shuppet":{"bs":{},"gr":4},"Banette":{"bs":{},"gr":4},"Duskull":{"bs":{},"gr":4},"Dusclops":{"bs":{},"gr":4},"Tropius":{"bs":{},"gr":4},"Chimecho":{"bs":{},"gr":4},"Absol":{"bs":{},"gr":3},"Wynaut":{"bs":{},"gr":0},"Snorunt":{"bs":{},"gr":0},"Glalie":{"bs":{},"gr":0},"Spheal":{"bs":{},"gr":3},"Sealeo":{"bs":{},"gr":3},"Walrein":{"bs":{},"gr":3},"Clamperl":{"bs":{},"gr":1},"Huntail":{"bs":{},"gr":1},"Gorebyss":{"bs":{},"gr":1},"Relicanth":{"bs":{},"gr":4},"Luvdisc":{"bs":{},"gr":4},"Bagon":{"bs":{},"gr":5},"Shelgon":{"bs":{},"gr":5},"Salamence":{"bs":{},"gr":5},"Beldum":{"bs":{},"gr":5},"Metang":{"bs":{},"gr":5},"Metagross":{"bs":{},"gr":5},"Regirock":{"bs":{},"gr":5},"Regice":{"bs":{},"gr":5},"Registeel":{"bs":{},"gr":5},"Latias":{"bs":{},"gr":5},"Latios":{"bs":{},"gr":5},"Kyogre":{"bs":{},"gr":5},"Groudon":{"bs":{},"gr":5},"Rayquaza":{"bs":{},"gr":5},"Jirachi":{"bs":{},"gr":5},"Deoxys":{"bs":{},"gr":5},"Turtwig":{"bs":{},"gr":3},"Grotle":{"bs":{},"gr":3},"Torterra":{"bs":{},"gr":3},"Chimchar":{"bs":{},"gr":3},"Monferno":{"bs":{},"gr":3},"Infernape":{"bs":{},"gr":3},"Piplup":{"bs":{},"gr":3},"Prinplup":{"bs":{},"gr":3},"Empoleon":{"bs":{},"gr":3},"Starly":{"bs":{},"gr":3},"Staravia":{"bs":{},"gr":3},"Staraptor":{"bs":{},"gr":3},"Bidoof":{"bs":{},"gr":0},"Bibarel":{"bs":{},"gr":0},"Kricketot":{"bs":{},"gr":4},"Kricketune":{"bs":{},"gr":4},"Shinx":{"bs":{},"gr":3},"Luxio":{"bs":{},"gr":3},"Luxray":{"bs":{},"gr":3},"Budew":{"bs":{},"gr":3},"Roserade":{"bs":{},"gr":3},"Cranidos":{"bs":{},"gr":1},"Rampardos":{"bs":{},"gr":1},"Shieldon":{"bs":{},"gr":4},"Bastiodon":{"bs":{},"gr":4},"Burmy":{"bs":{},"gr":4},"Wormadam":{"bs":{},"gr":4},"Mothim":{"bs":{},"gr":4},"Combee":{"bs":{},"gr":3},"Vespiquen":{"bs":{},"gr":3},"Pachirisu":{"bs":{},"gr":4},"Buizel":{"bs":{},"gr":0},"Floatzel":{"bs":{},"gr":0},"Cherubi":{"bs":{},"gr":4},"Cherrim":{"bs":{},"gr":4},"Shellos":{"bs":{},"gr":0},"Gastrodon":{"bs":{},"gr":0},"Ambipom":{"bs":{},"gr":4},"Drifloon":{"bs":{},"gr":4},"Drifblim":{"bs":{},"gr":4},"Buneary":{"bs":{},"gr":0},"Lopunny":{"bs":{},"gr":0},"Mismagius":{"bs":{},"gr":0},"Honchkrow":{"bs":{},"gr":3},"Glameow":{"bs":{},"gr":4},"Purugly":{"bs":{},"gr":4},"Chingling":{"bs":{},"gr":4},"Stunky":{"bs":{},"gr":0},"Skuntank":{"bs":{},"gr":0},"Bronzor":{"bs":{},"gr":0},"Bronzong":{"bs":{},"gr":0},"Bonsly":{"bs":{},"gr":4},"Mime Jr.":{"bs":{},"gr":0},"Happiny":{"bs":{},"gr":4},"Chatot":{"bs":{},"gr":3},"Spiritomb":{"bs":{},"gr":0},"Gible":{"bs":{},"gr":5},"Gabite":{"bs":{},"gr":5},"Garchomp":{"bs":{},"gr":5},"Munchlax":{"bs":{},"gr":5},"Riolu":{"bs":{},"gr":3},"Lucario":{"bs":{},"gr":3},"Hippopotas":{"bs":{},"gr":5},"Hippowdon":{"bs":{},"gr":5},"Skorupi":{"bs":{},"gr":5},"Drapion":{"bs":{},"gr":5},"Croagunk":{"bs":{},"gr":0},"Toxicroak":{"bs":{},"gr":0},"Carnivine":{"bs":{},"gr":4},"Finneon":{"bs":{},"gr":1},"Lumineon":{"bs":{},"gr":1},"Mantyke":{"bs":{},"gr":0},"Snover":{"bs":{},"gr":5},"Abomasnow":{"bs":{},"gr":5},"Weavile":{"bs":{},"gr":3},"Magnezone":{"bs":{},"gr":0},"Lickilicky":{"bs":{},"gr":0},"Rhyperior":{"bs":{},"gr":5},"Tangrowth":{"bs":{},"gr":0},"Electivire":{"bs":{},"gr":0},"Magmortar":{"bs":{},"gr":0},"Togekiss":{"bs":{},"gr":0},"Yanmega":{"bs":{},"gr":0},"Leafeon":{"bs":{},"gr":0},"Glaceon":{"bs":{},"gr":0},"Gliscor":{"bs":{},"gr":3},"Mamoswine":{"bs":{},"gr":5},"Porygon-Z":{"bs":{},"gr":0},"Gallade":{"bs":{},"gr":5},"Probopass":{"bs":{},"gr":0},"Dusknoir":{"bs":{},"gr":4},"Froslass":{"bs":{},"gr":0},"Rotom":{"bs":{},"gr":0},"Uxie":{"bs":{},"gr":5},"Mesprit":{"bs":{},"gr":5},"Azelf":{"bs":{},"gr":5},"Dialga":{"bs":{},"gr":5},"Palkia":{"bs":{},"gr":5},"Heatran":{"bs":{},"gr":5},"Regigigas":{"bs":{},"gr":5},"Giratina":{"bs":{},"gr":5},"Cresselia":{"bs":{},"gr":5},"Phione":{"bs":{},"gr":5},"Manaphy":{"bs":{},"gr":5},"Darkrai":{"bs":{},"gr":5},"Shaymin":{"bs":{},"gr":3},"Arceus":{"bs":{},"gr":5},"Victini":{"bs":{},"gr":5},"Snivy":{"bs":{},"gr":3},"Servine":{"bs":{},"gr":3},"Serperior":{"bs":{},"gr":3},"Tepig":{"bs":{},"gr":3},"Pignite":{"bs":{},"gr":3},"Emboar":{"bs":{},"gr":3},"Oshawott":{"bs":{},"gr":3},"Dewott":{"bs":{},"gr":3},"Samurott":{"bs":{},"gr":3},"Patrat":{"bs":{},"gr":4},"Watchog":{"bs":{},"gr":4},"Lillipup":{"bs":{},"gr":3},"Herdier":{"bs":{},"gr":3},"Stoutland":{"bs":{},"gr":3},"Purrloin":{"bs":{},"gr":0},"Liepard":{"bs":{},"gr":0},"Pansage":{"bs":{},"gr":0},"Simisage":{"bs":{},"gr":0},"Pansear":{"bs":{},"gr":0},"Simisear":{"bs":{},"gr":0},"Panpour":{"bs":{},"gr":0},"Simipour":{"bs":{},"gr":0},"Munna":{"bs":{},"gr":0},"Musharna":{"bs":{},"gr":0},"Pidove":{"bs":{},"gr":3},"Tranquill":{"bs":{},"gr":3},"Unfezant":{"bs":{},"gr":3},"Blitzle":{"bs":{},"gr":0},"Zebstrika":{"bs":{},"gr":0},"Roggenrola":{"bs":{},"gr":3},"Boldore":{"bs":{},"gr":3},"Gigalith":{"bs":{},"gr":3},"Woobat":{"bs":{},"gr":0},"Swoobat":{"bs":{},"gr":0},"Drilbur":{"bs":{},"gr":0},"Excadrill":{"bs":{},"gr":0},"Audino":{"bs":{},"gr":4},"Timburr":{"bs":{},"gr":3},"Gurdurr":{"bs":{},"gr":3},"Conkeldurr":{"bs":{},"gr":3},"Tympole":{"bs":{},"gr":3},"Palpitoad":{"bs":{},"gr":3},"Seismitoad":{"bs":{},"gr":3},"Throh":{"bs":{},"gr":0},"Sawk":{"bs":{},"gr":0},"Sewaddle":{"bs":{},"gr":3},"Swadloon":{"bs":{},"gr":3},"Leavanny":{"bs":{},"gr":3},"Venipede":{"bs":{},"gr":3},"Whirlipede":{"bs":{},"gr":3},"Scolipede":{"bs":{},"gr":3},"Cottonee":{"bs":{},"gr":0},"Whimsicott":{"bs":{},"gr":0},"Petilil":{"bs":{},"gr":0},"Lilligant":{"bs":{},"gr":0},"Basculin":{"bs":{},"gr":0},"Sandile":{"bs":{},"gr":3},"Krokorok":{"bs":{},"gr":3},"Krookodile":{"bs":{},"gr":3},"Darumaka":{"bs":{},"gr":3},"Darmanitan":{"bs":{},"gr":3},"Maractus":{"bs":{},"gr":4},"Dwebble":{"bs":{},"gr":0},"Crustle":{"bs":{},"gr":0},"Scraggy":{"bs":{},"gr":0},"Scrafty":{"bs":{},"gr":0},"Sigilyph":{"bs":{},"gr":0},"Yamask":{"bs":{},"gr":0},"Cofagrigus":{"bs":{},"gr":0},"Tirtouga":{"bs":{},"gr":0},"Carracosta":{"bs":{},"gr":0},"Archen":{"bs":{},"gr":0},"Archeops":{"bs":{},"gr":0},"Trubbish":{"bs":{},"gr":0},"Garbodor":{"bs":{},"gr":0},"Zorua":{"bs":{},"gr":3},"Zoroark":{"bs":{},"gr":3},"Minccino":{"bs":{},"gr":4},"Cinccino":{"bs":{},"gr":4},"Gothita":{"bs":{},"gr":3},"Gothorita":{"bs":{},"gr":3},"Gothitelle":{"bs":{},"gr":3},"Solosis":{"bs":{},"gr":3},"Duosion":{"bs":{},"gr":3},"Reuniclus":{"bs":{},"gr":3},"Ducklett":{"bs":{},"gr":0},"Swanna":{"bs":{},"gr":0},"Vanillite":{"bs":{},"gr":0},"Vanillish":{"bs":{},"gr":0},"Vanilluxe":{"bs":{},"gr":0},"Deerling":{"bs":{},"gr":0},"Sawsbuck":{"bs":{},"gr":0},"Emolga":{"bs":{},"gr":0},"Karrablast":{"bs":{},"gr":0},"Escavalier":{"bs":{},"gr":0},"Foongus":{"bs":{},"gr":0},"Amoonguss":{"bs":{},"gr":0},"Frillish":{"bs":{},"gr":0},"Jellicent":{"bs":{},"gr":0},"Alomomola":{"bs":{},"gr":4},"Joltik":{"bs":{},"gr":0},"Galvantula":{"bs":{},"gr":0},"Ferroseed":{"bs":{},"gr":0},"Ferrothorn":{"bs":{},"gr":0},"Klink":{"bs":{},"gr":3},"Klang":{"bs":{},"gr":3},"Klinklang":{"bs":{},"gr":3},"Tynamo":{"bs":{},"gr":5},"Eelektrik":{"bs":{},"gr":5},"Eelektross":{"bs":{},"gr":5},"Elgyem":{"bs":{},"gr":0},"Beheeyem":{"bs":{},"gr":0},"Litwick":{"bs":{},"gr":3},"Lampent":{"bs":{},"gr":3},"Chandelure":{"bs":{},"gr":3},"Axew":{"bs":{},"gr":5},"Fraxure":{"bs":{},"gr":5},"Haxorus":{"bs":{},"gr":5},"Cubchoo":{"bs":{},"gr":0},"Beartic":{"bs":{},"gr":0},"Cryogonal":{"bs":{},"gr":0},"Shelmet":{"bs":{},"gr":0},"Accelgor":{"bs":{},"gr":0},"Stunfisk":{"bs":{},"gr":0},"Mienfoo":{"bs":{},"gr":3},"Mienshao":{"bs":{},"gr":3},"Druddigon":{"bs":{},"gr":0},"Golett":{"bs":{},"gr":0},"Golurk":{"bs":{},"gr":0},"Pawniard":{"bs":{},"gr":0},"Bisharp":{"bs":{},"gr":0},"Bouffalant":{"bs":{},"gr":0},"Rufflet":{"bs":{},"gr":5},"Braviary":{"bs":{},"gr":5},"Vullaby":{"bs":{},"gr":5},"Mandibuzz":{"bs":{},"gr":5},"Heatmor":{"bs":{},"gr":0},"Durant":{"bs":{},"gr":0},"Deino":{"bs":{},"gr":5},"Zweilous":{"bs":{},"gr":5},"Hydreigon":{"bs":{},"gr":5},"Larvesta":{"bs":{},"gr":5},"Volcarona":{"bs":{},"gr":5},"Cobalion":{"bs":{},"gr":5},"Terrakion":{"bs":{},"gr":5},"Virizion":{"bs":{},"gr":5},"Tornadus":{"bs":{},"gr":5},"Thundurus":{"bs":{},"gr":5},"Reshiram":{"bs":{},"gr":5},"Zekrom":{"bs":{},"gr":5},"Landorus":{"bs":{},"gr":5},"Kyurem":{"bs":{},"gr":5},"Keldeo":{"bs":{},"gr":5},"Meloetta":{"bs":{},"gr":5},"Genesect":{"bs":{},"gr":5},"Chespin":{"bs":{},"gr":3},"Quilladin":{"bs":{},"gr":3},"Chesnaught":{"bs":{},"gr":3},"Fennekin":{"bs":{},"gr":3},"Braixen":{"bs":{},"gr":3},"Delphox":{"bs":{},"gr":3},"Froakie":{"bs":{},"gr":3},"Frogadier":{"bs":{},"gr":3},"Greninja":{"bs":{},"gr":3},"Bunnelby":{"bs":{},"gr":0},"Diggersby":{"bs":{},"gr":0},"Fletchling":{"bs":{},"gr":3},"Fletchinder":{"bs":{},"gr":3},"Talonflame":{"bs":{},"gr":3},"Scatterbug":{"bs":{},"gr":0},"Spewpa":{"bs":{},"gr":0},"Vivillon":{"bs":{},"gr":0},"Litleo":{"bs":{},"gr":3},"Pyroar":{"bs":{},"gr":3},"Flabébé":{"bs":{},"gr":0},"Floette":{"bs":{},"gr":0},"Florges":{"bs":{},"gr":0},"Skiddo":{"bs":{},"gr":0},"Gogoat":{"bs":{},"gr":0},"Pancham":{"bs":{},"gr":0},"Pangoro":{"bs":{},"gr":0},"Furfrou":{"bs":{},"gr":0},"Espurr":{"bs":{},"gr":0},"Meowstic":{"bs":{},"gr":0},"Honedge":{"bs":{},"gr":0},"Doublade":{"bs":{},"gr":0},"Spritzee":{"bs":{},"gr":0},"Aromatisse":{"bs":{},"gr":0},"Swirlix":{"bs":{},"gr":0},"Slurpuff":{"bs":{},"gr":0},"Inkay":{"bs":{},"gr":0},"Malamar":{"bs":{},"gr":0},"Binacle":{"bs":{},"gr":0},"Barbaracle":{"bs":{},"gr":0},"Skrelp":{"bs":{},"gr":0},"Dragalge":{"bs":{},"gr":0},"Clauncher":{"bs":{},"gr":0},"Clawitzer":{"bs":{},"gr":0},"Helioptile":{"bs":{},"gr":0},"Heliolisk":{"bs":{},"gr":0},"Tyrunt":{"bs":{},"gr":0},"Tyrantrum":{"bs":{},"gr":0},"Amaura":{"bs":{},"gr":0},"Aurorus":{"bs":{},"gr":0},"Sylveon":{"bs":{},"gr":0},"Hawlucha":{"bs":{},"gr":0},"Dedenne":{"bs":{},"gr":4},"Carbink":{"bs":{},"gr":0},"Goomy":{"bs":{},"gr":5},"Sliggoo":{"bs":{},"gr":5},"Goodra":{"bs":{},"gr":5},"Klefki":{"bs":{},"gr":4},"Phantump":{"bs":{},"gr":0},"Trevenant":{"bs":{},"gr":0},"Pumpkaboo":{"bs":{},"gr":0},"Gourgeist":{"bs":{},"gr":0},"Bergmite":{"bs":{},"gr":0},"Avalugg":{"bs":{},"gr":0},"Noibat":{"bs":{},"gr":0},"Noivern":{"bs":{},"gr":0},"Xerneas":{"bs":{},"gr":5},"Yveltal":{"bs":{},"gr":5},"Zygarde":{"bs":{},"gr":5},"Diancie":{"bs":{},"gr":5},"Hoopa":{"bs":{},"gr":5},"Volcanion":{"bs":{},"gr":5},"Rowlet":{"bs":{},"gr":3},"Dartrix":{"bs":{},"gr":3},"Decidueye":{"bs":{},"gr":3},"Litten":{"bs":{},"gr":3},"Torracat":{"bs":{},"gr":3},"Incineroar":{"bs":{},"gr":3},"Popplio":{"bs":{},"gr":3},"Brionne":{"bs":{},"gr":3},"Primarina":{"bs":{},"gr":3},"Pikipek":{"bs":{},"gr":0},"Trumbeak":{"bs":{},"gr":0},"Toucannon":{"bs":{},"gr":0},"Yungoos":{"bs":{},"gr":0},"Gumshoos":{"bs":{},"gr":0},"Grubbin":{"bs":{},"gr":0},"Charjabug":{"bs":{},"gr":0},"Vikavolt":{"bs":{},"gr":0},"Crabrawler":{"bs":{},"gr":0},"Crabominable":{"bs":{},"gr":0},"Oricorio":{"bs":{},"gr":0},"Cutiefly":{"bs":{},"gr":0},"Ribombee":{"bs":{},"gr":0},"Rockruff":{"bs":{},"gr":0},"Lycanroc":{"bs":{},"gr":0},"Wishiwashi":{"bs":{},"gr":4},"Mareanie":{"bs":{},"gr":0},"Toxapex":{"bs":{},"gr":0},"Mudbray":{"bs":{},"gr":0},"Mudsdale":{"bs":{},"gr":0},"Dewpider":{"bs":{},"gr":0},"Araquanid":{"bs":{},"gr":0},"Fomantis":{"bs":{},"gr":0},"Lurantis":{"bs":{},"gr":0},"Morelull":{"bs":{},"gr":0},"Shiinotic":{"bs":{},"gr":0},"Salandit":{"bs":{},"gr":0},"Salazzle":{"bs":{},"gr":0},"Stufful":{"bs":{},"gr":0},"Bewear":{"bs":{},"gr":0},"Bounsweet":{"bs":{},"gr":3},"Steenee":{"bs":{},"gr":3},"Tsareena":{"bs":{},"gr":3},"Comfey":{"bs":{},"gr":4},"Oranguru":{"bs":{},"gr":5},"Passimian":{"bs":{},"gr":5},"Wimpod":{"bs":{},"gr":0},"Golisopod":{"bs":{},"gr":0},"Sandygast":{"bs":{},"gr":0},"Palossand":{"bs":{},"gr":0},"Pyukumuku":{"bs":{},"gr":4},"Type: Null":{"bs":{},"gr":5},"Silvally":{"bs":{},"gr":5},"Minior":{"bs":{},"gr":3},"Komala":{"bs":{},"gr":5},"Turtonator":{"bs":{},"gr":0},"Togedemaru":{"bs":{},"gr":0},"Mimikyu":{"bs":{},"gr":0},"Bruxish":{"bs":{},"gr":0},"Drampa":{"bs":{},"gr":0},"Dhelmise":{"bs":{},"gr":0},"Jangmo-o":{"bs":{},"gr":5},"Hakamo-o":{"bs":{},"gr":5},"Kommo-o":{"bs":{},"gr":5},"Tapu Koko":{"bs":{},"gr":5},"Tapu Lele":{"bs":{},"gr":5},"Tapu Bulu":{"bs":{},"gr":5},"Tapu Fini":{"bs":{},"gr":5},"Cosmog":{"bs":{},"gr":5},"Cosmoem":{"bs":{},"gr":5},"Solgaleo":{"bs":{},"gr":5},"Lunala":{"bs":{},"gr":5},"Nihilego":{"bs":{},"gr":5},"Buzzwole":{"bs":{},"gr":5},"Pheromosa":{"bs":{},"gr":5},"Xurkitree":{"bs":{},"gr":5},"Celesteela":{"bs":{},"gr":5},"Kartana":{"bs":{},"gr":5},"Guzzlord":{"bs":{},"gr":5},"Necrozma":{"bs":{},"gr":5},"Magearna":{"bs":{},"gr":5},"Marshadow":{"bs":{},"gr":5},"Poipole":{"bs":{},"gr":5},"Naganadel":{"bs":{},"gr":5},"Stakataka":{"bs":{},"gr":5},"Blacephalon":{"bs":{},"gr":5},"Zeraora":{"bs":{},"gr":5},"Meltan":{"bs":{},"gr":5},"Melmetal":{"bs":{},"gr":5},"Grookey":{"bs":{},"gr":3},"Thwackey":{"bs":{},"gr":3},"Rillaboom":{"bs":{},"gr":3},"Scorbunny":{"bs":{},"gr":3},"Raboot":{"bs":{},"gr":3},"Cinderace":{"bs":{},"gr":3},"Sobble":{"bs":{},"gr":3},"Drizzile":{"bs":{},"gr":3},"Inteleon":{"bs":{},"gr":3},"Skwovet":{"bs":{},"gr":0},"Greedent":{"bs":{},"gr":0},"Rookidee":{"bs":{},"gr":3},"Corvisquire":{"bs":{},"gr":3},"Corviknight":{"bs":{},"gr":3},"Blipbug":{"bs":{},"gr":0},"Dottler":{"bs":{},"gr":0},"Orbeetle":{"bs":{},"gr":0},"Nickit":{"bs":{},"gr":4},"Thievul":{"bs":{},"gr":4},"Gossifleur":{"bs":{},"gr":0},"Eldegoss":{"bs":{},"gr":0},"Wooloo":{"bs":{},"gr":0},"Dubwool":{"bs":{},"gr":0},"Chewtle":{"bs":{},"gr":0},"Drednaw":{"bs":{},"gr":0},"Yamper":{"bs":{},"gr":4},"Boltund":{"bs":{},"gr":4},"Rolycoly":{"bs":{},"gr":3},"Carkol":{"bs":{},"gr":3},"Coalossal":{"bs":{},"gr":3},"Applin":{"bs":{},"gr":1},"Flapple":{"bs":{},"gr":1},"Appletun":{"bs":{},"gr":1},"Silicobra":{"bs":{},"gr":0},"Sandaconda":{"bs":{},"gr":0},"Cramorant":{"bs":{},"gr":0},"Arrokuda":{"bs":{},"gr":5},"Barraskewda":{"bs":{},"gr":5},"Toxel":{"bs":{},"gr":3},"Toxtricity":{"bs":{},"gr":3},"Sizzlipede":{"bs":{},"gr":0},"Centiskorch":{"bs":{},"gr":0},"Clobbopus":{"bs":{},"gr":3},"Grapploct":{"bs":{},"gr":3},"Sinistea":{"bs":{},"gr":0},"Polteageist":{"bs":{},"gr":0},"Hatenna":{"bs":{},"gr":5},"Hattrem":{"bs":{},"gr":5},"Hatterene":{"bs":{},"gr":5},"Impidimp":{"bs":{},"gr":0},"Morgrem":{"bs":{},"gr":0},"Grimmsnarl":{"bs":{},"gr":0},"Obstagoon":{"bs":{},"gr":0},"Perrserker":{"bs":{},"gr":0},"Cursola":{"bs":{},"gr":4},"Sirfetch’d":{"bs":{},"gr":4},"Mr. Rime":{"bs":{},"gr":0},"Runerigus":{"bs":{},"gr":0},"Milcery":{"bs":{},"gr":0},"Alcremie":{"bs":{},"gr":0},"Falinks":{"bs":{},"gr":0},"Pincurchin":{"bs":{},"gr":0},"Snom":{"bs":{},"gr":0},"Frosmoth":{"bs":{},"gr":0},"Stonjourner":{"bs":{},"gr":5},"Eiscue":{"bs":{},"gr":5},"Indeedee":{"bs":{},"gr":4},"Morpeko":{"bs":{},"gr":0},"Cufant":{"bs":{},"gr":0},"Copperajah":{"bs":{},"gr":0},"Dracozolt":{"bs":{},"gr":5},"Arctozolt":{"bs":{},"gr":5},"Dracovish":{"bs":{},"gr":5},"Arctovish":{"bs":{},"gr":5},"Duraludon":{"bs":{},"gr":0},"Dreepy":{"bs":{},"gr":5},"Drakloak":{"bs":{},"gr":5},"Dragapult":{"bs":{},"gr":5},"Zacian":{"bs":{},"gr":5},"Zamazenta":{"bs":{},"gr":5},"Eternatus":{"bs":{},"gr":5},"Kubfu":{"bs":{},"gr":5},"Urshifu":{"bs":{},"gr":5},"Zarude":{"bs":{},"gr":5},"Regieleki":{"bs":{},"gr":5},"Regidrago":{"bs":{},"gr":5},"Glastrier":{"bs":{},"gr":5},"Spectrier":{"bs":{},"gr":5},"Calyrex":{"bs":{},"gr":5},"Venusaur-Mega":{"bs":{},"gr":3},"Charizard-Mega-X":{"bs":{},"gr":3},"Charizard-Mega-Y":{"bs":{},"gr":3},"Blastoise-Mega":{"bs":{},"gr":3},"Beedrill-Mega":{"bs":{},"gr":0},"Pidgeot-Mega":{"bs":{},"gr":3},"Alakazam-Mega":{"bs":{},"gr":3},"Slowbro-Mega":{"bs":{},"gr":0},"Gengar-Mega":{"bs":{},"gr":3},"Kangaskhan-Mega":{"bs":{},"gr":0},"Pinsir-Mega":{"bs":{},"gr":5},"Gyarados-Mega":{"bs":{},"gr":5},"Aerodactyl-Mega":{"bs":{},"gr":5},"Mewtwo-Mega-X":{"bs":{},"gr":5},"Mewtwo-Mega-Y":{"bs":{},"gr":5},"Ampharos-Mega":{"bs":{},"gr":3},"Steelix-Mega":{"bs":{},"gr":0},"Scizor-Mega":{"bs":{},"gr":0},"Heracross-Mega":{"bs":{},"gr":5},"Houndoom-Mega":{"bs":{},"gr":5},"Tyranitar-Mega":{"bs":{},"gr":5},"Sceptile-Mega":{"bs":{},"gr":3},"Blaziken-Mega":{"bs":{},"gr":3},"Swampert-Mega":{"bs":{},"gr":3},"Gardevoir-Mega":{"bs":{},"gr":5},"Sableye-Mega":{"bs":{},"gr":3},"Mawile-Mega":{"bs":{},"gr":4},"Aggron-Mega":{"bs":{},"gr":5},"Medicham-Mega":{"bs":{},"gr":0},"Manectric-Mega":{"bs":{},"gr":5},"Sharpedo-Mega":{"bs":{},"gr":5},"Camerupt-Mega":{"bs":{},"gr":4},"Altaria-Mega":{"bs":{},"gr":0},"Banette-Mega":{"bs":{},"gr":4},"Absol-Mega":{"bs":{},"gr":3},"Glalie-Mega":{"bs":{},"gr":0},"Salamence-Mega":{"bs":{},"gr":5},"Metagross-Mega":{"bs":{},"gr":5},"Latias-Mega":{"bs":{},"gr":5},"Latios-Mega":{"bs":{},"gr":5},"Lopunny-Mega":{"bs":{},"gr":0},"Garchomp-Mega":{"bs":{},"gr":5},"Lucario-Mega":{"bs":{},"gr":3},"Abomasnow-Mega":{"bs":{},"gr":5},"Gallade-Mega":{"bs":{},"gr":5},"Audino-Mega":{"bs":{},"gr":4},"Diancie-Mega":{"bs":{},"gr":5},"Milotic-Mega":{"bs":{},"gr":0},"Butterfree-Mega":{"bs":{},"gr":4},"Machamp-Mega":{"bs":{},"gr":3},"Kingler-Mega":{"bs":{},"gr":0},"Lapras-Mega":{"bs":{},"gr":5},"Flygon-Mega":{"bs":{},"gr":3},"Kingdra-Mega":{"bs":{},"gr":0},"Rayquaza-Mega":{"bs":{},"gr":5},"Kyogre-Primal":{"bs":{},"gr":5},"Groudon-Primal":{"bs":{},"gr":5},"Rattata-Alola":{"bs":{},"gr":4},"Raticate-Alola":{"bs":{},"gr":4},"Raichu-Alola":{"bs":{},"gr":0},"Sandshrew-Alola":{"bs":{},"gr":0},"Sandslash-Alola":{"bs":{},"gr":0},"Vulpix-Alola":{"bs":{},"gr":0},"Ninetales-Alola":{"bs":{},"gr":0},"Diglett-Alola":{"bs":{},"gr":0},"Dugtrio-Alola":{"bs":{},"gr":0},"Meowth-Alola":{"bs":{},"gr":0},"Persian-Alola":{"bs":{},"gr":0},"Geodude-Alola":{"bs":{},"gr":3},"Graveler-Alola":{"bs":{},"gr":3},"Golem-Alola":{"bs":{},"gr":3},"Grimer-Alola":{"bs":{},"gr":0},"Muk-Alola":{"bs":{},"gr":0},"Exeggutor-Alola":{"bs":{},"gr":0},"Marowak-Alola":{"bs":{},"gr":0},"Meowth-Galar":{"bs":{},"gr":0},"Ponyta-Galar":{"bs":{},"gr":0},"Rapidash-Galar":{"bs":{},"gr":0},"Slowpoke-Galar":{"bs":{},"gr":0},"Slowbro-Galar":{"bs":{},"gr":0},"Farfetch’d-Galar":{"bs":{},"gr":4},"Weezing-Galar":{"bs":{},"gr":0},"Mr. Mime-Galar":{"bs":{},"gr":0},"Articuno-Galar":{"bs":{},"gr":5},"Zapdos-Galar":{"bs":{},"gr":5},"Moltres-Galar":{"bs":{},"gr":5},"Slowking-Galar":{"bs":{},"gr":0},"Corsola-Galar":{"bs":{},"gr":4},"Zigzagoon-Galar":{"bs":{},"gr":0},"Linoone-Galar":{"bs":{},"gr":0},"Darumaka-Galar":{"bs":{},"gr":3},"Darmanitan-Galar":{"bs":{},"gr":3},"Yamask-Galar":{"bs":{},"gr":0},"Stunfisk-Galar":{"bs":{},"gr":0},"Pikachucosplay":{"bs":{},"gr":0},"Pikachurockstar":{"bs":{},"gr":0},"Pikachubelle":{"bs":{},"gr":0},"Pikachupopstar":{"bs":{},"gr":0},"Pikachuphd":{"bs":{},"gr":0},"Pikachulibre":{"bs":{},"gr":0},"Pikachu-Original":{"bs":{},"gr":0},"Pikachu-Hoenn":{"bs":{},"gr":0},"Pikachu-Sinnoh":{"bs":{},"gr":0},"Pikachu-Unova":{"bs":{},"gr":0},"Pikachu-Kalos":{"bs":{},"gr":0},"Pikachu-Alola":{"bs":{},"gr":0},"Pikachu-Partner":{"bs":{},"gr":0},"Pikachu-World":{"bs":{},"gr":0},"Unownemark":{"bs":{},"gr":0},"Unownqmark":{"bs":{},"gr":0},"Castform-Sunny":{"bs":{},"gr":4},"Castform-Rainy":{"bs":{},"gr":4},"Castform-Snowy":{"bs":{},"gr":4},"Deoxys-Attack":{"bs":{},"gr":5},"Deoxys-Defense":{"bs":{},"gr":5},"Deoxys-Speed":{"bs":{},"gr":5},"Wormadam-Sandy":{"bs":{},"gr":4},"Wormadam-Trash":{"bs":{},"gr":4},"Cherrim-Sunshine":{"bs":{},"gr":4},"Rotom-Heat":{"bs":{},"gr":0},"Rotom-Wash":{"bs":{},"gr":0},"Rotom-Frost":{"bs":{},"gr":0},"Rotom-Fan":{"bs":{},"gr":0},"Rotom-Mow":{"bs":{},"gr":0},"Giratina-Origin":{"bs":{},"gr":5},"Shaymin-Sky":{"bs":{},"gr":3},"Arceus-Fighting":{"bs":{},"gr":5},"Arceus-Flying":{"bs":{},"gr":5},"Arceus-Poison":{"bs":{},"gr":5},"Arceus-Ground":{"bs":{},"gr":5},"Arceus-Rock":{"bs":{},"gr":5},"Arceus-Bug":{"bs":{},"gr":5},"Arceus-Ghost":{"bs":{},"gr":5},"Arceus-Steel":{"bs":{},"gr":5},"Arceus-Fire":{"bs":{},"gr":5},"Arceus-Water":{"bs":{},"gr":5},"Arceus-Grass":{"bs":{},"gr":5},"Arceus-Electric":{"bs":{},"gr":5},"Arceus-Psychic":{"bs":{},"gr":5},"Arceus-Ice":{"bs":{},"gr":5},"Arceus-Dragon":{"bs":{},"gr":5},"Arceus-Dark":{"bs":{},"gr":5},"Arceus-Fairy":{"bs":{},"gr":5},"Basculin-Blue-Striped":{"bs":{},"gr":0},"Darmanitan-Zen":{"bs":{},"gr":3},"Darmanitanzengalar":{"bs":{},"gr":3},"Tornadus-Therian":{"bs":{},"gr":5},"Thundurus-Therian":{"bs":{},"gr":5},"Landorus-Therian":{"bs":{},"gr":5},"Kyurem-White":{"bs":{},"gr":5},"Kyurem-Black":{"bs":{},"gr":5},"Keldeo-Resolute":{"bs":{},"gr":5},"Meloetta-Pirouette":{"bs":{},"gr":5},"Genesect-Douse":{"bs":{},"gr":5},"Genesect-Shock":{"bs":{},"gr":5},"Genesect-Burn":{"bs":{},"gr":5},"Genesect-Chill":{"bs":{},"gr":5},"Greninja-Ash":{"bs":{},"gr":3},"Vivillon-Fancy":{"bs":{},"gr":0},"Vivillon-Pokeball":{"bs":{},"gr":0},"Floette-Eternal":{"bs":{},"gr":0},"Meowstic-F":{"bs":{},"gr":0},"Aegislash-Blade":{"bs":{},"gr":0},"Pumpkaboo-Small":{"bs":{},"gr":0},"Pumpkaboo-Large":{"bs":{},"gr":0},"Pumpkaboo-Super":{"bs":{},"gr":0},"Gourgeist-Small":{"bs":{},"gr":0},"Gourgeist-Large":{"bs":{},"gr":0},"Gourgeist-Super":{"bs":{},"gr":0},"Zygarde-10%":{"bs":{},"gr":5},"Zygarde-Complete":{"bs":{},"gr":5},"Hoopa-Unbound":{"bs":{},"gr":5},"Oricorio-Pom-Pom":{"bs":{},"gr":0},"Oricorio-Pa'u":{"bs":{},"gr":0},"Oricorio-Sensu":{"bs":{},"gr":0},"Lycanroc-Midnight":{"bs":{},"gr":0},"Lycanroc-Dusk":{"bs":{},"gr":0},"Wishiwashi-School":{"bs":{},"gr":4},"Silvally-Fighting":{"bs":{},"gr":5},"Silvally-Flying":{"bs":{},"gr":5},"Silvally-Poison":{"bs":{},"gr":5},"Silvally-Ground":{"bs":{},"gr":5},"Silvally-Rock":{"bs":{},"gr":5},"Silvally-Bug":{"bs":{},"gr":5},"Silvally-Ghost":{"bs":{},"gr":5},"Silvally-Steel":{"bs":{},"gr":5},"Silvally-Fire":{"bs":{},"gr":5},"Silvally-Water":{"bs":{},"gr":5},"Silvally-Grass":{"bs":{},"gr":5},"Silvally-Electric":{"bs":{},"gr":5},"Silvally-Psychic":{"bs":{},"gr":5},"Silvally-Ice":{"bs":{},"gr":5},"Silvally-Dragon":{"bs":{},"gr":5},"Silvally-Dark":{"bs":{},"gr":5},"Silvally-Fairy":{"bs":{},"gr":5},"Minior-Meteor":{"bs":{},"gr":3},"Mimikyu-Busted":{"bs":{},"gr":0},"Necrozma-Dusk-Mane":{"bs":{},"gr":5},"Necrozma-Dawn-Wings":{"bs":{},"gr":5},"Necrozma-Ultra":{"bs":{},"gr":5},"Magearna-Original":{"bs":{},"gr":5},"Cramorant-Gulping":{"bs":{},"gr":0},"Cramorant-Gorging":{"bs":{},"gr":0},"Toxtricity-Low-Key":{"bs":{},"gr":3},"Sinistea-Antique":{"bs":{},"gr":0},"Polteageist-Antique":{"bs":{},"gr":0},"Eiscue-Noice":{"bs":{},"gr":5},"Indeedee-F":{"bs":{},"gr":4},"Morpeko-Hangry":{"bs":{},"gr":0},"Zacian-Crowned":{"bs":{},"gr":5},"Zamazenta-Crowned":{"bs":{},"gr":5},"Eternatus-Eternamax":{"bs":{},"gr":5},"Urshifu-Rapid-Strike":{"bs":{},"gr":5},"Zarude-Dada":{"bs":{},"gr":5},"Calyrex-Ice":{"bs":{},"gr":5},"Calyrex-Shadow":{"bs":{},"gr":5}}

emMons = ["-----",
"Bulbasaur",
"Ivysaur",
"Venusaur",
"Charmander",
"Charmeleon",
"Charizard",
"Squirtle",
"Wartortle",
"Blastoise",
"Caterpie",
"Metapod",
"Butterfree",
"Weedle",
"Kakuna",
"Beedrill",
"Pidgey",
"Pidgeotto",
"Pidgeot",
"Rattata",
"Raticate",
"Spearow",
"Fearow",
"Ekans",
"Arbok",
"Pikachu",
"Raichu",
"Sandshrew",
"Sandslash",
"Nidoran-F",
"Nidorina",
"Nidoqueen",
"Nidoran-M",
"Nidorino",
"Nidoking",
"Clefairy",
"Clefable",
"Vulpix",
"Ninetales",
"Jigglypuff",
"Wigglytuff",
"Zubat",
"Golbat",
"Oddish",
"Gloom",
"Vileplume",
"Paras",
"Parasect",
"Venonat",
"Venomoth",
"Diglett",
"Dugtrio",
"Meowth",
"Persian",
"Psyduck",
"Golduck",
"Mankey",
"Primeape",
"Growlithe",
"Arcanine",
"Poliwag",
"Poliwhirl",
"Poliwrath",
"Abra",
"Kadabra",
"Alakazam",
"Machop",
"Machoke",
"Machamp",
"Bellsprout",
"Weepinbell",
"Victreebel",
"Tentacool",
"Tentacruel",
"Geodude",
"Graveler",
"Golem",
"Ponyta",
"Rapidash",
"Slowpoke",
"Slowbro",
"Magnemite",
"Magneton",
"Farfetch’d",
"Doduo",
"Dodrio",
"Seel",
"Dewgong",
"Grimer",
"Muk",
"Shellder",
"Cloyster",
"Gastly",
"Haunter",
"Gengar",
"Onix",
"Drowzee",
"Hypno",
"Krabby",
"Kingler",
"Voltorb",
"Electrode",
"Exeggcute",
"Exeggutor",
"Cubone",
"Marowak",
"Hitmonlee",
"Hitmonchan",
"Lickitung",
"Koffing",
"Weezing",
"Rhyhorn",
"Rhydon",
"Chansey",
"Tangela",
"Kangaskhan",
"Horsea",
"Seadra",
"Goldeen",
"Seaking",
"Staryu",
"Starmie",
"Mr-Mime",
"Scyther",
"Jynx",
"Electabuzz",
"Magmar",
"Pinsir",
"Tauros",
"Magikarp",
"Gyarados",
"Lapras",
"Ditto",
"Eevee",
"Vaporeon",
"Jolteon",
"Flareon",
"Porygon",
"Omanyte",
"Omastar",
"Kabuto",
"Kabutops",
"Aerodactyl",
"Snorlax",
"Articuno",
"Zapdos",
"Moltres",
"Dratini",
"Dragonair",
"Dragonite",
"Mewtwo",
"Mew",
"Chikorita",
"Bayleef",
"Meganium",
"Cyndaquil",
"Quilava",
"Typhlosion",
"Totodile",
"Croconaw",
"Feraligatr",
"Sentret",
"Furret",
"Hoothoot",
"Noctowl",
"Ledyba",
"Ledian",
"Spinarak",
"Ariados",
"Crobat",
"Chinchou",
"Lanturn",
"Pichu",
"Cleffa",
"Igglybuff",
"Togepi",
"Togetic",
"Natu",
"Xatu",
"Mareep",
"Flaaffy",
"Ampharos",
"Bellossom",
"Marill",
"Azumarill",
"Sudowoodo",
"Politoed",
"Hoppip",
"Skiploom",
"Jumpluff",
"Aipom",
"Sunkern",
"Sunflora",
"Yanma",
"Wooper",
"Quagsire",
"Espeon",
"Umbreon",
"Murkrow",
"Slowking",
"Misdreavus",
"Unown",
"Wobbuffet",
"Girafarig",
"Pineco",
"Forretress",
"Dunsparce",
"Gligar",
"Steelix",
"Snubbull",
"Granbull",
"Qwilfish",
"Scizor",
"Shuckle",
"Heracross",
"Sneasel",
"Teddiursa",
"Ursaring",
"Slugma",
"Magcargo",
"Swinub",
"Piloswine",
"Corsola",
"Remoraid",
"Octillery",
"Delibird",
"Mantine",
"Skarmory",
"Houndour",
"Houndoom",
"Kingdra",
"Phanpy",
"Donphan",
"Porygon2",
"Stantler",
"Smeargle",
"Tyrogue",
"Hitmontop",
"Smoochum",
"Elekid",
"Magby",
"Miltank",
"Blissey",
"Raikou",
"Entei",
"Suicune",
"Larvitar",
"Pupitar",
"Tyranitar",
"Lugia",
"Ho-Oh",
"Celebi",
"Treecko",
"Grovyle",
"Sceptile",
"Torchic",
"Combusken",
"Blaziken",
"Mudkip",
"Marshtomp",
"Swampert",
"Poochyena",
"Mightyena",
"Zigzagoon",
"Linoone",
"Wurmple",
"Silcoon",
"Beautifly",
"Cascoon",
"Dustox",
"Lotad",
"Lombre",
"Ludicolo",
"Seedot",
"Nuzleaf",
"Shiftry",
"Taillow",
"Swellow",
"Wingull",
"Pelipper",
"Ralts",
"Kirlia",
"Gardevoir",
"Surskit",
"Masquerain",
"Shroomish",
"Breloom",
"Slakoth",
"Vigoroth",
"Slaking",
"Nincada",
"Ninjask",
"Shedinja",
"Whismur",
"Loudred",
"Exploud",
"Makuhita",
"Hariyama",
"Azurill",
"Nosepass",
"Skitty",
"Delcatty",
"Sableye",
"Mawile",
"Aron",
"Lairon",
"Aggron",
"Meditite",
"Medicham",
"Electrike",
"Manectric",
"Plusle",
"Minun",
"Volbeat",
"Illumise",
"Roselia",
"Gulpin",
"Swalot",
"Carvanha",
"Sharpedo",
"Wailmer",
"Wailord",
"Numel",
"Camerupt",
"Torkoal",
"Spoink",
"Grumpig",
"Spinda",
"Trapinch",
"Vibrava",
"Flygon",
"Cacnea",
"Cacturne",
"Swablu",
"Altaria",
"Zangoose",
"Seviper",
"Lunatone",
"Solrock",
"Barboach",
"Whiscash",
"Corphish",
"Crawdaunt",
"Baltoy",
"Claydol",
"Lileep",
"Cradily",
"Anorith",
"Armaldo",
"Feebas",
"Milotic",
"Castform",
"Kecleon",
"Shuppet",
"Banette",
"Duskull",
"Dusclops",
"Tropius",
"Chimecho",
"Absol",
"Wynaut",
"Snorunt",
"Glalie",
"Spheal",
"Sealeo",
"Walrein",
"Clamperl",
"Huntail",
"Gorebyss",
"Relicanth",
"Luvdisc",
"Bagon",
"Shelgon",
"Salamence",
"Beldum",
"Metang",
"Metagross",
"Regirock",
"Regice",
"Registeel",
"Latias",
"Latios",
"Kyogre",
"Groudon",
"Rayquaza",
"Jirachi",
"Deoxys",
"Turtwig",
"Grotle",
"Torterra",
"Chimchar",
"Monferno",
"Infernape",
"Piplup",
"Prinplup",
"Empoleon",
"Starly",
"Staravia",
"Staraptor",
"Bidoof",
"Bibarel",
"Kricketot",
"Kricketune",
"Shinx",
"Luxio",
"Luxray",
"Budew",
"Roserade",
"Cranidos",
"Rampardos",
"Shieldon",
"Bastiodon",
"Burmy",
"Wormadam",
"Mothim",
"Combee",
"Vespiquen",
"Pachirisu",
"Buizel",
"Floatzel",
"Cherubi",
"Cherrim",
"Shellos",
"Gastrodon",
"Ambipom",
"Drifloon",
"Drifblim",
"Buneary",
"Lopunny",
"Mismagius",
"Honchkrow",
"Glameow",
"Purugly",
"Chingling",
"Stunky",
"Skuntank",
"Bronzor",
"Bronzong",
"Bonsly",
"Mime-Jr",
"Happiny",
"Chatot",
"Spiritomb",
"Gible",
"Gabite",
"Garchomp",
"Munchlax",
"Riolu",
"Lucario",
"Hippopotas",
"Hippowdon",
"Skorupi",
"Drapion",
"Croagunk",
"Toxicroak",
"Carnivine",
"Finneon",
"Lumineon",
"Mantyke",
"Snover",
"Abomasnow",
"Weavile",
"Magnezone",
"Lickilicky",
"Rhyperior",
"Tangrowth",
"Electivire",
"Magmortar",
"Togekiss",
"Yanmega",
"Leafeon",
"Glaceon",
"Gliscor",
"Mamoswine",
"Porygon-Z",
"Gallade",
"Probopass",
"Dusknoir",
"Froslass",
"Rotom",
"Uxie",
"Mesprit",
"Azelf",
"Dialga",
"Palkia",
"Heatran",
"Regigigas",
"Giratina",
"Cresselia",
"Phione",
"Manaphy",
"Darkrai",
"Shaymin",
"Arceus",
"Victini",
"Snivy",
"Servine",
"Serperior",
"Tepig",
"Pignite",
"Emboar",
"Oshawott",
"Dewott",
"Samurott",
"Patrat",
"Watchog",
"Lillipup",
"Herdier",
"Stoutland",
"Purrloin",
"Liepard",
"Pansage",
"Simisage",
"Pansear",
"Simisear",
"Panpour",
"Simipour",
"Munna",
"Musharna",
"Pidove",
"Tranquill",
"Unfezant",
"Blitzle",
"Zebstrika",
"Roggenrola",
"Boldore",
"Gigalith",
"Woobat",
"Swoobat",
"Drilbur",
"Excadrill",
"Audino",
"Timburr",
"Gurdurr",
"Conkeldurr",
"Tympole",
"Palpitoad",
"Seismitoad",
"Throh",
"Sawk",
"Sewaddle",
"Swadloon",
"Leavanny",
"Venipede",
"Whirlipede",
"Scolipede",
"Cottonee",
"Whimsicott",
"Petilil",
"Lilligant",
"Basculin",
"Sandile",
"Krokorok",
"Krookodile",
"Darumaka",
"Darmanitan",
"Maractus",
"Dwebble",
"Crustle",
"Scraggy",
"Scrafty",
"Sigilyph",
"Yamask",
"Cofagrigus",
"Tirtouga",
"Carracosta",
"Archen",
"Archeops",
"Trubbish",
"Garbodor",
"Zorua",
"Zoroark",
"Minccino",
"Cinccino",
"Gothita",
"Gothorita",
"Gothitelle",
"Solosis",
"Duosion",
"Reuniclus",
"Ducklett",
"Swanna",
"Vanillite",
"Vanillish",
"Vanilluxe",
"Deerling",
"Sawsbuck",
"Emolga",
"Karrablast",
"Escavalier",
"Foongus",
"Amoonguss",
"Frillish",
"Jellicent",
"Alomomola",
"Joltik",
"Galvantula",
"Ferroseed",
"Ferrothorn",
"Klink",
"Klang",
"Klinklang",
"Tynamo",
"Eelektrik",
"Eelektross",
"Elgyem",
"Beheeyem",
"Litwick",
"Lampent",
"Chandelure",
"Axew",
"Fraxure",
"Haxorus",
"Cubchoo",
"Beartic",
"Cryogonal",
"Shelmet",
"Accelgor",
"Stunfisk",
"Mienfoo",
"Mienshao",
"Druddigon",
"Golett",
"Golurk",
"Pawniard",
"Bisharp",
"Bouffalant",
"Rufflet",
"Braviary",
"Vullaby",
"Mandibuzz",
"Heatmor",
"Durant",
"Deino",
"Zweilous",
"Hydreigon",
"Larvesta",
"Volcarona",
"Cobalion",
"Terrakion",
"Virizion",
"Tornadus",
"Thundurus",
"Reshiram",
"Zekrom",
"Landorus",
"Kyurem",
"Keldeo",
"Meloetta",
"Genesect",
"Chespin",
"Quilladin",
"Chesnaught",
"Fennekin",
"Braixen",
"Delphox",
"Froakie",
"Frogadier",
"Greninja",
"Bunnelby",
"Diggersby",
"Fletchling",
"Fletchinder",
"Talonflame",
"Scatterbug",
"Spewpa",
"Vivillon",
"Litleo",
"Pyroar",
"Flabebe",
"Floette",
"Florges",
"Skiddo",
"Gogoat",
"Pancham",
"Pangoro",
"Furfrou",
"Espurr",
"Meowstic",
"Honedge",
"Doublade",
"Aegislash",
"Spritzee",
"Aromatisse",
"Swirlix",
"Slurpuff",
"Inkay",
"Malamar",
"Binacle",
"Barbaracle",
"Skrelp",
"Dragalge",
"Clauncher",
"Clawitzer",
"Helioptile",
"Heliolisk",
"Tyrunt",
"Tyrantrum",
"Amaura",
"Aurorus",
"Sylveon",
"Hawlucha",
"Dedenne",
"Carbink",
"Goomy",
"Sliggoo",
"Goodra",
"Klefki",
"Phantump",
"Trevenant",
"Pumpkaboo",
"Gourgeist",
"Bergmite",
"Avalugg",
"Noibat",
"Noivern",
"Xerneas",
"Yveltal",
"Zygarde",
"Diancie",
"Hoopa",
"Volcanion",
"Rowlet",
"Dartrix",
"Decidueye",
"Litten",
"Torracat",
"Incineroar",
"Popplio",
"Brionne",
"Primarina",
"Pikipek",
"Trumbeak",
"Toucannon",
"Yungoos",
"Gumshoos",
"Grubbin",
"Charjabug",
"Vikavolt",
"Crabrawler",
"Crabominable",
"Oricorio",
"Cutiefly",
"Ribombee",
"Rockruff",
"Lycanroc",
"Wishiwashi",
"Mareanie",
"Toxapex",
"Mudbray",
"Mudsdale",
"Dewpider",
"Araquanid",
"Fomantis",
"Lurantis",
"Morelull",
"Shiinotic",
"Salandit",
"Salazzle",
"Stufful",
"Bewear",
"Bounsweet",
"Steenee",
"Tsareena",
"Comfey",
"Oranguru",
"Passimian",
"Wimpod",
"Golisopod",
"Sandygast",
"Palossand",
"Pyukumuku",
"Type-Null",
"Silvally",
"Minior",
"Komala",
"Turtonator",
"Togedemaru",
"Mimikyu",
"Bruxish",
"Drampa",
"Dhelmise",
"Jangmo-o",
"Hakamo-o",
"Kommo-o",
"Tapu Koko",
"Tapu Lele",
"Tapu-Bulu",
"Tapu-Fini",
"Cosmog",
"Cosmoem",
"Solgaleo",
"Lunala",
"Nihilego",
"Buzzwole",
"Pheromosa",
"Xurkitree",
"Celesteela",
"Kartana",
"Guzzlord",
"Necrozma",
"Magearna",
"Marshadow",
"Poipole",
"Naganadel",
"Stakataka",
"Blacephalon",
"Zeraora",
"Meltan",
"Melmetal",
"Grookey",
"Thwackey",
"Rillaboom",
"Scorbunny",
"Raboot",
"Cinderace",
"Sobble",
"Drizzile",
"Inteleon",
"Skwovet",
"Greedent",
"Rookidee",
"Corvisquire",
"Corviknight",
"Blipbug",
"Dottler",
"Orbeetle",
"Nickit",
"Thievul",
"Gossifleur",
"Eldegoss",
"Wooloo",
"Dubwool",
"Chewtle",
"Drednaw",
"Yamper",
"Boltund",
"Rolycoly",
"Carkol",
"Coalossal",
"Applin",
"Flapple",
"Appletun",
"Silicobra",
"Sandaconda",
"Cramorant",
"Arrokuda",
"Barraskewda",
"Toxel",
"Toxtricity",
"Sizzlipede",
"Centiskorch",
"Clobbopus",
"Grapploct",
"Sinistea",
"Polteageist",
"Hatenna",
"Hattrem",
"Hatterene",
"Impidimp",
"Morgrem",
"Grimmsnarl",
"Obstagoon",
"Perrserker",
"Cursola",
"Sirfetch’d",
"Mr-Rime",
"Runerigus",
"Milcery",
"Alcremie",
"Falinks",
"Pincurchin",
"Snom",
"Frosmoth",
"Stonjourner",
"Eiscue",
"Indeedee",
"Morpeko",
"Cufant",
"Copperajah",
"Dracozolt",
"Arctozolt",
"Dracovish",
"Arctovish",
"Duraludon",
"Dreepy",
"Drakloak",
"Dragapult",
"Zacian",
"Zamazenta",
"Eternatus",
"Kubfu",
"Urshifu",
"Zarude",
"Regieleki",
"Regidrago",
"Glastrier",
"Spectrier",
"Calyrex",
"Venusaur-Mega",
"Charizard-Mega-X",
"Charizard-Mega-Y",
"Blastoise-Mega",
"Beedrill-Mega",
"Pidgeot-Mega",
"Alakazam-Mega",
"Slowbro-Mega",
"Gengar-Mega",
"Kangaskhan-Mega",
"Pinsir-Mega",
"Gyarados-Mega",
"Aerodactyl-Mega",
"Mewtwo-Mega-X",
"Mewtwo-Mega-Y",
"Ampharos-Mega",
"Steelix-Mega",
"Scizor-Mega",
"Heracross-Mega",
"Houndoom-Mega",
"Tyranitar-Mega",
"Sceptile-Mega",
"Blaziken-Mega",
"Swampert-Mega",
"Gardevoir-Mega",
"Sableye-Mega",
"Mawile-Mega",
"Aggron-Mega",
"Medicham-Mega",
"Manectric-Mega",
"Sharpedo-Mega",
"Camerupt-Mega",
"Altaria-Mega",
"Banette-Mega",
"Absol-Mega",
"Glalie-Mega",
"Salamence-Mega",
"Metagross-Mega",
"Latias-Mega",
"Latios-Mega",
"Lopunny-Mega",
"Garchomp-Mega",
"Lucario-Mega",
"Abomasnow-Mega",
"Gallade-Mega",
"Audino-Mega",
"Diancie-Mega",
"Milotic-Mega",
"Butterfree-Mega",
"Machamp-Mega",
"Kingler-Mega",
"Lapras-Mega",
"Flygon-Mega",
"Kingdra-Mega",
"Rayquaza-Mega",
"Kyogre-Primal",
"Groudon-Primal",
"Rattata-Alola",
"Raticate-Alola",
"Raichu-Alola",
"Sandshrew-Alola",
"Sandslash-Alola",
"Vulpix-Alola",
"Ninetales-Alola",
"Diglett-Alola",
"Dugtrio-Alola",
"Meowth-Alola",
"Persian-Alola",
"Geodude-Alola",
"Graveler-Alola",
"Golem-Alola",
"Grimer-Alola",
"Muk-Alola",
"Exeggutor-Alola",
"Marowak-Alola",
"Meowth-Galarian",
"Ponyta-Galarian",
"Rapidash-Galarian",
"Slowpoke-Galarian",
"Slowbro-Galarian",
"Farfetch’d-Galarian",
"Weezing-Galarian",
"Mr-Mime-Galarian",
"Articuno-Galarian",
"Zapdos-Galarian",
"Moltres-Galarian",
"Slowking-Galarian",
"Corsola-Galarian",
"Zigzagoon-Galarian",
"Linoone-Galarian",
"Darumaka-Galarian",
"Darmanitan-Galarian",
"Yamask-Galarian",
"Stunfisk-Galarian",
"Pikachu-Cosplay",
"Pikachu-Rock-Star",
"Pikachu-Belle",
"Pikachu-Pop-Star",
"Pikachu-Ph-D",
"Pikachu-Libre",
"Pikachu-Original-Cap",
"Pikachu-Hoenn-Cap",
"Pikachu-Sinnoh-Cap",
"Pikachu-Unova-Cap",
"Pikachu-Kalos-Cap",
"Pikachu-Alola-Cap",
"Pikachu-Partner-Cap",
"Pikachu-World-Cap",
"Pichu-Spiky-Eared",
"Unown-B",
"Unown-C",
"Unown-D",
"Unown-E",
"Unown-F",
"Unown-G",
"Unown-H",
"Unown-I",
"Unown-J",
"Unown-K",
"Unown-L",
"Unown-M",
"Unown-N",
"Unown-O",
"Unown-P",
"Unown-Q",
"Unown-R",
"Unown-S",
"Unown-T",
"Unown-U",
"Unown-V",
"Unown-W",
"Unown-X",
"Unown-Y",
"Unown-Z",
"Unown-Emark",
"Unown-Qmark",
"Castform-Sunny",
"Castform-Rainy",
"Castform-Snowy",
"Deoxys-Attack",
"Deoxys-Defense",
"Deoxys-Speed",
"Burmy-Sandy-Cloak",
"Burmy-Trash-Cloak",
"Wormadam-Sandy",
"Wormadam-Trash",
"Cherrim-Sunshine",
"Shellos-East-Sea",
"Gastrodon",
"Rotom-Heat",
"Rotom-Wash",
"Rotom-Frost",
"Rotom-Fan",
"Rotom-Mow",
"Giratina-Origin",
"Shaymin-Sky",
"Arceus-Fighting",
"Arceus-Flying",
"Arceus-Poison",
"Arceus-Ground",
"Arceus-Rock",
"Arceus-Bug",
"Arceus-Ghost",
"Arceus-Steel",
"Arceus-Fire",
"Arceus-Water",
"Arceus-Grass",
"Arceus-Electric",
"Arceus-Psychic",
"Arceus-Ice",
"Arceus-Dragon",
"Arceus-Dark",
"Arceus-Fairy",
"Basculin-Blue-Striped",
"Darmanitan-Zen-Mode",
"Darmanitan-Zen-Mode-Galarian",
"Deerling-Summer",
"Deerling-Autumn",
"Deerling-Winter",
"Sawsbuck-Summer",
"Sawsbuck-Autumn",
"Sawsbuck-Winter",
"Tornadus-Therian",
"Thundurus-Therian",
"Landorus-Therian",
"Kyurem-White",
"Kyurem-Black",
"Keldeo-Resolute",
"Meloetta-Pirouette",
"Genesect-Douse-Drive",
"Genesect-Shock-Drive",
"Genesect-Burn-Drive",
"Genesect-Chill-Drive",
"Greninja-Battle-Bond",
"Greninja-Ash",
"Vivillon-Polar",
"Vivillon-Tundra",
"Vivillon-Continental",
"Vivillon-Garden",
"Vivillon-Elegant",
"Vivillon-Meadow",
"Vivillon-Modern",
"Vivillon-Marine",
"Vivillon-Archipelago",
"Vivillon-High-Plains",
"Vivillon-Sandstorm",
"Vivillon-River",
"Vivillon-Monsoon",
"Vivillon-Savanna",
"Vivillon-Sun",
"Vivillon-Ocean",
"Vivillon-Jungle",
"Vivillon-Fancy",
"Vivillon-Poke-Ball",
"Flabebe-Yellow-Flower",
"Flabebe-Orange-Flower",
"Flabebe-Blue-Flower",
"Flabebe-White-Flower",
"Floette-Yellow-Flower",
"Floette-Orange-Flower",
"Floette-Blue-Flower",
"Floette-White-Flower",
"Floette-Eternal-Flower",
"Florges-Yellow-Flower",
"Florges-Orange-Flower",
"Florges-Blue-Flower",
"Florges-White-Flower",
"Furfrou-Heart-Trim",
"Furfrou-Star-Trim",
"Furfrou-Diamond-Trim",
"Furfrou-Debutante-Trim",
"Furfrou-Matron-Trim",
"Furfrou-Dandy-Trim",
"Furfrou-La-Reine-Trim",
"Furfrou-Kabuki-Trim",
"Furfrou-Pharaoh-Trim",
"Meowstic-F",
"Aegislash-Blade",
"Pumpkaboo-Small",
"Pumpkaboo-Large",
"Pumpkaboo-Super",
"Gourgeist-Small",
"Gourgeist-Large",
"Gourgeist-Super",
"Xerneas-Active",
"Zygarde-10",
"Zygarde-10-Power-Construct",
"Zygarde-50-Power-Construct",
"Zygarde-Complete",
"Hoopa-Unbound",
"Oricorio-Pom-Pom",
"Oricorio-Pau",
"Oricorio-Sensu",
"Rockruff-Own-Tempo",
"Lycanroc-Midnight",
"Lycanroc-Dusk",
"Wishiwashi-School",
"Silvally-Fighting",
"Silvally-Flying",
"Silvally-Poison",
"Silvally-Ground",
"Silvally-Rock",
"Silvally-Bug",
"Silvally-Ghost",
"Silvally-Steel",
"Silvally-Fire",
"Silvally-Water",
"Silvally-Grass",
"Silvally-Electric",
"Silvally-Psychic",
"Silvally-Ice",
"Silvally-Dragon",
"Silvally-Dark",
"Silvally-Fairy",
"Minior-Meteor-Orange",
"Minior-Meteor-Yellow",
"Minior-Meteor-Green",
"Minior-Meteor-Blue",
"Minior-Meteor-Indigo",
"Minior-Meteor-Violet",
"Minior-Core-Red",
"Minior-Core-Orange",
"Minior-Core-Yellow",
"Minior-Core-Green",
"Minior-Core-Blue",
"Minior-Core-Indigo",
"Minior-Core-Violet",
"Mimikyu-Busted",
"Necrozma-Dusk-Mane",
"Necrozma-Dawn-Wings",
"Necrozma-Ultra",
"Magearna-Original-Color",
"Cramorant-Gulping",
"Cramorant-Gorging",
"Toxtricity-Low-Key",
"Sinistea-Antique",
"Polteageist-Antique",
"Alcremie-Ruby-Cream",
"Alcremie-Matcha-Cream",
"Alcremie-Mint-Cream",
"Alcremie-Lemon-Cream",
"Alcremie-Salted-Cream",
"Alcremie-Ruby-Swirl",
"Alcremie-Caramel-Swirl",
"Alcremie-Rainbow-Swirl",
"Eiscue-Noice-Face",
"Indeedee-Female",
"Morpeko-Hangry",
"Zacian-Crowned-Sword",
"Zamazenta-Crowned-Shield",
"Eternatus-Eternamax",
"Urshifu-Rapid-Strike-Style",
"Zarude-Dada",
"Calyrex-Ice",
"Calyrex-Shadow"]

pokeemeraldMoves = ["None",
"Pound",
"Karate Chop",
"Double Slap",
"Comet Punch",
"Mega Punch",
"Pay Day",
"Fire Punch",
"Ice Punch",
"Thunder Punch",
"Scratch",
"Vise Grip",
"Guillotine",
"Razor Wind",
"Swords Dance",
"Cut",
"Gust",
"Wing Attack",
"Whirlwind",
"Fly",
"Bind",
"Slam",
"Vine Whip",
"Stomp",
"Double Kick",
"Mega Kick",
"Jump Kick",
"Rolling Kick",
"Sand-Attack",
"Headbutt",
"Horn Attack",
"Fury Attack",
"Horn Drill",
"Tackle",
"Body Slam",
"Wrap",
"Take Down",
"Thrash",
"Double-Edge",
"Tail Whip",
"Poison Sting",
"Twineedle",
"Pin Missile",
"Leer",
"Bite",
"Growl",
"Roar",
"Sing",
"Supersonic",
"Sonic Boom",
"Disable",
"Acid",
"Ember",
"Flamethrower",
"Mist",
"Water Gun",
"Hydro Pump",
"Surf",
"Ice Beam",
"Blizzard",
"Psybeam",
"Bubble Beam",
"Aurora Beam",
"Hyper Beam",
"Peck",
"Drill Peck",
"Submission",
"Low Kick",
"Counter",
"Seismic Toss",
"Strength",
"Absorb",
"Mega Drain",
"Leech Seed",
"Growth",
"Razor Leaf",
"Solar Beam",
"Poison Powder",
"Stun Spore",
"Sleep Powder",
"Petal Dance",
"String Shot",
"Dragon Rage",
"Fire Spin",
"Thunder Shock",
"Thunderbolt",
"Thunder Wave",
"Thunder",
"Rock Throw",
"Earthquake",
"Fissure",
"Dig",
"Toxic",
"Confusion",
"Psychic",
"Hypnosis",
"Meditate",
"Agility",
"Quick Attack",
"Rage",
"Teleport",
"Night Shade",
"Mimic",
"Screech",
"Double Team",
"Recover",
"Harden",
"Minimize",
"Smokescreen",
"Confuse Ray",
"Withdraw",
"Defense Curl",
"Barrier",
"Light Screen",
"Haze",
"Reflect",
"Focus Energy",
"Bide",
"Metronome",
"Mirror Move",
"Self Destruct",
"Egg Bomb",
"Lick",
"Smog",
"Sludge",
"Bone Club",
"Fire Blast",
"Waterfall",
"Clamp",
"Swift",
"Skull Bash",
"Spike Cannon",
"Constrict",
"Amnesia",
"Kinesis",
"Soft Boiled",
"High Jump Kick",
"Glare",
"Dream Eater",
"Poison Gas",
"Barrage",
"Leech Life",
"Lovely Kiss",
"Sky Attack",
"Transform",
"Bubble",
"Dizzy Punch",
"Spore",
"Flash",
"Psywave",
"Splash",
"Acid Armor",
"Crabhammer",
"Explosion",
"Fury Swipes",
"Bonemerang",
"Rest",
"Rock Slide",
"Hyper Fang",
"Sharpen",
"Conversion",
"Tri Attack",
"Super Fang",
"Slash",
"Substitute",
"Struggle",
"Sketch",
"Triple Kick",
"Thief",
"Spider Web",
"Mind Reader",
"Nightmare",
"Flame Wheel",
"Snore",
"Curse",
"Flail",
"Conversion 2",
"Aeroblast",
"Cotton Spore",
"Reversal",
"Spite",
"Powder Snow",
"Protect",
"Mach Punch",
"Scary Face",
"Feint Attack",
"Sweet Kiss",
"Belly Drum",
"Sludge Bomb",
"Mud-Slap",
"Octazooka",
"Spikes",
"Zap Cannon",
"Foresight",
"Destiny Bond",
"Perish Song",
"Icy Wind",
"Detect",
"Bone Rush",
"Lock On",
"Outrage",
"Sandstorm",
"Giga Drain",
"Endure",
"Charm",
"Rollout",
"False Swipe",
"Swagger",
"Milk Drink",
"Spark",
"Fury Cutter",
"Steel Wing",
"Mean Look",
"Attract",
"Sleep Talk",
"Heal Bell",
"Return",
"Present",
"Frustration",
"Safeguard",
"Pain Split",
"Sacred Fire",
"Magnitude",
"Dynamic Punch",
"Megahorn",
"Dragon Breath",
"Baton Pass",
"Encore",
"Pursuit",
"Rapid Spin",
"Sweet Scent",
"Iron Tail",
"Metal Claw",
"Vital Throw",
"Morning Sun",
"Synthesis",
"Moonlight",
"Hidden Power",
"Cross Chop",
"Twister",
"Rain Dance",
"Sunny Day",
"Crunch",
"Mirror Coat",
"Psych Up",
"Extreme Speed",
"Ancient Power",
"Shadow Ball",
"Future Sight",
"Rock Smash",
"Whirlpool",
"Beat Up",
"Fake Out",
"Uproar",
"Stockpile",
"Spit Up",
"Swallow",
"Heat Wave",
"Hail",
"Torment",
"Flatter",
"Will-O-Wisp",
"Memento",
"Facade",
"Focus Punch",
"Smelling Salts",
"Follow Me",
"Nature Power",
"Charge",
"Taunt",
"Helping Hand",
"Trick",
"Role Play",
"Wish",
"Assist",
"Ingrain",
"Superpower",
"Magic Coat",
"Recycle",
"Revenge",
"Brick Break",
"Yawn",
"Knock Off",
"Endeavor",
"Eruption",
"Skill Swap",
"Imprison",
"Refresh",
"Grudge",
"Snatch",
"Secret Power",
"Dive",
"Arm Thrust",
"Camouflage",
"Tail Glow",
"Luster Purge",
"Mist Ball",
"Feather Dance",
"Teeter Dance",
"Blaze Kick",
"Mud Sport",
"Ice Ball",
"Needle Arm",
"Slack Off",
"Hyper Voice",
"Poison Fang",
"Crush Claw",
"Blast Burn",
"Hydro Cannon",
"Meteor Mash",
"Astonish",
"Weather Ball",
"Aromatherapy",
"Fake Tears",
"Air Cutter",
"Overheat",
"Odor Sleuth",
"Rock Tomb",
"Silver Wind",
"Metal Sound",
"Grass Whistle",
"Tickle",
"Cosmic Power",
"Water Spout",
"Signal Beam",
"Shadow Punch",
"Extrasensory",
"Sky Uppercut",
"Sand Tomb",
"Sheer Cold",
"Muddy Water",
"Bullet Seed",
"Aerial Ace",
"Icicle Spear",
"Iron Defense",
"Block",
"Howl",
"Dragon Claw",
"Frenzy Plant",
"Bulk Up",
"Bounce",
"Mud Shot",
"Poison Tail",
"Covet",
"Volt Tackle",
"Magical Leaf",
"Water Sport",
"Calm Mind",
"Leaf Blade",
"Dragon Dance",
"Rock Blast",
"Shock Wave",
"Water Pulse",
"Doom Desire",
"Psycho Boost",
"Roost",
"Gravity",
"Miracle Eye",
"Wake-Up Slap",
"Hammer Arm",
"Gyro Ball",
"Healing Wish",
"Brine",
"Natural Gift",
"Feint",
"Pluck",
"Tailwind",
"Acupressure",
"Metal Burst",
"U-turn",
"Close Combat",
"Payback",
"Assurance",
"Embargo",
"Fling",
"Psycho Shift",
"Trump Card",
"Heal Block",
"Wring Out",
"Power Trick",
"Gastro Acid",
"Lucky Chant",
"Me First",
"Copycat",
"Power Swap",
"Guard Swap",
"Punishment",
"Last Resort",
"Worry Seed",
"Sucker Punch",
"Toxic Spikes",
"Heart Swap",
"Aqua Ring",
"Magnet Rise",
"Flare Blitz",
"Force Palm",
"Aura Sphere",
"Rock Polish",
"Poison Jab",
"Dark Pulse",
"Night Slash",
"Aqua Tail",
"Seed Bomb",
"Air Slash",
"X-Scissor",
"Bug Buzz",
"Dragon Pulse",
"Dragon Rush",
"Power Gem",
"Drain Punch",
"Vacuum Wave",
"Focus Blast",
"Energy Ball",
"Brave Bird",
"Earth Power",
"Switcheroo",
"Giga Impact",
"Nasty Plot",
"Bullet Punch",
"Avalanche",
"Ice Shard",
"Shadow Claw",
"Thunder Fang",
"Ice Fang",
"Fire Fang",
"Shadow Sneak",
"Mud Bomb",
"Psycho Cut",
"Zen Headbutt",
"Mirror Shot",
"Flash Cannon",
"Rock Climb",
"Defog",
"Trick Room",
"Draco Meteor",
"Discharge",
"Lava Plume",
"Leaf Storm",
"Power Whip",
"Rock Wrecker",
"Cross Poison",
"Gunk Shot",
"Iron Head",
"Magnet Bomb",
"Stone Edge",
"Captivate",
"Stealth Rock",
"Grass Knot",
"Chatter",
"Judgment",
"Bug Bite",
"Charge Beam",
"Wood Hammer",
"Aqua Jet",
"Attack Order",
"Defend Order",
"Heal Order",
"Head Smash",
"Double Hit",
"Roar Of Time",
"Spacial Rend",
"Lunar Dance",
"Crush Grip",
"Magma Storm",
"Dark Void",
"Seed Flare",
"Ominous Wind",
"Shadow Force",
"Hone Claws",
"Wide Guard",
"Guard Split",
"Power Split",
"Wonder Room",
"Psyshock",
"Venoshock",
"Autotomize",
"Rage Powder",
"Telekinesis",
"Magic Room",
"Smack Down",
"Storm Throw",
"Flame Burst",
"Sludge Wave",
"Quiver Dance",
"Heavy Slam",
"Synchronoise",
"Electro Ball",
"Soak",
"Flame Charge",
"Coil",
"Low Sweep",
"Acid Spray",
"Foul Play",
"Simple Beam",
"Entrainment",
"After You",
"Round",
"Echoed Voice",
"Chip Away",
"Clear Smog",
"Stored Power",
"Quick Guard",
"Ally Switch",
"Scald",
"Shell Smash",
"Heal Pulse",
"Hex",
"Sky Drop",
"Shift Gear",
"Circle Throw",
"Incinerate",
"Quash",
"Acrobatics",
"Reflect Type",
"Retaliate",
"Final Gambit",
"Bestow",
"Inferno",
"Water Pledge",
"Fire Pledge",
"Grass Pledge",
"Volt Switch",
"Struggle Bug",
"Bulldoze",
"Frost Breath",
"Dragon Tail",
"Work Up",
"Electroweb",
"Wild Charge",
"Drill Run",
"Dual Chop",
"Heart Stamp",
"Horn Leech",
"Sacred Sword",
"Razor Shell",
"Heat Crash",
"Leaf Tornado",
"Steamroller",
"Cotton Guard",
"Night Daze",
"Psystrike",
"Tail Slap",
"Hurricane",
"Head Charge",
"Gear Grind",
"Searing Shot",
"Techno Blast",
"Relic Song",
"Secret Sword",
"Glaciate",
"Bolt Strike",
"Blue Flare",
"Fiery Dance",
"Freeze Shock",
"Ice Burn",
"Snarl",
"Icicle Crash",
"V-create",
"Fusion Flare",
"Fusion Bolt",
"Flying Press",
"Mat Block",
"Belch",
"Rototiller",
"Sticky Web",
"Fell Stinger",
"Phantom Force",
"Trick-or-Treat",
"Noble Roar",
"Ion Deluge",
"Parabolic Charge",
"Forests Curse",
"Petal Blizzard",
"Freeze-Dry",
"Disarming Voice",
"Parting Shot",
"Topsy-Turvy",
"Draining Kiss",
"Crafty Shield",
"Flower Shield",
"Grassy Terrain",
"Misty Terrain",
"Electrify",
"Play Rough",
"Fairy Wind",
"Moonblast",
"Boomburst",
"Fairy Lock",
"Kings Shield",
"Play Nice",
"Confide",
"Diamond Storm",
"Steam Eruption",
"Hyperspace Hole",
"Water Shuriken",
"Mystical Fire",
"Spiky Shield",
"Aromatic Mist",
"Eerie Impulse",
"Venom Drench",
"Powder",
"Geomancy",
"Magnetic Flux",
"Happy Hour",
"Electric Terrain",
"Dazzling Gleam",
"Celebrate",
"Hold Hands",
"Baby-Doll Eyes",
"Nuzzle",
"Hold Back",
"Infestation",
"Power-Up Punch",
"Oblivion Wing",
"Thousand Arrows",
"Thousand Waves",
"Lands Wrath",
"Light Of Ruin",
"Origin Pulse",
"Precipice Blades",
"Dragon Ascent",
"Hyperspace Fury",
"Shore Up",
"First Impression",
"Baneful Bunker",
"Spirit Shackle",
"Darkest Lariat",
"Sparkling Aria",
"Ice Hammer",
"Floral Healing",
"High Horsepower",
"Strength Sap",
"Solar Blade",
"Leafage",
"Spotlight",
"Toxic Thread",
"Laser Focus",
"Gear Up",
"Throat Chop",
"Pollen Puff",
"Anchor Shot",
"Psychic Terrain",
"Lunge",
"Fire Lash",
"Power Trip",
"Burn Up",
"Speed Swap",
"Smart Strike",
"Purify",
"Revelation Dance",
"Core Enforcer",
"Trop Kick",
"Instruct",
"Beak Blast",
"Clanging Scales",
"Dragon Hammer",
"Brutal Swing",
"Aurora Veil",
"Shell Trap",
"Fleur Cannon",
"Psychic Fangs",
"Stomping Tantrum",
"Shadow Bone",
"Accelerock",
"Liquidation",
"Prismatic Laser",
"Spectral Thief",
"Sunsteel Strike",
"Moongeist Beam",
"Tearful Look",
"Zing Zap",
"Natures Madness",
"Multi-Attack",
"Mind Blown",
"Plasma Fists",
"Photon Geyser",
"Zippy Zap",
"Splishy Splash",
"Floaty Fall",
"Pika Papow",
"Bouncy Bubble",
"Buzzy Buzz",
"Sizzly Slide",
"Glitzy Glow",
"Baddy Bad",
"Sappy Seed",
"Freezy Frost",
"Sparkly Swirl",
"Veevee Volley",
"Double Iron Bash",
"Dynamax Cannon",
"Snipe Shot",
"Jaw Lock",
"Stuff Cheeks",
"No Retreat",
"Tar Shot",
"Magic Powder",
"Dragon Darts",
"Teatime",
"Octolock",
"Bolt Beak",
"Fishious Rend",
"Court Change",
"Clangorous Soul",
"Body Press",
"Decorate",
"Drum Beating",
"Snap Trap",
"Pyro Ball",
"Behemoth Blade",
"Behemoth Bash",
"Aura Wheel",
"Breaking Swipe",
"Branch Poke",
"Overdrive",
"Apple Acid",
"Grav Apple",
"Spirit Break",
"Strange Steam",
"Life Dew",
"Obstruct",
"False Surrender",
"Meteor Assault",
"Eternabeam",
"Steel Beam",
"Expanding Force",
"Steel Roller",
"Scale Shot",
"Meteor Beam",
"Shell Side Arm",
"Misty Explosion",
"Grassy Glide",
"Rising Voltage",
"Terrain Pulse",
"Skitter Smack",
"Burning Jealousy",
"Lash Out",
"Poltergeist",
"Corrosive Gas",
"Coaching",
"Flip Turn",
"Triple Axel",
"Dual Wingbeat",
"Scorching Sands",
"Jungle Healing",
"Wicked Blow",
"Surging Strikes",
"Thunder Cage",
"Dragon Energy",
"Freezing Glare",
"Fiery Wrath",
"Thunderous Kick",
"Glacial Lance",
"Astral Barrage",
"Eerie Spell",
"Dire Claw",
"Psyshield Bash",
"Power Shift",
"Stone Axe",
"Springtide Storm",
"Mystical Power",
"Raging Fury",
"Wave Crash",
"Chloroblast",
"Mountain Gale",
"Victory Dance",
"Headlong Rush",
"Barb Barrage",
"Esper Wing",
"Bitter Malice",
"Shelter",
"Triple Arrows",
"Infernal Parade",
"Ceaseless Edge",
"Bleakwind Storm",
"Wildbolt Storm",
"Sandsear Storm",
"Lunar Blessing",
"Take Heart",
"Tera Blast",
"Silk Trap",
"Axe Kick",
"Last Respects",
"Lumina Crash",
"Order Up",
"Jet Punch",
"Spicy Extract",
"Spin Out",
"Population Bomb",
"Ice Spinner",
"Glaive Rush",
"Revival Blessing",
"Salt Cure",
"Triple Dive",
"Mortal Spin",
"Doodle",
"Fillet Away",
"Kowtow Cleave",
"Flower Trick",
"Torch Song",
"Aqua Step",
"Raging Bull",
"Make It Rain",
"Ruination",
"Collision Course",
"Electro Drift",
"Shed Tail",
"Chilly Reception",
"Tidy Up",
"Snowscape",
"Pounce",
"Trailblaze",
"Chilling Water",
"Hyper Drill",
"Twin Beam",
"Rage Fist",
"Armor Cannon",
"Bitter Blade",
"Double Shock",
"Gigaton Hammer",
"Comeuppance",
"Aqua Cutter",
"Blazing Torque",
"Wicked Torque",
"Noxious Torque",
"Combat Torque",
"Magical Torque",
"Psyblade",
"Hydro Steam",
"Blood Moon",
"Matcha Gotcha",
"Syrup Bomb",
"Ivy Cudgel",
"Electro Shot",
"Tera Starstorm",
"Fickle Beam",
"Burning Bulwark",
"Thunderclap",
"Mighty Cleave",
"Tachyon Cutter",
"Hard Press",
"Dragon Cheer",
"Alluring Voice",
"Temper Flare",
"Supercell Slam",
"Psychic Noise",
"Upper Hand",
"Malignant Chain",
"Aqua Fang",
"Dark Hole"]

emItems = []
